// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/webhooktemplates/v1/webhook_templates.proto

package webhooktemplatesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type WebhookTemplateError int32

const (
	WebhookTemplateError_WEBHOOK_TEMPLATE_ERROR_INVALID_REQUEST WebhookTemplateError = 0
)

// Enum value maps for WebhookTemplateError.
var (
	WebhookTemplateError_name = map[int32]string{
		0: "WEBHOOK_TEMPLATE_ERROR_INVALID_REQUEST",
	}
	WebhookTemplateError_value = map[string]int32{
		"WEBHOOK_TEMPLATE_ERROR_INVALID_REQUEST": 0,
	}
)

func (x WebhookTemplateError) Enum() *WebhookTemplateError {
	p := new(WebhookTemplateError)
	*p = x
	return p
}

func (x WebhookTemplateError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookTemplateError) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_enumTypes[0].Descriptor()
}

func (WebhookTemplateError) Type() protoreflect.EnumType {
	return &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_enumTypes[0]
}

func (x WebhookTemplateError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookTemplateError.Descriptor instead.
func (WebhookTemplateError) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescGZIP(), []int{0}
}

// Validates a Handlebars template against a JSON object supplied as sample context.
//
// The context is JSON rather than google.protobuf.Struct because Handlebars evaluation must retain the
// JSON numeric values and object-member order supplied by callers. Struct lowers every JSON number to a
// double, which is lossy for large integer values. The server requires a JSON object and caps its UTF-8
// representation at 64 KiB.
type ValidateTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Handlebars template that must render to a JSON object.
	Template string `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	// JSON object providing values that the template can reference.
	SampleContextJson string `protobuf:"bytes,2,opt,name=sample_context_json,json=sampleContextJson,proto3" json:"sample_context_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidateTemplateRequest) Reset() {
	*x = ValidateTemplateRequest{}
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTemplateRequest) ProtoMessage() {}

func (x *ValidateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTemplateRequest.ProtoReflect.Descriptor instead.
func (*ValidateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTemplateRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *ValidateTemplateRequest) GetSampleContextJson() string {
	if x != nil {
		return x.SampleContextJson
	}
	return ""
}

type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable explanation of why the template could not be validated.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateTemplateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the template renders successfully to a JSON object.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Rendered JSON object when validation succeeds.
	EvaluatedPayload *string `protobuf:"bytes,2,opt,name=evaluated_payload,json=evaluatedPayload,proto3,oneof" json:"evaluated_payload,omitempty"`
	// Problems found while compiling, rendering, or parsing the template.
	Errors        []*ValidationError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTemplateResponse) Reset() {
	*x = ValidateTemplateResponse{}
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTemplateResponse) ProtoMessage() {}

func (x *ValidateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTemplateResponse.ProtoReflect.Descriptor instead.
func (*ValidateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTemplateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTemplateResponse) GetEvaluatedPayload() string {
	if x != nil && x.EvaluatedPayload != nil {
		return *x.EvaluatedPayload
	}
	return ""
}

func (x *ValidateTemplateResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Sends a single test delivery through an existing simple-webhook integration.
type TestWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Existing SimpleWebhookIntegration used for the delivery.
	IntegrationRid string `protobuf:"bytes,1,opt,name=integration_rid,json=integrationRid,proto3" json:"integration_rid,omitempty"`
	// Handlebars template that must render to the JSON object delivered to the integration.
	Template string `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// JSON object providing values that the template can reference.
	SampleContextJson string `protobuf:"bytes,3,opt,name=sample_context_json,json=sampleContextJson,proto3" json:"sample_context_json,omitempty"`
	// Value for the webhook event-type header. Defaults to test.webhook when omitted.
	EventType     *string `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3,oneof" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookRequest) Reset() {
	*x = TestWebhookRequest{}
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookRequest) ProtoMessage() {}

func (x *TestWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookRequest.ProtoReflect.Descriptor instead.
func (*TestWebhookRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescGZIP(), []int{3}
}

func (x *TestWebhookRequest) GetIntegrationRid() string {
	if x != nil {
		return x.IntegrationRid
	}
	return ""
}

func (x *TestWebhookRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *TestWebhookRequest) GetSampleContextJson() string {
	if x != nil {
		return x.SampleContextJson
	}
	return ""
}

func (x *TestWebhookRequest) GetEventType() string {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return ""
}

type TestWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the endpoint responded with a 2xx status.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// HTTP status returned by the endpoint, or zero when no HTTP request was sent.
	StatusCode int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Response body captured from the endpoint, when present.
	ResponseBody *string `protobuf:"bytes,3,opt,name=response_body,json=responseBody,proto3,oneof" json:"response_body,omitempty"`
	// Human-readable failure explanation, when present.
	ErrorMessage *string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// JSON object rendered from the template, when rendering completed.
	EvaluatedPayload *string `protobuf:"bytes,5,opt,name=evaluated_payload,json=evaluatedPayload,proto3,oneof" json:"evaluated_payload,omitempty"`
	// Time spent delivering the webhook, in milliseconds.
	LatencyMillis int64 `protobuf:"varint,6,opt,name=latency_millis,json=latencyMillis,proto3" json:"latency_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookResponse) Reset() {
	*x = TestWebhookResponse{}
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookResponse) ProtoMessage() {}

func (x *TestWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookResponse.ProtoReflect.Descriptor instead.
func (*TestWebhookResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescGZIP(), []int{4}
}

func (x *TestWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestWebhookResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TestWebhookResponse) GetResponseBody() string {
	if x != nil && x.ResponseBody != nil {
		return *x.ResponseBody
	}
	return ""
}

func (x *TestWebhookResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *TestWebhookResponse) GetEvaluatedPayload() string {
	if x != nil && x.EvaluatedPayload != nil {
		return *x.EvaluatedPayload
	}
	return ""
}

func (x *TestWebhookResponse) GetLatencyMillis() int64 {
	if x != nil {
		return x.LatencyMillis
	}
	return 0
}

var File_nominal_protos_webhooktemplates_v1_webhook_templates_proto protoreflect.FileDescriptor

const file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDesc = "" +
	"\n" +
	":nominal/protos/webhooktemplates/v1/webhook_templates.proto\x12\x1bnominal.webhooktemplates.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a!nominal/protos/gen/v1/alias.proto\x1a!nominal/protos/gen/v1/error.proto\"{\n" +
	"\x17ValidateTemplateRequest\x12%\n" +
	"\btemplate\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x10R\btemplate\x129\n" +
	"\x13sample_context_json\x18\x02 \x01(\tB\t\xbaH\x06r\x04(\x80\x80\x04R\x11sampleContextJson\"+\n" +
	"\x0fValidationError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbe\x01\n" +
	"\x18ValidateTemplateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x120\n" +
	"\x11evaluated_payload\x18\x02 \x01(\tH\x00R\x10evaluatedPayload\x88\x01\x01\x12D\n" +
	"\x06errors\x18\x03 \x03(\v2,.nominal.webhooktemplates.v1.ValidationErrorR\x06errorsB\x14\n" +
	"\x12_evaluated_payload\"\x94\x02\n" +
	"\x12TestWebhookRequest\x12_\n" +
	"\x0fintegration_rid\x18\x01 \x01(\tB6\x9a\xb2\x1a2\n" +
	"0io.nominal.scout.integrations.api.IntegrationRidR\x0eintegrationRid\x12%\n" +
	"\btemplate\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x10R\btemplate\x129\n" +
	"\x13sample_context_json\x18\x03 \x01(\tB\t\xbaH\x06r\x04(\x80\x80\x04R\x11sampleContextJson\x12,\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bH\x00R\teventType\x88\x01\x01B\r\n" +
	"\v_event_type\"\xb7\x02\n" +
	"\x13TestWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\rresponse_body\x18\x03 \x01(\tH\x00R\fresponseBody\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x120\n" +
	"\x11evaluated_payload\x18\x05 \x01(\tH\x02R\x10evaluatedPayload\x88\x01\x01\x12%\n" +
	"\x0elatency_millis\x18\x06 \x01(\x03R\rlatencyMillisB\x10\n" +
	"\x0e_response_bodyB\x10\n" +
	"\x0e_error_messageB\x14\n" +
	"\x12_evaluated_payload*y\n" +
	"\x14WebhookTemplateError\x12a\n" +
	"&WEBHOOK_TEMPLATE_ERROR_INVALID_REQUEST\x10\x00\x1a5\xb2\xb2\x1a1\n" +
	"\x10INVALID_ARGUMENT\x12\x1dInvalidWebhookTemplateRequest2\xf7\x02\n" +
	"\x17WebhookTemplatesService\x12\xb6\x01\n" +
	"\x10ValidateTemplate\x124.nominal.webhooktemplates.v1.ValidateTemplateRequest\x1a5.nominal.webhooktemplates.v1.ValidateTemplateResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/webhook-templates/v1/template-validations\x12\xa2\x01\n" +
	"\vTestWebhook\x12/.nominal.webhooktemplates.v1.TestWebhookRequest\x1a0.nominal.webhooktemplates.v1.TestWebhookResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/webhook-templates/v1/test-deliveriesB\xa9\x02\n" +
	"\x1fcom.nominal.webhooktemplates.v1B\x15WebhookTemplatesProtoP\x01Zagithub.com/nominal-io/nominal-api-protos-go/nominal/protos/webhooktemplates/v1;webhooktemplatesv1\xa2\x02\x03NWX\xaa\x02\x1bNominal.Webhooktemplates.V1\xca\x02\x1bNominal\\Webhooktemplates\\V1\xe2\x02'Nominal\\Webhooktemplates\\V1\\GPBMetadata\xea\x02\x1dNominal::Webhooktemplates::V1b\x06proto3"

var (
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescOnce sync.Once
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescData []byte
)

func file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescGZIP() []byte {
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescOnce.Do(func() {
		file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDesc), len(file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDesc)))
	})
	return file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDescData
}

var file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_goTypes = []any{
	(WebhookTemplateError)(0),        // 0: nominal.webhooktemplates.v1.WebhookTemplateError
	(*ValidateTemplateRequest)(nil),  // 1: nominal.webhooktemplates.v1.ValidateTemplateRequest
	(*ValidationError)(nil),          // 2: nominal.webhooktemplates.v1.ValidationError
	(*ValidateTemplateResponse)(nil), // 3: nominal.webhooktemplates.v1.ValidateTemplateResponse
	(*TestWebhookRequest)(nil),       // 4: nominal.webhooktemplates.v1.TestWebhookRequest
	(*TestWebhookResponse)(nil),      // 5: nominal.webhooktemplates.v1.TestWebhookResponse
}
var file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_depIdxs = []int32{
	2, // 0: nominal.webhooktemplates.v1.ValidateTemplateResponse.errors:type_name -> nominal.webhooktemplates.v1.ValidationError
	1, // 1: nominal.webhooktemplates.v1.WebhookTemplatesService.ValidateTemplate:input_type -> nominal.webhooktemplates.v1.ValidateTemplateRequest
	4, // 2: nominal.webhooktemplates.v1.WebhookTemplatesService.TestWebhook:input_type -> nominal.webhooktemplates.v1.TestWebhookRequest
	3, // 3: nominal.webhooktemplates.v1.WebhookTemplatesService.ValidateTemplate:output_type -> nominal.webhooktemplates.v1.ValidateTemplateResponse
	5, // 4: nominal.webhooktemplates.v1.WebhookTemplatesService.TestWebhook:output_type -> nominal.webhooktemplates.v1.TestWebhookResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_init() }
func file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_init() {
	if File_nominal_protos_webhooktemplates_v1_webhook_templates_proto != nil {
		return
	}
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[2].OneofWrappers = []any{}
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[3].OneofWrappers = []any{}
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDesc), len(file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_goTypes,
		DependencyIndexes: file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_depIdxs,
		EnumInfos:         file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_enumTypes,
		MessageInfos:      file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_msgTypes,
	}.Build()
	File_nominal_protos_webhooktemplates_v1_webhook_templates_proto = out.File
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_goTypes = nil
	file_nominal_protos_webhooktemplates_v1_webhook_templates_proto_depIdxs = nil
}
