// WIRE-FROZEN — DOUBLY (conjure-grpc ADR, 2026-07-24): nominal-client consumes this package over native gRPC
// (CommentsServiceStub) since SDK v1.149.0, AND galaxy app code calls the generated twirp CommentsServiceClient.
// Because twirp routes embed `package.Service/Method`, the package (nominal.comments.v1), the service name
// (CommentsService), and every rpc method name are frozen too — no renames of any kind. Message names, field
// names/numbers/types, and enum values must not change either; evolution is additive-only. The EditCommentRequestWrapper
// message stays as a permanent-with-regret artifact until a v2 package is minted.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/comments/v1/comments.proto

package commentsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_VALUE_PREFIX
type ReactionType int32

const (
	ReactionType_REACTION_TYPE_UNSPECIFIED ReactionType = 0
	ReactionType_LIKE                      ReactionType = 1
	ReactionType_DISLIKE                   ReactionType = 2
	ReactionType_HEART                     ReactionType = 3
	ReactionType_HOORAY                    ReactionType = 4
	ReactionType_ROCKET                    ReactionType = 5
	ReactionType_EYES                      ReactionType = 6
)

// Enum value maps for ReactionType.
var (
	ReactionType_name = map[int32]string{
		0: "REACTION_TYPE_UNSPECIFIED",
		1: "LIKE",
		2: "DISLIKE",
		3: "HEART",
		4: "HOORAY",
		5: "ROCKET",
		6: "EYES",
	}
	ReactionType_value = map[string]int32{
		"REACTION_TYPE_UNSPECIFIED": 0,
		"LIKE":                      1,
		"DISLIKE":                   2,
		"HEART":                     3,
		"HOORAY":                    4,
		"ROCKET":                    5,
		"EYES":                      6,
	}
)

func (x ReactionType) Enum() *ReactionType {
	p := new(ReactionType)
	*p = x
	return p
}

func (x ReactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_comments_v1_comments_proto_enumTypes[0].Descriptor()
}

func (ReactionType) Type() protoreflect.EnumType {
	return &file_nominal_protos_comments_v1_comments_proto_enumTypes[0]
}

func (x ReactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReactionType.Descriptor instead.
func (ReactionType) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{0}
}

// buf:lint:ignore ENUM_VALUE_PREFIX
type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_RUN                       ResourceType = 1
	ResourceType_EVENT                     ResourceType = 2
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RUN",
		2: "EVENT",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"RUN":                       1,
		"EVENT":                     2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_comments_v1_comments_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_nominal_protos_comments_v1_comments_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{1}
}

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type CommentsError int32

const (
	CommentsError_COMMENTS_ERROR_COMMENT_NOT_FOUND          CommentsError = 0
	CommentsError_COMMENTS_ERROR_CONTENT_TOO_LONG           CommentsError = 1
	CommentsError_COMMENTS_ERROR_EMPTY_COMMENT_CONTENT      CommentsError = 2
	CommentsError_COMMENTS_ERROR_INVALID_ATTACHMENT         CommentsError = 3
	CommentsError_COMMENTS_ERROR_MAX_NESTING_DEPTH_EXCEEDED CommentsError = 4
	CommentsError_COMMENTS_ERROR_UNAUTHORIZED               CommentsError = 5
	CommentsError_COMMENTS_ERROR_INVALID_ARGUMENT           CommentsError = 6
)

// Enum value maps for CommentsError.
var (
	CommentsError_name = map[int32]string{
		0: "COMMENTS_ERROR_COMMENT_NOT_FOUND",
		1: "COMMENTS_ERROR_CONTENT_TOO_LONG",
		2: "COMMENTS_ERROR_EMPTY_COMMENT_CONTENT",
		3: "COMMENTS_ERROR_INVALID_ATTACHMENT",
		4: "COMMENTS_ERROR_MAX_NESTING_DEPTH_EXCEEDED",
		5: "COMMENTS_ERROR_UNAUTHORIZED",
		6: "COMMENTS_ERROR_INVALID_ARGUMENT",
	}
	CommentsError_value = map[string]int32{
		"COMMENTS_ERROR_COMMENT_NOT_FOUND":          0,
		"COMMENTS_ERROR_CONTENT_TOO_LONG":           1,
		"COMMENTS_ERROR_EMPTY_COMMENT_CONTENT":      2,
		"COMMENTS_ERROR_INVALID_ATTACHMENT":         3,
		"COMMENTS_ERROR_MAX_NESTING_DEPTH_EXCEEDED": 4,
		"COMMENTS_ERROR_UNAUTHORIZED":               5,
		"COMMENTS_ERROR_INVALID_ARGUMENT":           6,
	}
)

func (x CommentsError) Enum() *CommentsError {
	p := new(CommentsError)
	*p = x
	return p
}

func (x CommentsError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentsError) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_comments_v1_comments_proto_enumTypes[2].Descriptor()
}

func (CommentsError) Type() protoreflect.EnumType {
	return &file_nominal_protos_comments_v1_comments_proto_enumTypes[2]
}

func (x CommentsError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentsError.Descriptor instead.
func (CommentsError) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{2}
}

type Comment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique resource identifier for the comment
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	// The parent of the comment. It can be a resource or another comment.
	Parent *CommentParent `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// The user who authored the comment
	AuthorRid string `protobuf:"bytes,3,opt,name=author_rid,json=authorRid,proto3" json:"author_rid,omitempty"`
	// The time the comment was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The time the comment was edited. Empty if the comment has not been edited.
	EditedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=edited_at,json=editedAt,proto3,oneof" json:"edited_at,omitempty"`
	// The time the comment was deleted. Empty if the comment has not been deleted.
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// The markdown content of the comment.
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	// The user who pinned the comment. Empty if the comment is not pinned.
	PinnedBy *string `protobuf:"bytes,8,opt,name=pinned_by,json=pinnedBy,proto3,oneof" json:"pinned_by,omitempty"`
	// The time the comment was pinned. Empty if the comment is not pinned.
	PinnedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=pinned_at,json=pinnedAt,proto3,oneof" json:"pinned_at,omitempty"`
	// The reactions on the comment
	Reactions []*Reaction `protobuf:"bytes,10,rep,name=reactions,proto3" json:"reactions,omitempty"`
	// The comment's attachments
	Attachments   []string `protobuf:"bytes,11,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Comment) GetParent() *CommentParent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Comment) GetAuthorRid() string {
	if x != nil {
		return x.AuthorRid
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Comment) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetPinnedBy() string {
	if x != nil && x.PinnedBy != nil {
		return *x.PinnedBy
	}
	return ""
}

func (x *Comment) GetPinnedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PinnedAt
	}
	return nil
}

func (x *Comment) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *Comment) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// The parent of a comment. It can be a resource or another comment in the case of a reply.
type CommentParent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent of a comment. It can be a resource or another comment in the case of a reply.
	//
	// Types that are valid to be assigned to CommentParent:
	//
	//	*CommentParent_Resource
	//	*CommentParent_Comment
	CommentParent isCommentParent_CommentParent `protobuf_oneof:"comment_parent"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentParent) Reset() {
	*x = CommentParent{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentParent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentParent) ProtoMessage() {}

func (x *CommentParent) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentParent.ProtoReflect.Descriptor instead.
func (*CommentParent) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{1}
}

func (x *CommentParent) GetCommentParent() isCommentParent_CommentParent {
	if x != nil {
		return x.CommentParent
	}
	return nil
}

func (x *CommentParent) GetResource() *CommentParentResource {
	if x != nil {
		if x, ok := x.CommentParent.(*CommentParent_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *CommentParent) GetComment() *CommentParentComment {
	if x != nil {
		if x, ok := x.CommentParent.(*CommentParent_Comment); ok {
			return x.Comment
		}
	}
	return nil
}

type isCommentParent_CommentParent interface {
	isCommentParent_CommentParent()
}

type CommentParent_Resource struct {
	Resource *CommentParentResource `protobuf:"bytes,1,opt,name=resource,proto3,oneof"`
}

type CommentParent_Comment struct {
	Comment *CommentParentComment `protobuf:"bytes,2,opt,name=comment,proto3,oneof"`
}

func (*CommentParent_Resource) isCommentParent_CommentParent() {}

func (*CommentParent_Comment) isCommentParent_CommentParent() {}

type CommentParentComment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource identifier for the comment that the comment is replying to
	CommentRid    string `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentParentComment) Reset() {
	*x = CommentParentComment{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentParentComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentParentComment) ProtoMessage() {}

func (x *CommentParentComment) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentParentComment.ProtoReflect.Descriptor instead.
func (*CommentParentComment) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{2}
}

func (x *CommentParentComment) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

type CommentParentResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of resource that the comment is associated with
	ResourceType ResourceType `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=nominal.comments.v1.ResourceType" json:"resource_type,omitempty"`
	// The resource identifier for the resource that the comment is associated with. For example, a run or a workbook.
	ResourceRid   string `protobuf:"bytes,2,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentParentResource) Reset() {
	*x = CommentParentResource{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentParentResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentParentResource) ProtoMessage() {}

func (x *CommentParentResource) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentParentResource.ProtoReflect.Descriptor instead.
func (*CommentParentResource) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{3}
}

func (x *CommentParentResource) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *CommentParentResource) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

type Conversation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RID for the resource that the conversation is associated with.
	ResourceRid string `protobuf:"bytes,1,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	// The type of the resource that the conversation is associated with.
	ResourceType ResourceType `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=nominal.comments.v1.ResourceType" json:"resource_type,omitempty"`
	// The comments on the conversation ordered by creation time.
	// Empty if the comment has no replies.
	Comments      []*ConversationNode `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{4}
}

func (x *Conversation) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

func (x *Conversation) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *Conversation) GetComments() []*ConversationNode {
	if x != nil {
		return x.Comments
	}
	return nil
}

type ConversationNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The comment
	Comment *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	// The comments on (aka replies to) the comment ordered by creation time. Empty if the comment has no replies.
	Replies       []*ConversationNode `protobuf:"bytes,2,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationNode) Reset() {
	*x = ConversationNode{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationNode) ProtoMessage() {}

func (x *ConversationNode) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationNode.ProtoReflect.Descriptor instead.
func (*ConversationNode) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationNode) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *ConversationNode) GetReplies() []*ConversationNode {
	if x != nil {
		return x.Replies
	}
	return nil
}

type CreateCommentRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Parent *CommentParent         `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The content of the comment. Markdown supported.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Attachments to the comment.
	Attachments   []string `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCommentRequest) GetParent() *CommentParent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type EditCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content of the comment. Markdown supported.
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Attachments to the comment.
	Attachments   []string `protobuf:"bytes,2,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentRequest) Reset() {
	*x = EditCommentRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentRequest) ProtoMessage() {}

func (x *EditCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentRequest.ProtoReflect.Descriptor instead.
func (*EditCommentRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{7}
}

func (x *EditCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditCommentRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type Reaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique resource identifier for the reaction
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	// The user who authored the reaction
	UserRid string `protobuf:"bytes,2,opt,name=user_rid,json=userRid,proto3" json:"user_rid,omitempty"`
	// The time the reaction was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The type of reaction
	Type          ReactionType `protobuf:"varint,4,opt,name=type,proto3,enum=nominal.comments.v1.ReactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{8}
}

func (x *Reaction) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Reaction) GetUserRid() string {
	if x != nil {
		return x.UserRid
	}
	return ""
}

func (x *Reaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reaction) GetType() ReactionType {
	if x != nil {
		return x.Type
	}
	return ReactionType_REACTION_TYPE_UNSPECIFIED
}

type GetConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of resource that the comments are associated with
	ResourceType ResourceType `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=nominal.comments.v1.ResourceType" json:"resource_type,omitempty"`
	// The RID of resource that the comments are associated with
	ResourceRid   string `protobuf:"bytes,2,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{9}
}

func (x *GetConversationRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *GetConversationRequest) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

type GetConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{10}
}

func (x *GetConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type GetConversationCountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of resource that the comments are associated with
	ResourceType ResourceType `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=nominal.comments.v1.ResourceType" json:"resource_type,omitempty"`
	// The RID of resource that the comments are associated with
	ResourceRid string `protobuf:"bytes,2,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	// Whether to include deleted comments in the count
	IncludeDeleted *bool `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationCountRequest) Reset() {
	*x = GetConversationCountRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationCountRequest) ProtoMessage() {}

func (x *GetConversationCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationCountRequest.ProtoReflect.Descriptor instead.
func (*GetConversationCountRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{11}
}

func (x *GetConversationCountRequest) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *GetConversationCountRequest) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

func (x *GetConversationCountRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

type GetConversationCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationCountResponse) Reset() {
	*x = GetConversationCountResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationCountResponse) ProtoMessage() {}

func (x *GetConversationCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationCountResponse.ProtoReflect.Descriptor instead.
func (*GetConversationCountResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{12}
}

func (x *GetConversationCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RID of comment to fetch
	CommentRid    string `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{13}
}

func (x *GetCommentRequest) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

type GetCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentResponse) Reset() {
	*x = GetCommentResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentResponse) ProtoMessage() {}

func (x *GetCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentResponse.ProtoReflect.Descriptor instead.
func (*GetCommentResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type EditCommentRequestWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RID of comment to edit
	CommentRid    string              `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	Request       *EditCommentRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentRequestWrapper) Reset() {
	*x = EditCommentRequestWrapper{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentRequestWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentRequestWrapper) ProtoMessage() {}

func (x *EditCommentRequestWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentRequestWrapper.ProtoReflect.Descriptor instead.
func (*EditCommentRequestWrapper) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{16}
}

func (x *EditCommentRequestWrapper) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

func (x *EditCommentRequestWrapper) GetRequest() *EditCommentRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type EditCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentResponse) Reset() {
	*x = EditCommentResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentResponse) ProtoMessage() {}

func (x *EditCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentResponse.ProtoReflect.Descriptor instead.
func (*EditCommentResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{17}
}

func (x *EditCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type DeleteCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RID of comment to delete
	CommentRid    string `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteCommentRequest) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type PinCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RID of comment to pin
	CommentRid    string `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinCommentRequest) Reset() {
	*x = PinCommentRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinCommentRequest) ProtoMessage() {}

func (x *PinCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinCommentRequest.ProtoReflect.Descriptor instead.
func (*PinCommentRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{20}
}

func (x *PinCommentRequest) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

type PinCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinCommentResponse) Reset() {
	*x = PinCommentResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinCommentResponse) ProtoMessage() {}

func (x *PinCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinCommentResponse.ProtoReflect.Descriptor instead.
func (*PinCommentResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{21}
}

func (x *PinCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type UnpinCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RID of comment to unpin
	CommentRid    string `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinCommentRequest) Reset() {
	*x = UnpinCommentRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinCommentRequest) ProtoMessage() {}

func (x *UnpinCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinCommentRequest.ProtoReflect.Descriptor instead.
func (*UnpinCommentRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{22}
}

func (x *UnpinCommentRequest) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

type UnpinCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinCommentResponse) Reset() {
	*x = UnpinCommentResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinCommentResponse) ProtoMessage() {}

func (x *UnpinCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinCommentResponse.ProtoReflect.Descriptor instead.
func (*UnpinCommentResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{23}
}

func (x *UnpinCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type AddReactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RID of comment to delete
	CommentRid string `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	// The type of reaction
	Type          ReactionType `protobuf:"varint,2,opt,name=type,proto3,enum=nominal.comments.v1.ReactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReactionRequest) Reset() {
	*x = AddReactionRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReactionRequest) ProtoMessage() {}

func (x *AddReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReactionRequest.ProtoReflect.Descriptor instead.
func (*AddReactionRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{24}
}

func (x *AddReactionRequest) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

func (x *AddReactionRequest) GetType() ReactionType {
	if x != nil {
		return x.Type
	}
	return ReactionType_REACTION_TYPE_UNSPECIFIED
}

type AddReactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReactionResponse) Reset() {
	*x = AddReactionResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReactionResponse) ProtoMessage() {}

func (x *AddReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReactionResponse.ProtoReflect.Descriptor instead.
func (*AddReactionResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{25}
}

func (x *AddReactionResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type RemoveReactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RID of comment to delete
	CommentRid string `protobuf:"bytes,1,opt,name=comment_rid,json=commentRid,proto3" json:"comment_rid,omitempty"`
	// The type of reaction
	Type          ReactionType `protobuf:"varint,2,opt,name=type,proto3,enum=nominal.comments.v1.ReactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReactionRequest) Reset() {
	*x = RemoveReactionRequest{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReactionRequest) ProtoMessage() {}

func (x *RemoveReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReactionRequest.ProtoReflect.Descriptor instead.
func (*RemoveReactionRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveReactionRequest) GetCommentRid() string {
	if x != nil {
		return x.CommentRid
	}
	return ""
}

func (x *RemoveReactionRequest) GetType() ReactionType {
	if x != nil {
		return x.Type
	}
	return ReactionType_REACTION_TYPE_UNSPECIFIED
}

type RemoveReactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReactionResponse) Reset() {
	*x = RemoveReactionResponse{}
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReactionResponse) ProtoMessage() {}

func (x *RemoveReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_comments_v1_comments_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReactionResponse.ProtoReflect.Descriptor instead.
func (*RemoveReactionResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_comments_v1_comments_proto_rawDescGZIP(), []int{27}
}

func (x *RemoveReactionResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

var File_nominal_protos_comments_v1_comments_proto protoreflect.FileDescriptor

const file_nominal_protos_comments_v1_comments_proto_rawDesc = "" +
	"\n" +
	")nominal/protos/comments/v1/comments.proto\x12\x13nominal.comments.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!nominal/protos/gen/v1/alias.proto\x1a!nominal/protos/gen/v1/error.proto\"\xe8\x05\n" +
	"\aComment\x12:\n" +
	"\x03rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\x03rid\x12:\n" +
	"\x06parent\x18\x02 \x01(\v2\".nominal.comments.v1.CommentParentR\x06parent\x12G\n" +
	"\n" +
	"author_rid\x18\x03 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\tauthorRid\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\tedited_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\beditedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12J\n" +
	"\tpinned_by\x18\b \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierH\x02R\bpinnedBy\x88\x01\x01\x12<\n" +
	"\tpinned_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x03R\bpinnedAt\x88\x01\x01\x12;\n" +
	"\treactions\x18\n" +
	" \x03(\v2\x1d.nominal.comments.v1.ReactionR\treactions\x12I\n" +
	"\vattachments\x18\v \x03(\tB'\x9a\xb2\x1a#\n" +
	"!io.nominal.api.rids.AttachmentRidR\vattachmentsB\f\n" +
	"\n" +
	"_edited_atB\r\n" +
	"\v_deleted_atB\f\n" +
	"\n" +
	"_pinned_byB\f\n" +
	"\n" +
	"_pinned_at\"\xb9\x01\n" +
	"\rCommentParent\x12H\n" +
	"\bresource\x18\x01 \x01(\v2*.nominal.comments.v1.CommentParentResourceH\x00R\bresource\x12E\n" +
	"\acomment\x18\x02 \x01(\v2).nominal.comments.v1.CommentParentCommentH\x00R\acommentB\x17\n" +
	"\x0ecomment_parent\x12\x05\xbaH\x02\b\x01\"a\n" +
	"\x14CommentParentComment\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\"\xac\x01\n" +
	"\x15CommentParentResource\x12F\n" +
	"\rresource_type\x18\x01 \x01(\x0e2!.nominal.comments.v1.ResourceTypeR\fresourceType\x12K\n" +
	"\fresource_rid\x18\x02 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\vresourceRid\"\xe6\x01\n" +
	"\fConversation\x12K\n" +
	"\fresource_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\vresourceRid\x12F\n" +
	"\rresource_type\x18\x02 \x01(\x0e2!.nominal.comments.v1.ResourceTypeR\fresourceType\x12A\n" +
	"\bcomments\x18\x03 \x03(\v2%.nominal.comments.v1.ConversationNodeR\bcomments\"\x8b\x01\n" +
	"\x10ConversationNode\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\x12?\n" +
	"\areplies\x18\x02 \x03(\v2%.nominal.comments.v1.ConversationNodeR\areplies\"\xb7\x01\n" +
	"\x14CreateCommentRequest\x12:\n" +
	"\x06parent\x18\x01 \x01(\v2\".nominal.comments.v1.CommentParentR\x06parent\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12I\n" +
	"\vattachments\x18\x03 \x03(\tB'\x9a\xb2\x1a#\n" +
	"!io.nominal.api.rids.AttachmentRidR\vattachments\"y\n" +
	"\x12EditCommentRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12I\n" +
	"\vattachments\x18\x02 \x03(\tB'\x9a\xb2\x1a#\n" +
	"!io.nominal.api.rids.AttachmentRidR\vattachments\"\xfe\x01\n" +
	"\bReaction\x12;\n" +
	"\x03rid\x18\x01 \x01(\tB)\x9a\xb2\x1a%\n" +
	"#io.nominal.comments.api.ReactionRidR\x03rid\x12C\n" +
	"\buser_rid\x18\x02 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\auserRid\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\x04type\x18\x04 \x01(\x0e2!.nominal.comments.v1.ReactionTypeR\x04type\"\xad\x01\n" +
	"\x16GetConversationRequest\x12F\n" +
	"\rresource_type\x18\x01 \x01(\x0e2!.nominal.comments.v1.ResourceTypeR\fresourceType\x12K\n" +
	"\fresource_rid\x18\x02 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\vresourceRid\"`\n" +
	"\x17GetConversationResponse\x12E\n" +
	"\fconversation\x18\x01 \x01(\v2!.nominal.comments.v1.ConversationR\fconversation\"\xf4\x01\n" +
	"\x1bGetConversationCountRequest\x12F\n" +
	"\rresource_type\x18\x01 \x01(\x0e2!.nominal.comments.v1.ResourceTypeR\fresourceType\x12K\n" +
	"\fresource_rid\x18\x02 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\vresourceRid\x12,\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bH\x00R\x0eincludeDeleted\x88\x01\x01B\x12\n" +
	"\x10_include_deleted\"4\n" +
	"\x1cGetConversationCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"^\n" +
	"\x11GetCommentRequest\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\"L\n" +
	"\x12GetCommentResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\"O\n" +
	"\x15CreateCommentResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\"\xa9\x01\n" +
	"\x19EditCommentRequestWrapper\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\x12A\n" +
	"\arequest\x18\x02 \x01(\v2'.nominal.comments.v1.EditCommentRequestR\arequest\"M\n" +
	"\x13EditCommentResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\"a\n" +
	"\x14DeleteCommentRequest\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\"O\n" +
	"\x15DeleteCommentResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\"^\n" +
	"\x11PinCommentRequest\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\"L\n" +
	"\x12PinCommentResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\"`\n" +
	"\x13UnpinCommentRequest\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\"N\n" +
	"\x14UnpinCommentResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\"\x96\x01\n" +
	"\x12AddReactionRequest\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.nominal.comments.v1.ReactionTypeR\x04type\"M\n" +
	"\x13AddReactionResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment\"\x99\x01\n" +
	"\x15RemoveReactionRequest\x12I\n" +
	"\vcomment_rid\x18\x01 \x01(\tB(\x9a\xb2\x1a$\n" +
	"\"io.nominal.comments.api.CommentRidR\n" +
	"commentRid\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.nominal.comments.v1.ReactionTypeR\x04type\"P\n" +
	"\x16RemoveReactionResponse\x126\n" +
	"\acomment\x18\x01 \x01(\v2\x1c.nominal.comments.v1.CommentR\acomment*q\n" +
	"\fReactionType\x12\x1d\n" +
	"\x19REACTION_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04LIKE\x10\x01\x12\v\n" +
	"\aDISLIKE\x10\x02\x12\t\n" +
	"\x05HEART\x10\x03\x12\n" +
	"\n" +
	"\x06HOORAY\x10\x04\x12\n" +
	"\n" +
	"\x06ROCKET\x10\x05\x12\b\n" +
	"\x04EYES\x10\x06*A\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RUN\x10\x01\x12\t\n" +
	"\x05EVENT\x10\x02*\xc3\x04\n" +
	"\rCommentsError\x12F\n" +
	" COMMENTS_ERROR_COMMENT_NOT_FOUND\x10\x00\x1a \xb2\xb2\x1a\x1c\n" +
	"\tNOT_FOUND\x12\x0fCommentNotFound\x12K\n" +
	"\x1fCOMMENTS_ERROR_CONTENT_TOO_LONG\x10\x01\x1a&\xb2\xb2\x1a\"\n" +
	"\x10INVALID_ARGUMENT\x12\x0eContentTooLong\x12U\n" +
	"$COMMENTS_ERROR_EMPTY_COMMENT_CONTENT\x10\x02\x1a+\xb2\xb2\x1a'\n" +
	"\x10INVALID_ARGUMENT\x12\x13EmptyCommentContent\x12P\n" +
	"!COMMENTS_ERROR_INVALID_ATTACHMENT\x10\x03\x1a)\xb2\xb2\x1a%\n" +
	"\x10INVALID_ARGUMENT\x12\x11InvalidAttachment\x12^\n" +
	")COMMENTS_ERROR_MAX_NESTING_DEPTH_EXCEEDED\x10\x04\x1a/\xb2\xb2\x1a+\n" +
	"\x10INVALID_ARGUMENT\x12\x17MaxNestingDepthExceeded\x12F\n" +
	"\x1bCOMMENTS_ERROR_UNAUTHORIZED\x10\x05\x1a%\xb2\xb2\x1a!\n" +
	"\x11PERMISSION_DENIED\x12\fUnauthorized\x12L\n" +
	"\x1fCOMMENTS_ERROR_INVALID_ARGUMENT\x10\x06\x1a'\xb2\xb2\x1a#\n" +
	"\x10INVALID_ARGUMENT\x12\x0fInvalidArgument2\xcd\f\n" +
	"\x0fCommentsService\x12\xaf\x01\n" +
	"\x0fGetConversation\x12+.nominal.comments.v1.GetConversationRequest\x1a,.nominal.comments.v1.GetConversationResponse\"A\x82\xd3\xe4\x93\x02;\x129/comments/v2/conversations/{resource_type}/{resource_rid}\x12\xc4\x01\n" +
	"\x14GetConversationCount\x120.nominal.comments.v1.GetConversationCountRequest\x1a1.nominal.comments.v1.GetConversationCountResponse\"G\x82\xd3\xe4\x93\x02A\x12?/comments/v2/conversations/{resource_type}/{resource_rid}/count\x12\x8a\x01\n" +
	"\n" +
	"GetComment\x12&.nominal.comments.v1.GetCommentRequest\x1a'.nominal.comments.v1.GetCommentResponse\"+\x82\xd3\xe4\x93\x02%\x12#/comments/v2/comments/{comment_rid}\x12\x88\x01\n" +
	"\rCreateComment\x12).nominal.comments.v1.CreateCommentRequest\x1a*.nominal.comments.v1.CreateCommentResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/comments/v2/comments\x12\x9d\x01\n" +
	"\vEditComment\x12..nominal.comments.v1.EditCommentRequestWrapper\x1a(.nominal.comments.v1.EditCommentResponse\"4\x82\xd3\xe4\x93\x02.:\arequest\x1a#/comments/v2/comments/{comment_rid}\x12\x93\x01\n" +
	"\rDeleteComment\x12).nominal.comments.v1.DeleteCommentRequest\x1a*.nominal.comments.v1.DeleteCommentResponse\"+\x82\xd3\xe4\x93\x02%*#/comments/v2/comments/{comment_rid}\x12\x8e\x01\n" +
	"\n" +
	"PinComment\x12&.nominal.comments.v1.PinCommentRequest\x1a'.nominal.comments.v1.PinCommentResponse\"/\x82\xd3\xe4\x93\x02)\"'/comments/v2/comments/{comment_rid}/pin\x12\x96\x01\n" +
	"\fUnpinComment\x12(.nominal.comments.v1.UnpinCommentRequest\x1a).nominal.comments.v1.UnpinCommentResponse\"1\x82\xd3\xe4\x93\x02+\")/comments/v2/comments/{comment_rid}/unpin\x12\x9e\x01\n" +
	"\vAddReaction\x12'.nominal.comments.v1.AddReactionRequest\x1a(.nominal.comments.v1.AddReactionResponse\"<\x82\xd3\xe4\x93\x026\"4/comments/v2/comments/{comment_rid}/reactions/{type}\x12\xa7\x01\n" +
	"\x0eRemoveReaction\x12*.nominal.comments.v1.RemoveReactionRequest\x1a+.nominal.comments.v1.RemoveReactionResponse\"<\x82\xd3\xe4\x93\x026*4/comments/v2/comments/{comment_rid}/reactions/{type}B\xe9\x01\n" +
	"\x17com.nominal.comments.v1B\rCommentsProtoP\x01ZQgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/comments/v1;commentsv1\xa2\x02\x03NCX\xaa\x02\x13Nominal.Comments.V1\xca\x02\x13Nominal\\Comments\\V1\xe2\x02\x1fNominal\\Comments\\V1\\GPBMetadata\xea\x02\x15Nominal::Comments::V1b\x06proto3"

var (
	file_nominal_protos_comments_v1_comments_proto_rawDescOnce sync.Once
	file_nominal_protos_comments_v1_comments_proto_rawDescData []byte
)

func file_nominal_protos_comments_v1_comments_proto_rawDescGZIP() []byte {
	file_nominal_protos_comments_v1_comments_proto_rawDescOnce.Do(func() {
		file_nominal_protos_comments_v1_comments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_comments_v1_comments_proto_rawDesc), len(file_nominal_protos_comments_v1_comments_proto_rawDesc)))
	})
	return file_nominal_protos_comments_v1_comments_proto_rawDescData
}

var file_nominal_protos_comments_v1_comments_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nominal_protos_comments_v1_comments_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_nominal_protos_comments_v1_comments_proto_goTypes = []any{
	(ReactionType)(0),                    // 0: nominal.comments.v1.ReactionType
	(ResourceType)(0),                    // 1: nominal.comments.v1.ResourceType
	(CommentsError)(0),                   // 2: nominal.comments.v1.CommentsError
	(*Comment)(nil),                      // 3: nominal.comments.v1.Comment
	(*CommentParent)(nil),                // 4: nominal.comments.v1.CommentParent
	(*CommentParentComment)(nil),         // 5: nominal.comments.v1.CommentParentComment
	(*CommentParentResource)(nil),        // 6: nominal.comments.v1.CommentParentResource
	(*Conversation)(nil),                 // 7: nominal.comments.v1.Conversation
	(*ConversationNode)(nil),             // 8: nominal.comments.v1.ConversationNode
	(*CreateCommentRequest)(nil),         // 9: nominal.comments.v1.CreateCommentRequest
	(*EditCommentRequest)(nil),           // 10: nominal.comments.v1.EditCommentRequest
	(*Reaction)(nil),                     // 11: nominal.comments.v1.Reaction
	(*GetConversationRequest)(nil),       // 12: nominal.comments.v1.GetConversationRequest
	(*GetConversationResponse)(nil),      // 13: nominal.comments.v1.GetConversationResponse
	(*GetConversationCountRequest)(nil),  // 14: nominal.comments.v1.GetConversationCountRequest
	(*GetConversationCountResponse)(nil), // 15: nominal.comments.v1.GetConversationCountResponse
	(*GetCommentRequest)(nil),            // 16: nominal.comments.v1.GetCommentRequest
	(*GetCommentResponse)(nil),           // 17: nominal.comments.v1.GetCommentResponse
	(*CreateCommentResponse)(nil),        // 18: nominal.comments.v1.CreateCommentResponse
	(*EditCommentRequestWrapper)(nil),    // 19: nominal.comments.v1.EditCommentRequestWrapper
	(*EditCommentResponse)(nil),          // 20: nominal.comments.v1.EditCommentResponse
	(*DeleteCommentRequest)(nil),         // 21: nominal.comments.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),        // 22: nominal.comments.v1.DeleteCommentResponse
	(*PinCommentRequest)(nil),            // 23: nominal.comments.v1.PinCommentRequest
	(*PinCommentResponse)(nil),           // 24: nominal.comments.v1.PinCommentResponse
	(*UnpinCommentRequest)(nil),          // 25: nominal.comments.v1.UnpinCommentRequest
	(*UnpinCommentResponse)(nil),         // 26: nominal.comments.v1.UnpinCommentResponse
	(*AddReactionRequest)(nil),           // 27: nominal.comments.v1.AddReactionRequest
	(*AddReactionResponse)(nil),          // 28: nominal.comments.v1.AddReactionResponse
	(*RemoveReactionRequest)(nil),        // 29: nominal.comments.v1.RemoveReactionRequest
	(*RemoveReactionResponse)(nil),       // 30: nominal.comments.v1.RemoveReactionResponse
	(*timestamppb.Timestamp)(nil),        // 31: google.protobuf.Timestamp
}
var file_nominal_protos_comments_v1_comments_proto_depIdxs = []int32{
	4,  // 0: nominal.comments.v1.Comment.parent:type_name -> nominal.comments.v1.CommentParent
	31, // 1: nominal.comments.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	31, // 2: nominal.comments.v1.Comment.edited_at:type_name -> google.protobuf.Timestamp
	31, // 3: nominal.comments.v1.Comment.deleted_at:type_name -> google.protobuf.Timestamp
	31, // 4: nominal.comments.v1.Comment.pinned_at:type_name -> google.protobuf.Timestamp
	11, // 5: nominal.comments.v1.Comment.reactions:type_name -> nominal.comments.v1.Reaction
	6,  // 6: nominal.comments.v1.CommentParent.resource:type_name -> nominal.comments.v1.CommentParentResource
	5,  // 7: nominal.comments.v1.CommentParent.comment:type_name -> nominal.comments.v1.CommentParentComment
	1,  // 8: nominal.comments.v1.CommentParentResource.resource_type:type_name -> nominal.comments.v1.ResourceType
	1,  // 9: nominal.comments.v1.Conversation.resource_type:type_name -> nominal.comments.v1.ResourceType
	8,  // 10: nominal.comments.v1.Conversation.comments:type_name -> nominal.comments.v1.ConversationNode
	3,  // 11: nominal.comments.v1.ConversationNode.comment:type_name -> nominal.comments.v1.Comment
	8,  // 12: nominal.comments.v1.ConversationNode.replies:type_name -> nominal.comments.v1.ConversationNode
	4,  // 13: nominal.comments.v1.CreateCommentRequest.parent:type_name -> nominal.comments.v1.CommentParent
	31, // 14: nominal.comments.v1.Reaction.created_at:type_name -> google.protobuf.Timestamp
	0,  // 15: nominal.comments.v1.Reaction.type:type_name -> nominal.comments.v1.ReactionType
	1,  // 16: nominal.comments.v1.GetConversationRequest.resource_type:type_name -> nominal.comments.v1.ResourceType
	7,  // 17: nominal.comments.v1.GetConversationResponse.conversation:type_name -> nominal.comments.v1.Conversation
	1,  // 18: nominal.comments.v1.GetConversationCountRequest.resource_type:type_name -> nominal.comments.v1.ResourceType
	3,  // 19: nominal.comments.v1.GetCommentResponse.comment:type_name -> nominal.comments.v1.Comment
	3,  // 20: nominal.comments.v1.CreateCommentResponse.comment:type_name -> nominal.comments.v1.Comment
	10, // 21: nominal.comments.v1.EditCommentRequestWrapper.request:type_name -> nominal.comments.v1.EditCommentRequest
	3,  // 22: nominal.comments.v1.EditCommentResponse.comment:type_name -> nominal.comments.v1.Comment
	3,  // 23: nominal.comments.v1.DeleteCommentResponse.comment:type_name -> nominal.comments.v1.Comment
	3,  // 24: nominal.comments.v1.PinCommentResponse.comment:type_name -> nominal.comments.v1.Comment
	3,  // 25: nominal.comments.v1.UnpinCommentResponse.comment:type_name -> nominal.comments.v1.Comment
	0,  // 26: nominal.comments.v1.AddReactionRequest.type:type_name -> nominal.comments.v1.ReactionType
	3,  // 27: nominal.comments.v1.AddReactionResponse.comment:type_name -> nominal.comments.v1.Comment
	0,  // 28: nominal.comments.v1.RemoveReactionRequest.type:type_name -> nominal.comments.v1.ReactionType
	3,  // 29: nominal.comments.v1.RemoveReactionResponse.comment:type_name -> nominal.comments.v1.Comment
	12, // 30: nominal.comments.v1.CommentsService.GetConversation:input_type -> nominal.comments.v1.GetConversationRequest
	14, // 31: nominal.comments.v1.CommentsService.GetConversationCount:input_type -> nominal.comments.v1.GetConversationCountRequest
	16, // 32: nominal.comments.v1.CommentsService.GetComment:input_type -> nominal.comments.v1.GetCommentRequest
	9,  // 33: nominal.comments.v1.CommentsService.CreateComment:input_type -> nominal.comments.v1.CreateCommentRequest
	19, // 34: nominal.comments.v1.CommentsService.EditComment:input_type -> nominal.comments.v1.EditCommentRequestWrapper
	21, // 35: nominal.comments.v1.CommentsService.DeleteComment:input_type -> nominal.comments.v1.DeleteCommentRequest
	23, // 36: nominal.comments.v1.CommentsService.PinComment:input_type -> nominal.comments.v1.PinCommentRequest
	25, // 37: nominal.comments.v1.CommentsService.UnpinComment:input_type -> nominal.comments.v1.UnpinCommentRequest
	27, // 38: nominal.comments.v1.CommentsService.AddReaction:input_type -> nominal.comments.v1.AddReactionRequest
	29, // 39: nominal.comments.v1.CommentsService.RemoveReaction:input_type -> nominal.comments.v1.RemoveReactionRequest
	13, // 40: nominal.comments.v1.CommentsService.GetConversation:output_type -> nominal.comments.v1.GetConversationResponse
	15, // 41: nominal.comments.v1.CommentsService.GetConversationCount:output_type -> nominal.comments.v1.GetConversationCountResponse
	17, // 42: nominal.comments.v1.CommentsService.GetComment:output_type -> nominal.comments.v1.GetCommentResponse
	18, // 43: nominal.comments.v1.CommentsService.CreateComment:output_type -> nominal.comments.v1.CreateCommentResponse
	20, // 44: nominal.comments.v1.CommentsService.EditComment:output_type -> nominal.comments.v1.EditCommentResponse
	22, // 45: nominal.comments.v1.CommentsService.DeleteComment:output_type -> nominal.comments.v1.DeleteCommentResponse
	24, // 46: nominal.comments.v1.CommentsService.PinComment:output_type -> nominal.comments.v1.PinCommentResponse
	26, // 47: nominal.comments.v1.CommentsService.UnpinComment:output_type -> nominal.comments.v1.UnpinCommentResponse
	28, // 48: nominal.comments.v1.CommentsService.AddReaction:output_type -> nominal.comments.v1.AddReactionResponse
	30, // 49: nominal.comments.v1.CommentsService.RemoveReaction:output_type -> nominal.comments.v1.RemoveReactionResponse
	40, // [40:50] is the sub-list for method output_type
	30, // [30:40] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_nominal_protos_comments_v1_comments_proto_init() }
func file_nominal_protos_comments_v1_comments_proto_init() {
	if File_nominal_protos_comments_v1_comments_proto != nil {
		return
	}
	file_nominal_protos_comments_v1_comments_proto_msgTypes[0].OneofWrappers = []any{}
	file_nominal_protos_comments_v1_comments_proto_msgTypes[1].OneofWrappers = []any{
		(*CommentParent_Resource)(nil),
		(*CommentParent_Comment)(nil),
	}
	file_nominal_protos_comments_v1_comments_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_comments_v1_comments_proto_rawDesc), len(file_nominal_protos_comments_v1_comments_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_comments_v1_comments_proto_goTypes,
		DependencyIndexes: file_nominal_protos_comments_v1_comments_proto_depIdxs,
		EnumInfos:         file_nominal_protos_comments_v1_comments_proto_enumTypes,
		MessageInfos:      file_nominal_protos_comments_v1_comments_proto_msgTypes,
	}.Build()
	File_nominal_protos_comments_v1_comments_proto = out.File
	file_nominal_protos_comments_v1_comments_proto_goTypes = nil
	file_nominal_protos_comments_v1_comments_proto_depIdxs = nil
}
