// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/internal/servicemetadata/v1/servicemetadata.proto

package servicemetadatav1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceMetadataRequest) Reset() {
	*x = GetServiceMetadataRequest{}
	mi := &file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceMetadataRequest) ProtoMessage() {}

func (x *GetServiceMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetServiceMetadataRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescGZIP(), []int{0}
}

type GetServiceMetadataResponse struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	Version                            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MinSupportedSchemaVersionInclusive int32                  `protobuf:"varint,2,opt,name=min_supported_schema_version_inclusive,json=minSupportedSchemaVersionInclusive,proto3" json:"min_supported_schema_version_inclusive,omitempty"`
	MaxSupportedSchemaVersionInclusive int32                  `protobuf:"varint,3,opt,name=max_supported_schema_version_inclusive,json=maxSupportedSchemaVersionInclusive,proto3" json:"max_supported_schema_version_inclusive,omitempty"`
	CurrentSchemaVersion               int32                  `protobuf:"varint,4,opt,name=current_schema_version,json=currentSchemaVersion,proto3" json:"current_schema_version,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *GetServiceMetadataResponse) Reset() {
	*x = GetServiceMetadataResponse{}
	mi := &file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceMetadataResponse) ProtoMessage() {}

func (x *GetServiceMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetServiceMetadataResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceMetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServiceMetadataResponse) GetMinSupportedSchemaVersionInclusive() int32 {
	if x != nil {
		return x.MinSupportedSchemaVersionInclusive
	}
	return 0
}

func (x *GetServiceMetadataResponse) GetMaxSupportedSchemaVersionInclusive() int32 {
	if x != nil {
		return x.MaxSupportedSchemaVersionInclusive
	}
	return 0
}

func (x *GetServiceMetadataResponse) GetCurrentSchemaVersion() int32 {
	if x != nil {
		return x.CurrentSchemaVersion
	}
	return 0
}

var File_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto protoreflect.FileDescriptor

const file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDesc = "" +
	"\n" +
	"@nominal/protos/internal/servicemetadata/v1/servicemetadata.proto\x12#nominal.internal.servicemetadata.v1\x1a\x1cgoogle/api/annotations.proto\"\x1b\n" +
	"\x19GetServiceMetadataRequest\"\x94\x02\n" +
	"\x1aGetServiceMetadataResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12R\n" +
	"&min_supported_schema_version_inclusive\x18\x02 \x01(\x05R\"minSupportedSchemaVersionInclusive\x12R\n" +
	"&max_supported_schema_version_inclusive\x18\x03 \x01(\x05R\"maxSupportedSchemaVersionInclusive\x124\n" +
	"\x16current_schema_version\x18\x04 \x01(\x05R\x14currentSchemaVersion2\xd6\x01\n" +
	"\x16ServiceMetadataService\x12\xbb\x01\n" +
	"\x12GetServiceMetadata\x12>.nominal.internal.servicemetadata.v1.GetServiceMetadataRequest\x1a?.nominal.internal.servicemetadata.v1.GetServiceMetadataResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/internal/servicemetadata/v1B\xd8\x02\n" +
	"'com.nominal.internal.servicemetadata.v1B\x14ServicemetadataProtoP\x01Zhgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/internal/servicemetadata/v1;servicemetadatav1\xa2\x02\x03NIS\xaa\x02#Nominal.Internal.Servicemetadata.V1\xca\x02#Nominal\\Internal\\Servicemetadata\\V1\xe2\x02/Nominal\\Internal\\Servicemetadata\\V1\\GPBMetadata\xea\x02&Nominal::Internal::Servicemetadata::V1b\x06proto3"

var (
	file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescOnce sync.Once
	file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescData []byte
)

func file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescGZIP() []byte {
	file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescOnce.Do(func() {
		file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDesc), len(file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDesc)))
	})
	return file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDescData
}

var file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_goTypes = []any{
	(*GetServiceMetadataRequest)(nil),  // 0: nominal.internal.servicemetadata.v1.GetServiceMetadataRequest
	(*GetServiceMetadataResponse)(nil), // 1: nominal.internal.servicemetadata.v1.GetServiceMetadataResponse
}
var file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_depIdxs = []int32{
	0, // 0: nominal.internal.servicemetadata.v1.ServiceMetadataService.GetServiceMetadata:input_type -> nominal.internal.servicemetadata.v1.GetServiceMetadataRequest
	1, // 1: nominal.internal.servicemetadata.v1.ServiceMetadataService.GetServiceMetadata:output_type -> nominal.internal.servicemetadata.v1.GetServiceMetadataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_init() }
func file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_init() {
	if File_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDesc), len(file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_goTypes,
		DependencyIndexes: file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_depIdxs,
		MessageInfos:      file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_msgTypes,
	}.Build()
	File_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto = out.File
	file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_goTypes = nil
	file_nominal_protos_internal_servicemetadata_v1_servicemetadata_proto_depIdxs = nil
}
