// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/mesh/v1/internal/internal_mesh.proto

package internal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalMeshService_UpdateRemoteConnectionStatus_FullMethodName = "/nominal.mesh.v1.internal.InternalMeshService/UpdateRemoteConnectionStatus"
)

// InternalMeshServiceClient is the client API for InternalMeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal service for inter-service RPCs. Uses a separate package so that
// the gRPC path (nominal.mesh.v1.internal.*) is excluded from public ingress.
type InternalMeshServiceClient interface {
	// Updates the health status of a remote connection. Internal-only (service-token auth).
	UpdateRemoteConnectionStatus(ctx context.Context, in *UpdateRemoteConnectionStatusRequest, opts ...grpc.CallOption) (*UpdateRemoteConnectionStatusResponse, error)
}

type internalMeshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalMeshServiceClient(cc grpc.ClientConnInterface) InternalMeshServiceClient {
	return &internalMeshServiceClient{cc}
}

func (c *internalMeshServiceClient) UpdateRemoteConnectionStatus(ctx context.Context, in *UpdateRemoteConnectionStatusRequest, opts ...grpc.CallOption) (*UpdateRemoteConnectionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRemoteConnectionStatusResponse)
	err := c.cc.Invoke(ctx, InternalMeshService_UpdateRemoteConnectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalMeshServiceServer is the server API for InternalMeshService service.
// All implementations must embed UnimplementedInternalMeshServiceServer
// for forward compatibility.
//
// Internal service for inter-service RPCs. Uses a separate package so that
// the gRPC path (nominal.mesh.v1.internal.*) is excluded from public ingress.
type InternalMeshServiceServer interface {
	// Updates the health status of a remote connection. Internal-only (service-token auth).
	UpdateRemoteConnectionStatus(context.Context, *UpdateRemoteConnectionStatusRequest) (*UpdateRemoteConnectionStatusResponse, error)
	mustEmbedUnimplementedInternalMeshServiceServer()
}

// UnimplementedInternalMeshServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalMeshServiceServer struct{}

func (UnimplementedInternalMeshServiceServer) UpdateRemoteConnectionStatus(context.Context, *UpdateRemoteConnectionStatusRequest) (*UpdateRemoteConnectionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRemoteConnectionStatus not implemented")
}
func (UnimplementedInternalMeshServiceServer) mustEmbedUnimplementedInternalMeshServiceServer() {}
func (UnimplementedInternalMeshServiceServer) testEmbeddedByValue()                             {}

// UnsafeInternalMeshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalMeshServiceServer will
// result in compilation errors.
type UnsafeInternalMeshServiceServer interface {
	mustEmbedUnimplementedInternalMeshServiceServer()
}

func RegisterInternalMeshServiceServer(s grpc.ServiceRegistrar, srv InternalMeshServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalMeshServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalMeshService_ServiceDesc, srv)
}

func _InternalMeshService_UpdateRemoteConnectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemoteConnectionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMeshServiceServer).UpdateRemoteConnectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMeshService_UpdateRemoteConnectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMeshServiceServer).UpdateRemoteConnectionStatus(ctx, req.(*UpdateRemoteConnectionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalMeshService_ServiceDesc is the grpc.ServiceDesc for InternalMeshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalMeshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.mesh.v1.internal.InternalMeshService",
	HandlerType: (*InternalMeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateRemoteConnectionStatus",
			Handler:    _InternalMeshService_UpdateRemoteConnectionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/mesh/v1/internal/internal_mesh.proto",
}
