// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/iceberg/v1/wal.proto

package icebergv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One Parquet file just uploaded to object storage by the streaming Iceberg
// writer. The downstream committer reads these from a Kafka "WAL" topic,
// groups them per Iceberg TableIdentifier, and registers them with Iceberg in
// a single AppendFiles per (table, batch) snapshot.
//
// The writer encodes the full table target (namespace + table name) AND the
// resolved partition value the file belongs in.
//
// The Kafka record key is DatasetRid so all files for one dataset land on the same partition.
// The producer is the authority on table location — the consumer never re-derives namespaces.
type IcebergFileWrittenEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full Iceberg table location (namespace + table name).
	Table *TableTarget `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Pre-computed Iceberg partition value. For series tables (identity partition
	// on int month) this is raw yyyymm; for data tables (month(timestamp)
	// transform) this is months-since-epoch. The committer passes this through
	// unchanged to PartitionData.set(0, ...).
	PartitionValue int32 `protobuf:"varint,2,opt,name=partition_value,json=partitionValue,proto3" json:"partition_value,omitempty"`
	// Storage-agnostic object key, e.g. s3://… URIs for S3/MinIO or gs://… URIs for GCS.
	// The Iceberg catalog's FileIO resolves the appropriate cheme at commit time.
	// Also used as the dedupe key for the snapshot-summary ledger (nominal.appended-paths), so producers must
	// emit deterministic keys across writer retries.
	ObjectKey string `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// Wall-clock ingest timestamp captured by the writer, primarily for
	// observability (lag, end-to-end latency monitoring).
	IngestedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"`
	// Provenance of the upstream channel-writer Kafka batch this file was written
	// from. The committer dedupes by recording, per (source_topic,
	// source_partition), the highest source_end_offset it has committed into each
	// table (snapshot summary property nominal.source-watermarks) and skipping any
	// file whose source_end_offset is at or below that watermark.
	//
	// This is robust where a WAL-offset watermark would not be: the writer
	// re-emits the same file (same provenance) at a NEW WAL offset on reprocessing
	// (see IcebergStreamWriter.writeParquetToleratingAlreadyExists), so dedupe must
	// key on the upstream offset, which is stable across re-emits.
	//
	// These fields are additive, but the streaming committer assumes they are
	// present: the WAL is drained before cutover (see the watermark rollout), so
	// every streaming event produced after deploy carries provenance. An event that
	// nonetheless arrives without source_topic is treated as a new file and appended
	// (never dropped); it is NOT deduped against the file-name ledger
	// (nominal.appended-paths), which is used only by the bulk-ingest path.
	SourceTopic     string `protobuf:"bytes,5,opt,name=source_topic,json=sourceTopic,proto3" json:"source_topic,omitempty"`
	SourcePartition int32  `protobuf:"varint,6,opt,name=source_partition,json=sourcePartition,proto3" json:"source_partition,omitempty"`
	SourceEndOffset int64  `protobuf:"varint,7,opt,name=source_end_offset,json=sourceEndOffset,proto3" json:"source_end_offset,omitempty"`
	// Earliest upstream Kafka record timestamp among the records merged into this file.
	//
	// Unset when the write has no upstream Kafka origin (video series) or predates this field.
	OldestSourceRecordTimestamp *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=oldest_source_record_timestamp,json=oldestSourceRecordTimestamp,proto3" json:"oldest_source_record_timestamp,omitempty"`
	// Size in bytes of the Parquet object at object_key.
	FileSizeBytes *int64 `protobuf:"varint,9,opt,name=file_size_bytes,json=fileSizeBytes,proto3,oneof" json:"file_size_bytes,omitempty"`
	// File statistics as the writing Iceberg FileAppender reported them.
	// If the Iceberg libraries start reporting a new set of metrics that aren't covered by a case here, the appender
	// should fall back to recalculating metrics itself at commit time.
	// Adding a variant is the ONLY compatible way to change these statistics.
	//
	// Types that are valid to be assigned to Metrics:
	//
	//	*IcebergFileWrittenEvent_MetricsV1
	Metrics       isIcebergFileWrittenEvent_Metrics `protobuf_oneof:"metrics"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergFileWrittenEvent) Reset() {
	*x = IcebergFileWrittenEvent{}
	mi := &file_nominal_protos_iceberg_v1_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergFileWrittenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergFileWrittenEvent) ProtoMessage() {}

func (x *IcebergFileWrittenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_iceberg_v1_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergFileWrittenEvent.ProtoReflect.Descriptor instead.
func (*IcebergFileWrittenEvent) Descriptor() ([]byte, []int) {
	return file_nominal_protos_iceberg_v1_wal_proto_rawDescGZIP(), []int{0}
}

func (x *IcebergFileWrittenEvent) GetTable() *TableTarget {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *IcebergFileWrittenEvent) GetPartitionValue() int32 {
	if x != nil {
		return x.PartitionValue
	}
	return 0
}

func (x *IcebergFileWrittenEvent) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *IcebergFileWrittenEvent) GetIngestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestedAt
	}
	return nil
}

func (x *IcebergFileWrittenEvent) GetSourceTopic() string {
	if x != nil {
		return x.SourceTopic
	}
	return ""
}

func (x *IcebergFileWrittenEvent) GetSourcePartition() int32 {
	if x != nil {
		return x.SourcePartition
	}
	return 0
}

func (x *IcebergFileWrittenEvent) GetSourceEndOffset() int64 {
	if x != nil {
		return x.SourceEndOffset
	}
	return 0
}

func (x *IcebergFileWrittenEvent) GetOldestSourceRecordTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestSourceRecordTimestamp
	}
	return nil
}

func (x *IcebergFileWrittenEvent) GetFileSizeBytes() int64 {
	if x != nil && x.FileSizeBytes != nil {
		return *x.FileSizeBytes
	}
	return 0
}

func (x *IcebergFileWrittenEvent) GetMetrics() isIcebergFileWrittenEvent_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *IcebergFileWrittenEvent) GetMetricsV1() *IcebergFileMetricsV1 {
	if x != nil {
		if x, ok := x.Metrics.(*IcebergFileWrittenEvent_MetricsV1); ok {
			return x.MetricsV1
		}
	}
	return nil
}

type isIcebergFileWrittenEvent_Metrics interface {
	isIcebergFileWrittenEvent_Metrics()
}

type IcebergFileWrittenEvent_MetricsV1 struct {
	MetricsV1 *IcebergFileMetricsV1 `protobuf:"bytes,10,opt,name=metrics_v1,json=metricsV1,proto3,oneof"`
}

func (*IcebergFileWrittenEvent_MetricsV1) isIcebergFileWrittenEvent_Metrics() {}

// Iceberg file statistics as org.apache.iceberg.Metrics carried them at Iceberg 1.11, keyed
// throughout by Iceberg field ID.
type IcebergFileMetricsV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Iceberg schema ID (Schema.schemaId) the writer computed these statistics against.
	//
	// If this value does not equal the table's current schema ID, read the footer from object storage instead.
	// Statistics are keyed by field ID: schema changes re-keys field IDs. Thus,  an evolved table would get statistics
	// for field IDs it no longer has, or none for a column it just gained.
	// Events in flight across a schema change therefore pay the footer read until the writer catches up.
	//
	// Optional so that schema ID 0 (a table that never evolved) is distinguishable from an unset field.
	// Absent counts as a mismatch.
	SchemaId *int32 `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3,oneof" json:"schema_id,omitempty"`
	// Number of rows in the file. Always positive: a zero-row file carries no metrics variant.
	RecordCount int64 `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	// Field ID to that column's total size in bytes across every row group.
	ColumnSizes map[int32]int64 `protobuf:"bytes,3,rep,name=column_sizes,json=columnSizes,proto3" json:"column_sizes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Field ID to the count of all values, nulls, NaNs and repeated values included.
	ValueCounts map[int32]int64 `protobuf:"bytes,4,rep,name=value_counts,json=valueCounts,proto3" json:"value_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Field ID to the count of null values.
	NullValueCounts map[int32]int64 `protobuf:"bytes,5,rep,name=null_value_counts,json=nullValueCounts,proto3" json:"null_value_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Field ID to the count of NaN values. Populated for float and double columns only.
	NanValueCounts map[int32]int64 `protobuf:"bytes,6,rep,name=nan_value_counts,json=nanValueCounts,proto3" json:"nan_value_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Field ID to that column's lower bound, in Iceberg's single-value serialization (Appendix D of
	// the Iceberg spec) and truncated per the table's write.metadata.metrics.* configuration. These
	// are the bytes Iceberg writes into the manifest verbatim, so this is the one place the WAL
	// schema does depend on an Iceberg encoding.
	LowerBounds map[int32][]byte `protobuf:"bytes,7,rep,name=lower_bounds,json=lowerBounds,proto3" json:"lower_bounds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Field ID to that column's upper bound, encoded as lower_bounds is.
	UpperBounds   map[int32][]byte `protobuf:"bytes,8,rep,name=upper_bounds,json=upperBounds,proto3" json:"upper_bounds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergFileMetricsV1) Reset() {
	*x = IcebergFileMetricsV1{}
	mi := &file_nominal_protos_iceberg_v1_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergFileMetricsV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergFileMetricsV1) ProtoMessage() {}

func (x *IcebergFileMetricsV1) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_iceberg_v1_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergFileMetricsV1.ProtoReflect.Descriptor instead.
func (*IcebergFileMetricsV1) Descriptor() ([]byte, []int) {
	return file_nominal_protos_iceberg_v1_wal_proto_rawDescGZIP(), []int{1}
}

func (x *IcebergFileMetricsV1) GetSchemaId() int32 {
	if x != nil && x.SchemaId != nil {
		return *x.SchemaId
	}
	return 0
}

func (x *IcebergFileMetricsV1) GetRecordCount() int64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *IcebergFileMetricsV1) GetColumnSizes() map[int32]int64 {
	if x != nil {
		return x.ColumnSizes
	}
	return nil
}

func (x *IcebergFileMetricsV1) GetValueCounts() map[int32]int64 {
	if x != nil {
		return x.ValueCounts
	}
	return nil
}

func (x *IcebergFileMetricsV1) GetNullValueCounts() map[int32]int64 {
	if x != nil {
		return x.NullValueCounts
	}
	return nil
}

func (x *IcebergFileMetricsV1) GetNanValueCounts() map[int32]int64 {
	if x != nil {
		return x.NanValueCounts
	}
	return nil
}

func (x *IcebergFileMetricsV1) GetLowerBounds() map[int32][]byte {
	if x != nil {
		return x.LowerBounds
	}
	return nil
}

func (x *IcebergFileMetricsV1) GetUpperBounds() map[int32][]byte {
	if x != nil {
		return x.UpperBounds
	}
	return nil
}

var File_nominal_protos_iceberg_v1_wal_proto protoreflect.FileDescriptor

const file_nominal_protos_iceberg_v1_wal_proto_rawDesc = "" +
	"\n" +
	"#nominal/protos/iceberg/v1/wal.proto\x12\x12nominal.iceberg.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%nominal/protos/iceberg/v1/table.proto\"\xe1\x04\n" +
	"\x17IcebergFileWrittenEvent\x12=\n" +
	"\x05table\x18\x01 \x01(\v2\x1f.nominal.iceberg.v1.TableTargetB\x06\xbaH\x03\xc8\x01\x01R\x05table\x12'\n" +
	"\x0fpartition_value\x18\x02 \x01(\x05R\x0epartitionValue\x12&\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tobjectKey\x12;\n" +
	"\vingested_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestedAt\x12!\n" +
	"\fsource_topic\x18\x05 \x01(\tR\vsourceTopic\x12)\n" +
	"\x10source_partition\x18\x06 \x01(\x05R\x0fsourcePartition\x12*\n" +
	"\x11source_end_offset\x18\a \x01(\x03R\x0fsourceEndOffset\x12_\n" +
	"\x1eoldest_source_record_timestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x1boldestSourceRecordTimestamp\x124\n" +
	"\x0ffile_size_bytes\x18\t \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x01R\rfileSizeBytes\x88\x01\x01\x12I\n" +
	"\n" +
	"metrics_v1\x18\n" +
	" \x01(\v2(.nominal.iceberg.v1.IcebergFileMetricsV1H\x00R\tmetricsV1B\t\n" +
	"\ametricsB\x12\n" +
	"\x10_file_size_bytes\"\xc4\b\n" +
	"\x14IcebergFileMetricsV1\x12 \n" +
	"\tschema_id\x18\x01 \x01(\x05H\x00R\bschemaId\x88\x01\x01\x12*\n" +
	"\frecord_count\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\vrecordCount\x12\\\n" +
	"\fcolumn_sizes\x18\x03 \x03(\v29.nominal.iceberg.v1.IcebergFileMetricsV1.ColumnSizesEntryR\vcolumnSizes\x12\\\n" +
	"\fvalue_counts\x18\x04 \x03(\v29.nominal.iceberg.v1.IcebergFileMetricsV1.ValueCountsEntryR\vvalueCounts\x12i\n" +
	"\x11null_value_counts\x18\x05 \x03(\v2=.nominal.iceberg.v1.IcebergFileMetricsV1.NullValueCountsEntryR\x0fnullValueCounts\x12f\n" +
	"\x10nan_value_counts\x18\x06 \x03(\v2<.nominal.iceberg.v1.IcebergFileMetricsV1.NanValueCountsEntryR\x0enanValueCounts\x12\\\n" +
	"\flower_bounds\x18\a \x03(\v29.nominal.iceberg.v1.IcebergFileMetricsV1.LowerBoundsEntryR\vlowerBounds\x12\\\n" +
	"\fupper_bounds\x18\b \x03(\v29.nominal.iceberg.v1.IcebergFileMetricsV1.UpperBoundsEntryR\vupperBounds\x1a>\n" +
	"\x10ColumnSizesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10ValueCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14NullValueCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aA\n" +
	"\x13NanValueCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10LowerBoundsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a>\n" +
	"\x10UpperBoundsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_schema_idB\xdd\x01\n" +
	"\x16com.nominal.iceberg.v1B\bWalProtoP\x01ZOgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/iceberg/v1;icebergv1\xa2\x02\x03NIX\xaa\x02\x12Nominal.Iceberg.V1\xca\x02\x12Nominal\\Iceberg\\V1\xe2\x02\x1eNominal\\Iceberg\\V1\\GPBMetadata\xea\x02\x14Nominal::Iceberg::V1b\x06proto3"

var (
	file_nominal_protos_iceberg_v1_wal_proto_rawDescOnce sync.Once
	file_nominal_protos_iceberg_v1_wal_proto_rawDescData []byte
)

func file_nominal_protos_iceberg_v1_wal_proto_rawDescGZIP() []byte {
	file_nominal_protos_iceberg_v1_wal_proto_rawDescOnce.Do(func() {
		file_nominal_protos_iceberg_v1_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_iceberg_v1_wal_proto_rawDesc), len(file_nominal_protos_iceberg_v1_wal_proto_rawDesc)))
	})
	return file_nominal_protos_iceberg_v1_wal_proto_rawDescData
}

var file_nominal_protos_iceberg_v1_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nominal_protos_iceberg_v1_wal_proto_goTypes = []any{
	(*IcebergFileWrittenEvent)(nil), // 0: nominal.iceberg.v1.IcebergFileWrittenEvent
	(*IcebergFileMetricsV1)(nil),    // 1: nominal.iceberg.v1.IcebergFileMetricsV1
	nil,                             // 2: nominal.iceberg.v1.IcebergFileMetricsV1.ColumnSizesEntry
	nil,                             // 3: nominal.iceberg.v1.IcebergFileMetricsV1.ValueCountsEntry
	nil,                             // 4: nominal.iceberg.v1.IcebergFileMetricsV1.NullValueCountsEntry
	nil,                             // 5: nominal.iceberg.v1.IcebergFileMetricsV1.NanValueCountsEntry
	nil,                             // 6: nominal.iceberg.v1.IcebergFileMetricsV1.LowerBoundsEntry
	nil,                             // 7: nominal.iceberg.v1.IcebergFileMetricsV1.UpperBoundsEntry
	(*TableTarget)(nil),             // 8: nominal.iceberg.v1.TableTarget
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_nominal_protos_iceberg_v1_wal_proto_depIdxs = []int32{
	8,  // 0: nominal.iceberg.v1.IcebergFileWrittenEvent.table:type_name -> nominal.iceberg.v1.TableTarget
	9,  // 1: nominal.iceberg.v1.IcebergFileWrittenEvent.ingested_at:type_name -> google.protobuf.Timestamp
	9,  // 2: nominal.iceberg.v1.IcebergFileWrittenEvent.oldest_source_record_timestamp:type_name -> google.protobuf.Timestamp
	1,  // 3: nominal.iceberg.v1.IcebergFileWrittenEvent.metrics_v1:type_name -> nominal.iceberg.v1.IcebergFileMetricsV1
	2,  // 4: nominal.iceberg.v1.IcebergFileMetricsV1.column_sizes:type_name -> nominal.iceberg.v1.IcebergFileMetricsV1.ColumnSizesEntry
	3,  // 5: nominal.iceberg.v1.IcebergFileMetricsV1.value_counts:type_name -> nominal.iceberg.v1.IcebergFileMetricsV1.ValueCountsEntry
	4,  // 6: nominal.iceberg.v1.IcebergFileMetricsV1.null_value_counts:type_name -> nominal.iceberg.v1.IcebergFileMetricsV1.NullValueCountsEntry
	5,  // 7: nominal.iceberg.v1.IcebergFileMetricsV1.nan_value_counts:type_name -> nominal.iceberg.v1.IcebergFileMetricsV1.NanValueCountsEntry
	6,  // 8: nominal.iceberg.v1.IcebergFileMetricsV1.lower_bounds:type_name -> nominal.iceberg.v1.IcebergFileMetricsV1.LowerBoundsEntry
	7,  // 9: nominal.iceberg.v1.IcebergFileMetricsV1.upper_bounds:type_name -> nominal.iceberg.v1.IcebergFileMetricsV1.UpperBoundsEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_nominal_protos_iceberg_v1_wal_proto_init() }
func file_nominal_protos_iceberg_v1_wal_proto_init() {
	if File_nominal_protos_iceberg_v1_wal_proto != nil {
		return
	}
	file_nominal_protos_iceberg_v1_table_proto_init()
	file_nominal_protos_iceberg_v1_wal_proto_msgTypes[0].OneofWrappers = []any{
		(*IcebergFileWrittenEvent_MetricsV1)(nil),
	}
	file_nominal_protos_iceberg_v1_wal_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_iceberg_v1_wal_proto_rawDesc), len(file_nominal_protos_iceberg_v1_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nominal_protos_iceberg_v1_wal_proto_goTypes,
		DependencyIndexes: file_nominal_protos_iceberg_v1_wal_proto_depIdxs,
		MessageInfos:      file_nominal_protos_iceberg_v1_wal_proto_msgTypes,
	}.Build()
	File_nominal_protos_iceberg_v1_wal_proto = out.File
	file_nominal_protos_iceberg_v1_wal_proto_goTypes = nil
	file_nominal_protos_iceberg_v1_wal_proto_depIdxs = nil
}
