// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/usage_tracking/v1/usage_tracking.proto

package usage_trackingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of resource involved in a usage tracking event.
// buf:lint:ignore ENUM_VALUE_PREFIX
type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_RESOURCE_TYPE_WORKBOOK    ResourceType = 1
	ResourceType_RESOURCE_TYPE_CHECKLIST   ResourceType = 2
	ResourceType_RESOURCE_TYPE_PROCEDURE   ResourceType = 3
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_WORKBOOK",
		2: "RESOURCE_TYPE_CHECKLIST",
		3: "RESOURCE_TYPE_PROCEDURE",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"RESOURCE_TYPE_WORKBOOK":    1,
		"RESOURCE_TYPE_CHECKLIST":   2,
		"RESOURCE_TYPE_PROCEDURE":   3,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_usage_tracking_v1_usage_tracking_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_nominal_protos_usage_tracking_v1_usage_tracking_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescGZIP(), []int{0}
}

// A resource-opened event.
type ResourceOpenedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of resource that was opened.
	ResourceType ResourceType `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=nominal.usage_tracking.v1.ResourceType" json:"resource_type,omitempty"`
	// The RID of the resource that was opened.
	Rid string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	// Whether the current user is the creator of the resource.
	IsCreator     bool `protobuf:"varint,3,opt,name=is_creator,json=isCreator,proto3" json:"is_creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceOpenedEvent) Reset() {
	*x = ResourceOpenedEvent{}
	mi := &file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceOpenedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceOpenedEvent) ProtoMessage() {}

func (x *ResourceOpenedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceOpenedEvent.ProtoReflect.Descriptor instead.
func (*ResourceOpenedEvent) Descriptor() ([]byte, []int) {
	return file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceOpenedEvent) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *ResourceOpenedEvent) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *ResourceOpenedEvent) GetIsCreator() bool {
	if x != nil {
		return x.IsCreator
	}
	return false
}

// Request to track a usage event.
type TrackEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace in which the event occurred.
	WorkspaceRid string `protobuf:"bytes,1,opt,name=workspace_rid,json=workspaceRid,proto3" json:"workspace_rid,omitempty"`
	// The event to track. Exactly one must be set.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*TrackEventRequest_ResourceOpened
	Event         isTrackEventRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *TrackEventRequest) GetWorkspaceRid() string {
	if x != nil {
		return x.WorkspaceRid
	}
	return ""
}

func (x *TrackEventRequest) GetEvent() isTrackEventRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TrackEventRequest) GetResourceOpened() *ResourceOpenedEvent {
	if x != nil {
		if x, ok := x.Event.(*TrackEventRequest_ResourceOpened); ok {
			return x.ResourceOpened
		}
	}
	return nil
}

type isTrackEventRequest_Event interface {
	isTrackEventRequest_Event()
}

type TrackEventRequest_ResourceOpened struct {
	ResourceOpened *ResourceOpenedEvent `protobuf:"bytes,2,opt,name=resource_opened,json=resourceOpened,proto3,oneof"`
}

func (*TrackEventRequest_ResourceOpened) isTrackEventRequest_Event() {}

// Response for tracking a usage event.
type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescGZIP(), []int{2}
}

var File_nominal_protos_usage_tracking_v1_usage_tracking_proto protoreflect.FileDescriptor

const file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDesc = "" +
	"\n" +
	"5nominal/protos/usage_tracking/v1/usage_tracking.proto\x12\x19nominal.usage_tracking.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a!nominal/protos/gen/v1/alias.proto\"\xce\x01\n" +
	"\x13ResourceOpenedEvent\x12V\n" +
	"\rresource_type\x18\x01 \x01(\x0e2'.nominal.usage_tracking.v1.ResourceTypeB\b\xbaH\x05\x82\x01\x02 \x00R\fresourceType\x12@\n" +
	"\x03rid\x18\x02 \x01(\tB.\xbaH\x03\xc8\x01\x01\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\x03rid\x12\x1d\n" +
	"\n" +
	"is_creator\x18\x03 \x01(\bR\tisCreator\"\xd1\x01\n" +
	"\x11TrackEventRequest\x12Q\n" +
	"\rworkspace_rid\x18\x01 \x01(\tB,\xbaH\x03\xc8\x01\x01\x9a\xb2\x1a\"\n" +
	" io.nominal.api.rids.WorkspaceRidR\fworkspaceRid\x12Y\n" +
	"\x0fresource_opened\x18\x02 \x01(\v2..nominal.usage_tracking.v1.ResourceOpenedEventH\x00R\x0eresourceOpenedB\x0e\n" +
	"\x05event\x12\x05\xbaH\x02\b\x01\"\x14\n" +
	"\x12TrackEventResponse*\x83\x01\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RESOURCE_TYPE_WORKBOOK\x10\x01\x12\x1b\n" +
	"\x17RESOURCE_TYPE_CHECKLIST\x10\x02\x12\x1b\n" +
	"\x17RESOURCE_TYPE_PROCEDURE\x10\x032\xa8\x01\n" +
	"\x14UsageTrackingService\x12\x8f\x01\n" +
	"\n" +
	"TrackEvent\x12,.nominal.usage_tracking.v1.TrackEventRequest\x1a-.nominal.usage_tracking.v1.TrackEventResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/usage-tracking/v1/eventsB\x94\x02\n" +
	"\x1dcom.nominal.usage_tracking.v1B\x12UsageTrackingProtoP\x01Z]github.com/nominal-io/nominal-api-protos-go/nominal/protos/usage_tracking/v1;usage_trackingv1\xa2\x02\x03NUX\xaa\x02\x18Nominal.UsageTracking.V1\xca\x02\x18Nominal\\UsageTracking\\V1\xe2\x02$Nominal\\UsageTracking\\V1\\GPBMetadata\xea\x02\x1aNominal::UsageTracking::V1b\x06proto3"

var (
	file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescOnce sync.Once
	file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescData []byte
)

func file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescGZIP() []byte {
	file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescOnce.Do(func() {
		file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDesc), len(file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDesc)))
	})
	return file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDescData
}

var file_nominal_protos_usage_tracking_v1_usage_tracking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nominal_protos_usage_tracking_v1_usage_tracking_proto_goTypes = []any{
	(ResourceType)(0),           // 0: nominal.usage_tracking.v1.ResourceType
	(*ResourceOpenedEvent)(nil), // 1: nominal.usage_tracking.v1.ResourceOpenedEvent
	(*TrackEventRequest)(nil),   // 2: nominal.usage_tracking.v1.TrackEventRequest
	(*TrackEventResponse)(nil),  // 3: nominal.usage_tracking.v1.TrackEventResponse
}
var file_nominal_protos_usage_tracking_v1_usage_tracking_proto_depIdxs = []int32{
	0, // 0: nominal.usage_tracking.v1.ResourceOpenedEvent.resource_type:type_name -> nominal.usage_tracking.v1.ResourceType
	1, // 1: nominal.usage_tracking.v1.TrackEventRequest.resource_opened:type_name -> nominal.usage_tracking.v1.ResourceOpenedEvent
	2, // 2: nominal.usage_tracking.v1.UsageTrackingService.TrackEvent:input_type -> nominal.usage_tracking.v1.TrackEventRequest
	3, // 3: nominal.usage_tracking.v1.UsageTrackingService.TrackEvent:output_type -> nominal.usage_tracking.v1.TrackEventResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nominal_protos_usage_tracking_v1_usage_tracking_proto_init() }
func file_nominal_protos_usage_tracking_v1_usage_tracking_proto_init() {
	if File_nominal_protos_usage_tracking_v1_usage_tracking_proto != nil {
		return
	}
	file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes[1].OneofWrappers = []any{
		(*TrackEventRequest_ResourceOpened)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDesc), len(file_nominal_protos_usage_tracking_v1_usage_tracking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_usage_tracking_v1_usage_tracking_proto_goTypes,
		DependencyIndexes: file_nominal_protos_usage_tracking_v1_usage_tracking_proto_depIdxs,
		EnumInfos:         file_nominal_protos_usage_tracking_v1_usage_tracking_proto_enumTypes,
		MessageInfos:      file_nominal_protos_usage_tracking_v1_usage_tracking_proto_msgTypes,
	}.Build()
	File_nominal_protos_usage_tracking_v1_usage_tracking_proto = out.File
	file_nominal_protos_usage_tracking_v1_usage_tracking_proto_goTypes = nil
	file_nominal_protos_usage_tracking_v1_usage_tracking_proto_depIdxs = nil
}
