// This proto file was generated from the InternalApiKeyService and InternalSandboxTokenService
// definitions in authorization-service-api.yml.
// Care should be taken while both files exist to maintain backwards compatibility with the Conjure
// generated code.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/internalauthorization/v1/internal_authorization.proto

package internalauthorizationv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Which sandbox workspace to create a token for. Each has its own service user, so
// the two values are two user identities in the same sandbox org.
type SandboxWorkspace int32

const (
	// The default, when unspecified, is the PRIMARY workspace.
	SandboxWorkspace_SANDBOX_WORKSPACE_UNSPECIFIED SandboxWorkspace = 0
	SandboxWorkspace_SANDBOX_WORKSPACE_PRIMARY     SandboxWorkspace = 1
	SandboxWorkspace_SANDBOX_WORKSPACE_SECONDARY   SandboxWorkspace = 2
)

// Enum value maps for SandboxWorkspace.
var (
	SandboxWorkspace_name = map[int32]string{
		0: "SANDBOX_WORKSPACE_UNSPECIFIED",
		1: "SANDBOX_WORKSPACE_PRIMARY",
		2: "SANDBOX_WORKSPACE_SECONDARY",
	}
	SandboxWorkspace_value = map[string]int32{
		"SANDBOX_WORKSPACE_UNSPECIFIED": 0,
		"SANDBOX_WORKSPACE_PRIMARY":     1,
		"SANDBOX_WORKSPACE_SECONDARY":   2,
	}
)

func (x SandboxWorkspace) Enum() *SandboxWorkspace {
	p := new(SandboxWorkspace)
	*p = x
	return p
}

func (x SandboxWorkspace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxWorkspace) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes[0].Descriptor()
}

func (SandboxWorkspace) Type() protoreflect.EnumType {
	return &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes[0]
}

func (x SandboxWorkspace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxWorkspace.Descriptor instead.
func (SandboxWorkspace) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP(), []int{0}
}

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type InternalApiKeyError int32

const (
	// The provided API key value is malformed or does not correspond to any known API key. The two
	// cases are intentionally indistinguishable to callers.
	InternalApiKeyError_INTERNAL_API_KEY_ERROR_API_KEY_NOT_FOUND InternalApiKeyError = 0
)

// Enum value maps for InternalApiKeyError.
var (
	InternalApiKeyError_name = map[int32]string{
		0: "INTERNAL_API_KEY_ERROR_API_KEY_NOT_FOUND",
	}
	InternalApiKeyError_value = map[string]int32{
		"INTERNAL_API_KEY_ERROR_API_KEY_NOT_FOUND": 0,
	}
)

func (x InternalApiKeyError) Enum() *InternalApiKeyError {
	p := new(InternalApiKeyError)
	*p = x
	return p
}

func (x InternalApiKeyError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalApiKeyError) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes[1].Descriptor()
}

func (InternalApiKeyError) Type() protoreflect.EnumType {
	return &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes[1]
}

func (x InternalApiKeyError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalApiKeyError.Descriptor instead.
func (InternalApiKeyError) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP(), []int{1}
}

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type InternalSandboxTokenError int32

const (
	// The endpoint cannot mint a sandbox token — either because no sandbox configuration is present
	// on this gatekeeper instance, or because the shared-secret header is missing or does not match.
	// The cases are intentionally indistinguishable to callers.
	InternalSandboxTokenError_INTERNAL_SANDBOX_TOKEN_ERROR_SANDBOX_TOKEN_UNAVAILABLE InternalSandboxTokenError = 0
)

// Enum value maps for InternalSandboxTokenError.
var (
	InternalSandboxTokenError_name = map[int32]string{
		0: "INTERNAL_SANDBOX_TOKEN_ERROR_SANDBOX_TOKEN_UNAVAILABLE",
	}
	InternalSandboxTokenError_value = map[string]int32{
		"INTERNAL_SANDBOX_TOKEN_ERROR_SANDBOX_TOKEN_UNAVAILABLE": 0,
	}
)

func (x InternalSandboxTokenError) Enum() *InternalSandboxTokenError {
	p := new(InternalSandboxTokenError)
	*p = x
	return p
}

func (x InternalSandboxTokenError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalSandboxTokenError) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes[2].Descriptor()
}

func (InternalSandboxTokenError) Type() protoreflect.EnumType {
	return &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes[2]
}

func (x InternalSandboxTokenError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalSandboxTokenError.Descriptor instead.
func (InternalSandboxTokenError) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP(), []int{2}
}

type GetAccessTokenFromApiKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The long-lived Nominal API key value to exchange for an access token. Callers should verify
	// their key is formatted properly (prefixed with "nominal_api_key") before calling.
	ApiKeyValue   string `protobuf:"bytes,1,opt,name=api_key_value,json=apiKeyValue,proto3" json:"api_key_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenFromApiKeyRequest) Reset() {
	*x = GetAccessTokenFromApiKeyRequest{}
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenFromApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenFromApiKeyRequest) ProtoMessage() {}

func (x *GetAccessTokenFromApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenFromApiKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAccessTokenFromApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccessTokenFromApiKeyRequest) GetApiKeyValue() string {
	if x != nil {
		return x.ApiKeyValue
	}
	return ""
}

type GetAccessTokenFromApiKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SENSITIVE: JWT bearer token suitable for use as a Nominal Authorization header value. The
	// Conjure field was `safety: do-not-log`; proto3 has no equivalent, so never log this value or
	// serialize this message into a log/error payload.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Unix seconds at which the token expires.
	ExpiresAtSeconds int64 `protobuf:"varint,2,opt,name=expires_at_seconds,json=expiresAtSeconds,proto3" json:"expires_at_seconds,omitempty"`
	// UUID of the Nominal user the token authenticates. Serialized as a plain string to match the
	// Conjure `uuid` wire format.
	UserUuid string `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// UUID of the Nominal org the token authenticates the user into.
	OrgUuid string `protobuf:"bytes,4,opt,name=org_uuid,json=orgUuid,proto3" json:"org_uuid,omitempty"`
	// True if the key's creator reaches org_uuid as a guest rather than a member.
	IsGuest       bool `protobuf:"varint,5,opt,name=is_guest,json=isGuest,proto3" json:"is_guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenFromApiKeyResponse) Reset() {
	*x = GetAccessTokenFromApiKeyResponse{}
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenFromApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenFromApiKeyResponse) ProtoMessage() {}

func (x *GetAccessTokenFromApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenFromApiKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAccessTokenFromApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessTokenFromApiKeyResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetAccessTokenFromApiKeyResponse) GetExpiresAtSeconds() int64 {
	if x != nil {
		return x.ExpiresAtSeconds
	}
	return 0
}

func (x *GetAccessTokenFromApiKeyResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetAccessTokenFromApiKeyResponse) GetOrgUuid() string {
	if x != nil {
		return x.OrgUuid
	}
	return ""
}

func (x *GetAccessTokenFromApiKeyResponse) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

type IssueSandboxTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired token lifetime in seconds. Capped server-side at 3600 (1h). Omit to use the server
	// default (the cap). Non-positive values are rejected with SandboxTokenUnavailable rather than
	// silently upgraded to the cap.
	RequestedTtlSeconds *int64 `protobuf:"varint,1,opt,name=requested_ttl_seconds,json=requestedTtlSeconds,proto3,oneof" json:"requested_ttl_seconds,omitempty"`
	// SENSITIVE: shared secret. The Conjure endpoint carried this in the `X-Nominal-Sandbox-Shared-Secret`
	// header (`safety: do-not-log`). On the gRPC path the secret is carried in the request body instead;
	// gRPC callers must set it explicitly. proto3 has no do-not-log equivalent — never log this value or
	// serialize this message into a log/error payload. The legacy Conjure header path remains available
	// during dual-stack for the existing curl caller (this RPC has no `google.api.http` annotation, so the
	// transcoder does not shadow that Conjure path). `optional` so an absent value is omitted from the JSON
	// (a proto3 default `string` would emit an empty `sharedSecret` that a legacy Conjure request body
	// never carries).
	SharedSecret *string `protobuf:"bytes,2,opt,name=shared_secret,json=sharedSecret,proto3,oneof" json:"shared_secret,omitempty"`
	// Workspace to mint the token for. Defaults to SANDBOX_WORKSPACE_PRIMARY when unspecified.
	SandboxWorkspace SandboxWorkspace `protobuf:"varint,3,opt,name=sandbox_workspace,json=sandboxWorkspace,proto3,enum=nominal.internalauthorization.v1.SandboxWorkspace" json:"sandbox_workspace,omitempty"`
	// Whether to mint the token for a distinct administrator identity in the selected sandbox
	// organization. Defaults to false.
	IsAdmin       bool `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSandboxTokenRequest) Reset() {
	*x = IssueSandboxTokenRequest{}
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxTokenRequest) ProtoMessage() {}

func (x *IssueSandboxTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueSandboxTokenRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *IssueSandboxTokenRequest) GetRequestedTtlSeconds() int64 {
	if x != nil && x.RequestedTtlSeconds != nil {
		return *x.RequestedTtlSeconds
	}
	return 0
}

func (x *IssueSandboxTokenRequest) GetSharedSecret() string {
	if x != nil && x.SharedSecret != nil {
		return *x.SharedSecret
	}
	return ""
}

func (x *IssueSandboxTokenRequest) GetSandboxWorkspace() SandboxWorkspace {
	if x != nil {
		return x.SandboxWorkspace
	}
	return SandboxWorkspace_SANDBOX_WORKSPACE_UNSPECIFIED
}

func (x *IssueSandboxTokenRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type IssueSandboxTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SENSITIVE: bearer token. The Conjure field was `safety: do-not-log`; proto3 has no equivalent,
	// so never log this value or serialize this message into a log/error payload.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Unix seconds at which the token expires.
	ExpiresAtSeconds int64 `protobuf:"varint,2,opt,name=expires_at_seconds,json=expiresAtSeconds,proto3" json:"expires_at_seconds,omitempty"`
	// UUID of the sandbox user the token authenticates. Serialized as a plain string to match the
	// Conjure `uuid` wire format.
	UserUuid string `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// UUID of the sandbox org the token authenticates the user into.
	OrgUuid string `protobuf:"bytes,4,opt,name=org_uuid,json=orgUuid,proto3" json:"org_uuid,omitempty"`
	// RID of the configured sandbox workspace.
	WorkspaceRid  string `protobuf:"bytes,5,opt,name=workspace_rid,json=workspaceRid,proto3" json:"workspace_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSandboxTokenResponse) Reset() {
	*x = IssueSandboxTokenResponse{}
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxTokenResponse) ProtoMessage() {}

func (x *IssueSandboxTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueSandboxTokenResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *IssueSandboxTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *IssueSandboxTokenResponse) GetExpiresAtSeconds() int64 {
	if x != nil {
		return x.ExpiresAtSeconds
	}
	return 0
}

func (x *IssueSandboxTokenResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *IssueSandboxTokenResponse) GetOrgUuid() string {
	if x != nil {
		return x.OrgUuid
	}
	return ""
}

func (x *IssueSandboxTokenResponse) GetWorkspaceRid() string {
	if x != nil {
		return x.WorkspaceRid
	}
	return ""
}

var File_nominal_protos_internalauthorization_v1_internal_authorization_proto protoreflect.FileDescriptor

const file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDesc = "" +
	"\n" +
	"Dnominal/protos/internalauthorization/v1/internal_authorization.proto\x12 nominal.internalauthorization.v1\x1a\x1bbuf/validate/validate.proto\x1a!nominal/protos/gen/v1/alias.proto\x1a!nominal/protos/gen/v1/error.proto\"N\n" +
	"\x1fGetAccessTokenFromApiKeyRequest\x12+\n" +
	"\rapi_key_value\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vapiKeyValue\"\xc6\x01\n" +
	" GetAccessTokenFromApiKeyResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12,\n" +
	"\x12expires_at_seconds\x18\x02 \x01(\x03R\x10expiresAtSeconds\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12\x19\n" +
	"\borg_uuid\x18\x04 \x01(\tR\aorgUuid\x12\x19\n" +
	"\bis_guest\x18\x05 \x01(\bR\aisGuest\"\xa5\x02\n" +
	"\x18IssueSandboxTokenRequest\x127\n" +
	"\x15requested_ttl_seconds\x18\x01 \x01(\x03H\x00R\x13requestedTtlSeconds\x88\x01\x01\x12(\n" +
	"\rshared_secret\x18\x02 \x01(\tH\x01R\fsharedSecret\x88\x01\x01\x12_\n" +
	"\x11sandbox_workspace\x18\x03 \x01(\x0e22.nominal.internalauthorization.v1.SandboxWorkspaceR\x10sandboxWorkspace\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdminB\x18\n" +
	"\x16_requested_ttl_secondsB\x10\n" +
	"\x0e_shared_secret\"\xf1\x01\n" +
	"\x19IssueSandboxTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12,\n" +
	"\x12expires_at_seconds\x18\x02 \x01(\x03R\x10expiresAtSeconds\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12\x19\n" +
	"\borg_uuid\x18\x04 \x01(\tR\aorgUuid\x12K\n" +
	"\rworkspace_rid\x18\x05 \x01(\tB&\x9a\xb2\x1a\"\n" +
	" io.nominal.api.rids.WorkspaceRidR\fworkspaceRid*u\n" +
	"\x10SandboxWorkspace\x12!\n" +
	"\x1dSANDBOX_WORKSPACE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SANDBOX_WORKSPACE_PRIMARY\x10\x01\x12\x1f\n" +
	"\x1bSANDBOX_WORKSPACE_SECONDARY\x10\x02*d\n" +
	"\x13InternalApiKeyError\x12M\n" +
	"(INTERNAL_API_KEY_ERROR_API_KEY_NOT_FOUND\x10\x00\x1a\x1f\xb2\xb2\x1a\x1b\n" +
	"\tNOT_FOUND\x12\x0eApiKeyNotFound*\x89\x01\n" +
	"\x19InternalSandboxTokenError\x12l\n" +
	"6INTERNAL_SANDBOX_TOKEN_ERROR_SANDBOX_TOKEN_UNAVAILABLE\x10\x00\x1a0\xb2\xb2\x1a,\n" +
	"\x11PERMISSION_DENIED\x12\x17SandboxTokenUnavailable2\xc0\x01\n" +
	"\x15InternalApiKeyService\x12\xa6\x01\n" +
	"\x1dGetAccessTokenFromApiKeyValue\x12A.nominal.internalauthorization.v1.GetAccessTokenFromApiKeyRequest\x1aB.nominal.internalauthorization.v1.GetAccessTokenFromApiKeyResponse2\xac\x01\n" +
	"\x1bInternalSandboxTokenService\x12\x8c\x01\n" +
	"\x11IssueSandboxToken\x12:.nominal.internalauthorization.v1.IssueSandboxTokenRequest\x1a;.nominal.internalauthorization.v1.IssueSandboxTokenResponseB\xd1\x02\n" +
	"$com.nominal.internalauthorization.v1B\x1aInternalAuthorizationProtoP\x01Zkgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/internalauthorization/v1;internalauthorizationv1\xa2\x02\x03NIX\xaa\x02 Nominal.Internalauthorization.V1\xca\x02 Nominal\\Internalauthorization\\V1\xe2\x02,Nominal\\Internalauthorization\\V1\\GPBMetadata\xea\x02\"Nominal::Internalauthorization::V1b\x06proto3"

var (
	file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescOnce sync.Once
	file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescData []byte
)

func file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescGZIP() []byte {
	file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescOnce.Do(func() {
		file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDesc), len(file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDesc)))
	})
	return file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDescData
}

var file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nominal_protos_internalauthorization_v1_internal_authorization_proto_goTypes = []any{
	(SandboxWorkspace)(0),                    // 0: nominal.internalauthorization.v1.SandboxWorkspace
	(InternalApiKeyError)(0),                 // 1: nominal.internalauthorization.v1.InternalApiKeyError
	(InternalSandboxTokenError)(0),           // 2: nominal.internalauthorization.v1.InternalSandboxTokenError
	(*GetAccessTokenFromApiKeyRequest)(nil),  // 3: nominal.internalauthorization.v1.GetAccessTokenFromApiKeyRequest
	(*GetAccessTokenFromApiKeyResponse)(nil), // 4: nominal.internalauthorization.v1.GetAccessTokenFromApiKeyResponse
	(*IssueSandboxTokenRequest)(nil),         // 5: nominal.internalauthorization.v1.IssueSandboxTokenRequest
	(*IssueSandboxTokenResponse)(nil),        // 6: nominal.internalauthorization.v1.IssueSandboxTokenResponse
}
var file_nominal_protos_internalauthorization_v1_internal_authorization_proto_depIdxs = []int32{
	0, // 0: nominal.internalauthorization.v1.IssueSandboxTokenRequest.sandbox_workspace:type_name -> nominal.internalauthorization.v1.SandboxWorkspace
	3, // 1: nominal.internalauthorization.v1.InternalApiKeyService.GetAccessTokenFromApiKeyValue:input_type -> nominal.internalauthorization.v1.GetAccessTokenFromApiKeyRequest
	5, // 2: nominal.internalauthorization.v1.InternalSandboxTokenService.IssueSandboxToken:input_type -> nominal.internalauthorization.v1.IssueSandboxTokenRequest
	4, // 3: nominal.internalauthorization.v1.InternalApiKeyService.GetAccessTokenFromApiKeyValue:output_type -> nominal.internalauthorization.v1.GetAccessTokenFromApiKeyResponse
	6, // 4: nominal.internalauthorization.v1.InternalSandboxTokenService.IssueSandboxToken:output_type -> nominal.internalauthorization.v1.IssueSandboxTokenResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nominal_protos_internalauthorization_v1_internal_authorization_proto_init() }
func file_nominal_protos_internalauthorization_v1_internal_authorization_proto_init() {
	if File_nominal_protos_internalauthorization_v1_internal_authorization_proto != nil {
		return
	}
	file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDesc), len(file_nominal_protos_internalauthorization_v1_internal_authorization_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_nominal_protos_internalauthorization_v1_internal_authorization_proto_goTypes,
		DependencyIndexes: file_nominal_protos_internalauthorization_v1_internal_authorization_proto_depIdxs,
		EnumInfos:         file_nominal_protos_internalauthorization_v1_internal_authorization_proto_enumTypes,
		MessageInfos:      file_nominal_protos_internalauthorization_v1_internal_authorization_proto_msgTypes,
	}.Build()
	File_nominal_protos_internalauthorization_v1_internal_authorization_proto = out.File
	file_nominal_protos_internalauthorization_v1_internal_authorization_proto_goTypes = nil
	file_nominal_protos_internalauthorization_v1_internal_authorization_proto_depIdxs = nil
}
