// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/nova/v1/app_proxy.proto

package novav1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One app's access to one API proxy — a privilege rather than an association,
// since it will carry a credential the app's callers cannot read. Who created it
// is not here: Nova audit-logs the actor for every mutation.
type AppProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppRid        string                 `protobuf:"bytes,1,opt,name=app_rid,json=appRid,proto3" json:"app_rid,omitempty"`
	ApiProxyRid   string                 `protobuf:"bytes,2,opt,name=api_proxy_rid,json=apiProxyRid,proto3" json:"api_proxy_rid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppProxy) Reset() {
	*x = AppProxy{}
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppProxy) ProtoMessage() {}

func (x *AppProxy) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppProxy.ProtoReflect.Descriptor instead.
func (*AppProxy) Descriptor() ([]byte, []int) {
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *AppProxy) GetAppRid() string {
	if x != nil {
		return x.AppRid
	}
	return ""
}

func (x *AppProxy) GetApiProxyRid() string {
	if x != nil {
		return x.ApiProxyRid
	}
	return ""
}

func (x *AppProxy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAppProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppRid        string                 `protobuf:"bytes,1,opt,name=app_rid,json=appRid,proto3" json:"app_rid,omitempty"`
	ApiProxyRid   string                 `protobuf:"bytes,2,opt,name=api_proxy_rid,json=apiProxyRid,proto3" json:"api_proxy_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppProxyRequest) Reset() {
	*x = CreateAppProxyRequest{}
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppProxyRequest) ProtoMessage() {}

func (x *CreateAppProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppProxyRequest.ProtoReflect.Descriptor instead.
func (*CreateAppProxyRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppProxyRequest) GetAppRid() string {
	if x != nil {
		return x.AppRid
	}
	return ""
}

func (x *CreateAppProxyRequest) GetApiProxyRid() string {
	if x != nil {
		return x.ApiProxyRid
	}
	return ""
}

type CreateAppProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppProxy      *AppProxy              `protobuf:"bytes,1,opt,name=app_proxy,json=appProxy,proto3" json:"app_proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppProxyResponse) Reset() {
	*x = CreateAppProxyResponse{}
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppProxyResponse) ProtoMessage() {}

func (x *CreateAppProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppProxyResponse.ProtoReflect.Descriptor instead.
func (*CreateAppProxyResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAppProxyResponse) GetAppProxy() *AppProxy {
	if x != nil {
		return x.AppProxy
	}
	return nil
}

type DeleteAppProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppRid        string                 `protobuf:"bytes,1,opt,name=app_rid,json=appRid,proto3" json:"app_rid,omitempty"`
	ApiProxyRid   string                 `protobuf:"bytes,2,opt,name=api_proxy_rid,json=apiProxyRid,proto3" json:"api_proxy_rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppProxyRequest) Reset() {
	*x = DeleteAppProxyRequest{}
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppProxyRequest) ProtoMessage() {}

func (x *DeleteAppProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppProxyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppProxyRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAppProxyRequest) GetAppRid() string {
	if x != nil {
		return x.AppRid
	}
	return ""
}

func (x *DeleteAppProxyRequest) GetApiProxyRid() string {
	if x != nil {
		return x.ApiProxyRid
	}
	return ""
}

type DeleteAppProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppProxyResponse) Reset() {
	*x = DeleteAppProxyResponse{}
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppProxyResponse) ProtoMessage() {}

func (x *DeleteAppProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppProxyResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppProxyResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP(), []int{4}
}

type ListAppProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppRid        string                 `protobuf:"bytes,1,opt,name=app_rid,json=appRid,proto3" json:"app_rid,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppProxiesRequest) Reset() {
	*x = ListAppProxiesRequest{}
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppProxiesRequest) ProtoMessage() {}

func (x *ListAppProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppProxiesRequest.ProtoReflect.Descriptor instead.
func (*ListAppProxiesRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *ListAppProxiesRequest) GetAppRid() string {
	if x != nil {
		return x.AppRid
	}
	return ""
}

func (x *ListAppProxiesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListAppProxiesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListAppProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppProxies    []*AppProxy            `protobuf:"bytes,1,rep,name=app_proxies,json=appProxies,proto3" json:"app_proxies,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppProxiesResponse) Reset() {
	*x = ListAppProxiesResponse{}
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppProxiesResponse) ProtoMessage() {}

func (x *ListAppProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppProxiesResponse.ProtoReflect.Descriptor instead.
func (*ListAppProxiesResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *ListAppProxiesResponse) GetAppProxies() []*AppProxy {
	if x != nil {
		return x.AppProxies
	}
	return nil
}

func (x *ListAppProxiesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

var File_nominal_protos_nova_v1_app_proxy_proto protoreflect.FileDescriptor

const file_nominal_protos_nova_v1_app_proxy_proto_rawDesc = "" +
	"\n" +
	"&nominal/protos/nova/v1/app_proxy.proto\x12\x0fnominal.nova.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!nominal/protos/gen/v1/alias.proto\"\xe3\x01\n" +
	"\bAppProxy\x12E\n" +
	"\aapp_rid\x18\x01 \x01(\tB,\xbaH\x05r\x03\x18\x80\x04\x9a\xb2\x1a \n" +
	"\x1eio.nominal.api.rids.NovaAppRidR\x06appRid\x12U\n" +
	"\rapi_proxy_rid\x18\x02 \x01(\tB1\xbaH\x05r\x03\x18\x80\x04\x9a\xb2\x1a%\n" +
	"#io.nominal.api.rids.NovaApiProxyRidR\vapiProxyRid\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbf\x01\n" +
	"\x15CreateAppProxyRequest\x12J\n" +
	"\aapp_rid\x18\x01 \x01(\tB1\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x04\x9a\xb2\x1a \n" +
	"\x1eio.nominal.api.rids.NovaAppRidR\x06appRid\x12Z\n" +
	"\rapi_proxy_rid\x18\x02 \x01(\tB6\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x04\x9a\xb2\x1a%\n" +
	"#io.nominal.api.rids.NovaApiProxyRidR\vapiProxyRid\"P\n" +
	"\x16CreateAppProxyResponse\x126\n" +
	"\tapp_proxy\x18\x01 \x01(\v2\x19.nominal.nova.v1.AppProxyR\bappProxy\"\xbf\x01\n" +
	"\x15DeleteAppProxyRequest\x12J\n" +
	"\aapp_rid\x18\x01 \x01(\tB1\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x04\x9a\xb2\x1a \n" +
	"\x1eio.nominal.api.rids.NovaAppRidR\x06appRid\x12Z\n" +
	"\rapi_proxy_rid\x18\x02 \x01(\tB6\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x04\x9a\xb2\x1a%\n" +
	"#io.nominal.api.rids.NovaApiProxyRidR\vapiProxyRid\"\x18\n" +
	"\x16DeleteAppProxyResponse\"\xf5\x01\n" +
	"\x15ListAppProxiesRequest\x12J\n" +
	"\aapp_rid\x18\x01 \x01(\tB1\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x04\x9a\xb2\x1a \n" +
	"\x1eio.nominal.api.rids.NovaAppRidR\x06appRid\x12+\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01H\x00R\bpageSize\x88\x01\x01\x12F\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\"\xbaH\x05r\x03(\x80 \x9a\xb2\x1a\x16\n" +
	"\x14io.nominal.api.TokenH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xb1\x01\n" +
	"\x16ListAppProxiesResponse\x12:\n" +
	"\vapp_proxies\x18\x01 \x03(\v2\x19.nominal.nova.v1.AppProxyR\n" +
	"appProxies\x12G\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x1a\x9a\xb2\x1a\x16\n" +
	"\x14io.nominal.api.TokenH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token2\xcb\x03\n" +
	"\x0fAppProxyService\x12\x8d\x01\n" +
	"\x0eCreateAppProxy\x12&.nominal.nova.v1.CreateAppProxyRequest\x1a'.nominal.nova.v1.CreateAppProxyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/nova/v1/apps/{app_rid}/proxies\x12\x9a\x01\n" +
	"\x0eDeleteAppProxy\x12&.nominal.nova.v1.DeleteAppProxyRequest\x1a'.nominal.nova.v1.DeleteAppProxyResponse\"7\x82\xd3\xe4\x93\x021*//nova/v1/apps/{app_rid}/proxies/{api_proxy_rid}\x12\x8a\x01\n" +
	"\x0eListAppProxies\x12&.nominal.nova.v1.ListAppProxiesRequest\x1a'.nominal.nova.v1.ListAppProxiesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/nova/v1/apps/{app_rid}/proxiesB\xcd\x01\n" +
	"\x13com.nominal.nova.v1B\rAppProxyProtoP\x01ZIgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/nova/v1;novav1\xa2\x02\x03NNX\xaa\x02\x0fNominal.Nova.V1\xca\x02\x0fNominal\\Nova\\V1\xe2\x02\x1bNominal\\Nova\\V1\\GPBMetadata\xea\x02\x11Nominal::Nova::V1b\x06proto3"

var (
	file_nominal_protos_nova_v1_app_proxy_proto_rawDescOnce sync.Once
	file_nominal_protos_nova_v1_app_proxy_proto_rawDescData []byte
)

func file_nominal_protos_nova_v1_app_proxy_proto_rawDescGZIP() []byte {
	file_nominal_protos_nova_v1_app_proxy_proto_rawDescOnce.Do(func() {
		file_nominal_protos_nova_v1_app_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_nova_v1_app_proxy_proto_rawDesc), len(file_nominal_protos_nova_v1_app_proxy_proto_rawDesc)))
	})
	return file_nominal_protos_nova_v1_app_proxy_proto_rawDescData
}

var file_nominal_protos_nova_v1_app_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nominal_protos_nova_v1_app_proxy_proto_goTypes = []any{
	(*AppProxy)(nil),               // 0: nominal.nova.v1.AppProxy
	(*CreateAppProxyRequest)(nil),  // 1: nominal.nova.v1.CreateAppProxyRequest
	(*CreateAppProxyResponse)(nil), // 2: nominal.nova.v1.CreateAppProxyResponse
	(*DeleteAppProxyRequest)(nil),  // 3: nominal.nova.v1.DeleteAppProxyRequest
	(*DeleteAppProxyResponse)(nil), // 4: nominal.nova.v1.DeleteAppProxyResponse
	(*ListAppProxiesRequest)(nil),  // 5: nominal.nova.v1.ListAppProxiesRequest
	(*ListAppProxiesResponse)(nil), // 6: nominal.nova.v1.ListAppProxiesResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_nominal_protos_nova_v1_app_proxy_proto_depIdxs = []int32{
	7, // 0: nominal.nova.v1.AppProxy.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: nominal.nova.v1.CreateAppProxyResponse.app_proxy:type_name -> nominal.nova.v1.AppProxy
	0, // 2: nominal.nova.v1.ListAppProxiesResponse.app_proxies:type_name -> nominal.nova.v1.AppProxy
	1, // 3: nominal.nova.v1.AppProxyService.CreateAppProxy:input_type -> nominal.nova.v1.CreateAppProxyRequest
	3, // 4: nominal.nova.v1.AppProxyService.DeleteAppProxy:input_type -> nominal.nova.v1.DeleteAppProxyRequest
	5, // 5: nominal.nova.v1.AppProxyService.ListAppProxies:input_type -> nominal.nova.v1.ListAppProxiesRequest
	2, // 6: nominal.nova.v1.AppProxyService.CreateAppProxy:output_type -> nominal.nova.v1.CreateAppProxyResponse
	4, // 7: nominal.nova.v1.AppProxyService.DeleteAppProxy:output_type -> nominal.nova.v1.DeleteAppProxyResponse
	6, // 8: nominal.nova.v1.AppProxyService.ListAppProxies:output_type -> nominal.nova.v1.ListAppProxiesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nominal_protos_nova_v1_app_proxy_proto_init() }
func file_nominal_protos_nova_v1_app_proxy_proto_init() {
	if File_nominal_protos_nova_v1_app_proxy_proto != nil {
		return
	}
	file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[5].OneofWrappers = []any{}
	file_nominal_protos_nova_v1_app_proxy_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_nova_v1_app_proxy_proto_rawDesc), len(file_nominal_protos_nova_v1_app_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_nova_v1_app_proxy_proto_goTypes,
		DependencyIndexes: file_nominal_protos_nova_v1_app_proxy_proto_depIdxs,
		MessageInfos:      file_nominal_protos_nova_v1_app_proxy_proto_msgTypes,
	}.Build()
	File_nominal_protos_nova_v1_app_proxy_proto = out.File
	file_nominal_protos_nova_v1_app_proxy_proto_goTypes = nil
	file_nominal_protos_nova_v1_app_proxy_proto_depIdxs = nil
}
