// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/nova/v1/proxy.proto

package novav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NovaProxyService_CallApiProxy_FullMethodName = "/nominal.nova.v1.NovaProxyService/CallApiProxy"
)

// NovaProxyServiceClient is the client API for NovaProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Forwards app calls to the third party APIs their workspace has declared.
type NovaProxyServiceClient interface {
	// Forwards one HTTP request/response call.
	CallApiProxy(ctx context.Context, in *CallApiProxyRequest, opts ...grpc.CallOption) (*CallApiProxyResponse, error)
}

type novaProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNovaProxyServiceClient(cc grpc.ClientConnInterface) NovaProxyServiceClient {
	return &novaProxyServiceClient{cc}
}

func (c *novaProxyServiceClient) CallApiProxy(ctx context.Context, in *CallApiProxyRequest, opts ...grpc.CallOption) (*CallApiProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallApiProxyResponse)
	err := c.cc.Invoke(ctx, NovaProxyService_CallApiProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NovaProxyServiceServer is the server API for NovaProxyService service.
// All implementations must embed UnimplementedNovaProxyServiceServer
// for forward compatibility.
//
// Forwards app calls to the third party APIs their workspace has declared.
type NovaProxyServiceServer interface {
	// Forwards one HTTP request/response call.
	CallApiProxy(context.Context, *CallApiProxyRequest) (*CallApiProxyResponse, error)
	mustEmbedUnimplementedNovaProxyServiceServer()
}

// UnimplementedNovaProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNovaProxyServiceServer struct{}

func (UnimplementedNovaProxyServiceServer) CallApiProxy(context.Context, *CallApiProxyRequest) (*CallApiProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallApiProxy not implemented")
}
func (UnimplementedNovaProxyServiceServer) mustEmbedUnimplementedNovaProxyServiceServer() {}
func (UnimplementedNovaProxyServiceServer) testEmbeddedByValue()                          {}

// UnsafeNovaProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NovaProxyServiceServer will
// result in compilation errors.
type UnsafeNovaProxyServiceServer interface {
	mustEmbedUnimplementedNovaProxyServiceServer()
}

func RegisterNovaProxyServiceServer(s grpc.ServiceRegistrar, srv NovaProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedNovaProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NovaProxyService_ServiceDesc, srv)
}

func _NovaProxyService_CallApiProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallApiProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaProxyServiceServer).CallApiProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovaProxyService_CallApiProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaProxyServiceServer).CallApiProxy(ctx, req.(*CallApiProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NovaProxyService_ServiceDesc is the grpc.ServiceDesc for NovaProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NovaProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.nova.v1.NovaProxyService",
	HandlerType: (*NovaProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallApiProxy",
			Handler:    _NovaProxyService_CallApiProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/nova/v1/proxy.proto",
}
