// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/authorization/internal/v1/internal_proxy_jwt.proto

package internalv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type InternalProxyJwtError int32

const (
	// The endpoint cannot mint a Nominal access token from a proxy-injected
	// JWT — for any of: no customJwtProviders entry matches the JWT's iss;
	// the JWT fails verification; the verified email does not resolve to a
	// single Nominal user/org. The cases are intentionally indistinguishable
	// to callers to avoid leaking which proxy issuers are configured on this
	// deployment.
	InternalProxyJwtError_INTERNAL_PROXY_JWT_ERROR_PROXY_JWT_UNAVAILABLE InternalProxyJwtError = 0
)

// Enum value maps for InternalProxyJwtError.
var (
	InternalProxyJwtError_name = map[int32]string{
		0: "INTERNAL_PROXY_JWT_ERROR_PROXY_JWT_UNAVAILABLE",
	}
	InternalProxyJwtError_value = map[string]int32{
		"INTERNAL_PROXY_JWT_ERROR_PROXY_JWT_UNAVAILABLE": 0,
	}
)

func (x InternalProxyJwtError) Enum() *InternalProxyJwtError {
	p := new(InternalProxyJwtError)
	*p = x
	return p
}

func (x InternalProxyJwtError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalProxyJwtError) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_enumTypes[0].Descriptor()
}

func (InternalProxyJwtError) Type() protoreflect.EnumType {
	return &file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_enumTypes[0]
}

func (x InternalProxyJwtError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalProxyJwtError.Descriptor instead.
func (InternalProxyJwtError) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescGZIP(), []int{0}
}

type AccessToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT bearer token suitable for use as a Nominal Authorization header value.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Unix seconds at which the token expires.
	ExpiresAtSeconds int64 `protobuf:"varint,2,opt,name=expires_at_seconds,json=expiresAtSeconds,proto3" json:"expires_at_seconds,omitempty"`
	// RID of the Nominal user the token authenticates.
	UserRid string `protobuf:"bytes,3,opt,name=user_rid,json=userRid,proto3" json:"user_rid,omitempty"`
	// RID of the Nominal org the token authenticates the user into.
	OrgRid string `protobuf:"bytes,4,opt,name=org_rid,json=orgRid,proto3" json:"org_rid,omitempty"`
	// True if the user reaches org_rid as a guest rather than a member. This auth method only
	// works against member orgs, so this is always false, but the client shouldn't have to
	// infer that.
	IsGuest       bool `protobuf:"varint,5,opt,name=is_guest,json=isGuest,proto3" json:"is_guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *AccessToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccessToken) GetExpiresAtSeconds() int64 {
	if x != nil {
		return x.ExpiresAtSeconds
	}
	return 0
}

func (x *AccessToken) GetUserRid() string {
	if x != nil {
		return x.UserRid
	}
	return ""
}

func (x *AccessToken) GetOrgRid() string {
	if x != nil {
		return x.OrgRid
	}
	return ""
}

func (x *AccessToken) GetIsGuest() bool {
	if x != nil {
		return x.IsGuest
	}
	return false
}

type GetAccessTokenFromProxyJwtRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw JWT value forwarded by a zero-trust proxy. Not yet trusted by the
	// caller; gatekeeper performs full verification (signature, iss, aud, exp)
	// against the matching customJwtProviders entry before minting a token.
	ProxyJwt      string `protobuf:"bytes,1,opt,name=proxy_jwt,json=proxyJwt,proto3" json:"proxy_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenFromProxyJwtRequest) Reset() {
	*x = GetAccessTokenFromProxyJwtRequest{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenFromProxyJwtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenFromProxyJwtRequest) ProtoMessage() {}

func (x *GetAccessTokenFromProxyJwtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenFromProxyJwtRequest.ProtoReflect.Descriptor instead.
func (*GetAccessTokenFromProxyJwtRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessTokenFromProxyJwtRequest) GetProxyJwt() string {
	if x != nil {
		return x.ProxyJwt
	}
	return ""
}

type GetAccessTokenFromProxyJwtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *AccessToken           `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenFromProxyJwtResponse) Reset() {
	*x = GetAccessTokenFromProxyJwtResponse{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenFromProxyJwtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenFromProxyJwtResponse) ProtoMessage() {}

func (x *GetAccessTokenFromProxyJwtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenFromProxyJwtResponse.ProtoReflect.Descriptor instead.
func (*GetAccessTokenFromProxyJwtResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccessTokenFromProxyJwtResponse) GetAccessToken() *AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

var File_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto protoreflect.FileDescriptor

const file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDesc = "" +
	"\n" +
	"Anominal/protos/authorization/internal/v1/internal_proxy_jwt.proto\x12!nominal.authorization.internal.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a!nominal/protos/gen/v1/alias.proto\x1a!nominal/protos/gen/v1/error.proto\"\xf9\x01\n" +
	"\vAccessToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12,\n" +
	"\x12expires_at_seconds\x18\x02 \x01(\x03R\x10expiresAtSeconds\x12F\n" +
	"\buser_rid\x18\x03 \x01(\tB+\x9a\xb2\x1a'\n" +
	"%io.nominal.authentication.api.UserRidR\auserRid\x12C\n" +
	"\aorg_rid\x18\x04 \x01(\tB*\x9a\xb2\x1a&\n" +
	"$io.nominal.authentication.api.OrgRidR\x06orgRid\x12\x19\n" +
	"\bis_guest\x18\x05 \x01(\bR\aisGuest\"I\n" +
	"!GetAccessTokenFromProxyJwtRequest\x12$\n" +
	"\tproxy_jwt\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bproxyJwt\"w\n" +
	"\"GetAccessTokenFromProxyJwtResponse\x12Q\n" +
	"\faccess_token\x18\x01 \x01(\v2..nominal.authorization.internal.v1.AccessTokenR\vaccessToken*y\n" +
	"\x15InternalProxyJwtError\x12`\n" +
	".INTERNAL_PROXY_JWT_ERROR_PROXY_JWT_UNAVAILABLE\x10\x00\x1a,\xb2\xb2\x1a(\n" +
	"\x11PERMISSION_DENIED\x12\x13ProxyJwtUnavailable2\x8c\x02\n" +
	"\x17InternalProxyJwtService\x12\xf0\x01\n" +
	"\x1aGetAccessTokenFromProxyJwt\x12D.nominal.authorization.internal.v1.GetAccessTokenFromProxyJwtRequest\x1aE.nominal.authorization.internal.v1.GetAccessTokenFromProxyJwtResponse\"E\x82\xd3\xe4\x93\x02?\x12=/authorization/internal/v1/proxy-jwt/{proxy_jwt}/access-tokenB\xc6\x02\n" +
	"%com.nominal.authorization.internal.v1B\x15InternalProxyJwtProtoP\x01Z_github.com/nominal-io/nominal-api-protos-go/nominal/protos/authorization/internal/v1;internalv1\xa2\x02\x03NAI\xaa\x02!Nominal.Authorization.Internal.V1\xca\x02!Nominal\\Authorization\\Internal\\V1\xe2\x02-Nominal\\Authorization\\Internal\\V1\\GPBMetadata\xea\x02$Nominal::Authorization::Internal::V1b\x06proto3"

var (
	file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescOnce sync.Once
	file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescData []byte
)

func file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescGZIP() []byte {
	file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescOnce.Do(func() {
		file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDesc), len(file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDesc)))
	})
	return file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDescData
}

var file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_goTypes = []any{
	(InternalProxyJwtError)(0),                 // 0: nominal.authorization.internal.v1.InternalProxyJwtError
	(*AccessToken)(nil),                        // 1: nominal.authorization.internal.v1.AccessToken
	(*GetAccessTokenFromProxyJwtRequest)(nil),  // 2: nominal.authorization.internal.v1.GetAccessTokenFromProxyJwtRequest
	(*GetAccessTokenFromProxyJwtResponse)(nil), // 3: nominal.authorization.internal.v1.GetAccessTokenFromProxyJwtResponse
}
var file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_depIdxs = []int32{
	1, // 0: nominal.authorization.internal.v1.GetAccessTokenFromProxyJwtResponse.access_token:type_name -> nominal.authorization.internal.v1.AccessToken
	2, // 1: nominal.authorization.internal.v1.InternalProxyJwtService.GetAccessTokenFromProxyJwt:input_type -> nominal.authorization.internal.v1.GetAccessTokenFromProxyJwtRequest
	3, // 2: nominal.authorization.internal.v1.InternalProxyJwtService.GetAccessTokenFromProxyJwt:output_type -> nominal.authorization.internal.v1.GetAccessTokenFromProxyJwtResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_init() }
func file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_init() {
	if File_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDesc), len(file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_goTypes,
		DependencyIndexes: file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_depIdxs,
		EnumInfos:         file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_enumTypes,
		MessageInfos:      file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_msgTypes,
	}.Build()
	File_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto = out.File
	file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_goTypes = nil
	file_nominal_protos_authorization_internal_v1_internal_proxy_jwt_proto_depIdxs = nil
}
