// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/authorization/internal/v1/internal_refresh_coordination.proto

package internalv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome of a BeginRefresh call.
type RefreshCoordinationDecision int32

const (
	RefreshCoordinationDecision_REFRESH_COORDINATION_DECISION_UNSPECIFIED RefreshCoordinationDecision = 0
	// The caller holds the refresh lock for this credential and must perform
	// the refresh, then call CompleteRefresh (on success or terminal failure)
	// or AbandonRefresh (on transient failure).
	RefreshCoordinationDecision_REFRESH_COORDINATION_DECISION_ACQUIRED RefreshCoordinationDecision = 1
	// Another caller holds the lock; poll BeginRefresh until it returns
	// RESULT_AVAILABLE (the holder published), or ACQUIRED (the holder
	// abandoned or its lock expired, and this caller atomically took the lock
	// over and must perform the refresh itself).
	RefreshCoordinationDecision_REFRESH_COORDINATION_DECISION_WAIT RefreshCoordinationDecision = 2
	// The credential was already refreshed; adopt the result returned
	// alongside this decision instead of refreshing again.
	RefreshCoordinationDecision_REFRESH_COORDINATION_DECISION_RESULT_AVAILABLE RefreshCoordinationDecision = 3
)

// Enum value maps for RefreshCoordinationDecision.
var (
	RefreshCoordinationDecision_name = map[int32]string{
		0: "REFRESH_COORDINATION_DECISION_UNSPECIFIED",
		1: "REFRESH_COORDINATION_DECISION_ACQUIRED",
		2: "REFRESH_COORDINATION_DECISION_WAIT",
		3: "REFRESH_COORDINATION_DECISION_RESULT_AVAILABLE",
	}
	RefreshCoordinationDecision_value = map[string]int32{
		"REFRESH_COORDINATION_DECISION_UNSPECIFIED":      0,
		"REFRESH_COORDINATION_DECISION_ACQUIRED":         1,
		"REFRESH_COORDINATION_DECISION_WAIT":             2,
		"REFRESH_COORDINATION_DECISION_RESULT_AVAILABLE": 3,
	}
)

func (x RefreshCoordinationDecision) Enum() *RefreshCoordinationDecision {
	p := new(RefreshCoordinationDecision)
	*p = x
	return p
}

func (x RefreshCoordinationDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshCoordinationDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_enumTypes[0].Descriptor()
}

func (RefreshCoordinationDecision) Type() protoreflect.EnumType {
	return &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_enumTypes[0]
}

func (x RefreshCoordinationDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshCoordinationDecision.Descriptor instead.
func (RefreshCoordinationDecision) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP(), []int{0}
}

type BeginRefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, collision-resistant digest of the refresh credential (e.g. a
	// SHA-256 of the OAuth refresh token). Never the credential itself.
	CredentialHash string `protobuf:"bytes,1,opt,name=credential_hash,json=credentialHash,proto3" json:"credential_hash,omitempty"`
	// How long the acquired lock is held before another caller may steal it.
	// Must comfortably exceed the caller's IdP round-trip timeout, and is
	// bounded so a crashed holder cannot stall waiters for long.
	LockTtlSeconds int64 `protobuf:"varint,2,opt,name=lock_ttl_seconds,json=lockTtlSeconds,proto3" json:"lock_ttl_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeginRefreshRequest) Reset() {
	*x = BeginRefreshRequest{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRefreshRequest) ProtoMessage() {}

func (x *BeginRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRefreshRequest.ProtoReflect.Descriptor instead.
func (*BeginRefreshRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP(), []int{0}
}

func (x *BeginRefreshRequest) GetCredentialHash() string {
	if x != nil {
		return x.CredentialHash
	}
	return ""
}

func (x *BeginRefreshRequest) GetLockTtlSeconds() int64 {
	if x != nil {
		return x.LockTtlSeconds
	}
	return 0
}

type BeginRefreshResponse struct {
	state    protoimpl.MessageState      `protogen:"open.v1"`
	Decision RefreshCoordinationDecision `protobuf:"varint,1,opt,name=decision,proto3,enum=nominal.authorization.internal.v1.RefreshCoordinationDecision" json:"decision,omitempty"`
	// Set iff decision is RESULT_AVAILABLE. Ciphertext produced and consumed
	// exclusively by the caller; opaque to gatekeeper. Not logged.
	EncryptedResult *string `protobuf:"bytes,2,opt,name=encrypted_result,json=encryptedResult,proto3,oneof" json:"encrypted_result,omitempty"`
	// Set iff decision is ACQUIRED. Identifies this acquisition of the lock;
	// pass it to AbandonRefresh so that only the holder can release the lock.
	LockToken     *string `protobuf:"bytes,3,opt,name=lock_token,json=lockToken,proto3,oneof" json:"lock_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRefreshResponse) Reset() {
	*x = BeginRefreshResponse{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRefreshResponse) ProtoMessage() {}

func (x *BeginRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRefreshResponse.ProtoReflect.Descriptor instead.
func (*BeginRefreshResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP(), []int{1}
}

func (x *BeginRefreshResponse) GetDecision() RefreshCoordinationDecision {
	if x != nil {
		return x.Decision
	}
	return RefreshCoordinationDecision_REFRESH_COORDINATION_DECISION_UNSPECIFIED
}

func (x *BeginRefreshResponse) GetEncryptedResult() string {
	if x != nil && x.EncryptedResult != nil {
		return *x.EncryptedResult
	}
	return ""
}

func (x *BeginRefreshResponse) GetLockToken() string {
	if x != nil && x.LockToken != nil {
		return *x.LockToken
	}
	return ""
}

type CompleteRefreshRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialHash string                 `protobuf:"bytes,1,opt,name=credential_hash,json=credentialHash,proto3" json:"credential_hash,omitempty"`
	// Caller-encrypted refresh outcome; opaque to gatekeeper. Not logged.
	EncryptedResult string `protobuf:"bytes,2,opt,name=encrypted_result,json=encryptedResult,proto3" json:"encrypted_result,omitempty"`
	// How long the published result stays adoptable by callers that still
	// hold the consumed credential. Must outlive the window in which a caller
	// can still present the consumed credential. Bounded above by seven days,
	// the Okta-configured refresh token's idle expiration. A result adopted
	// after that time would be unusable.
	ResultTtlSeconds int64 `protobuf:"varint,3,opt,name=result_ttl_seconds,json=resultTtlSeconds,proto3" json:"result_ttl_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteRefreshRequest) Reset() {
	*x = CompleteRefreshRequest{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRefreshRequest) ProtoMessage() {}

func (x *CompleteRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRefreshRequest.ProtoReflect.Descriptor instead.
func (*CompleteRefreshRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteRefreshRequest) GetCredentialHash() string {
	if x != nil {
		return x.CredentialHash
	}
	return ""
}

func (x *CompleteRefreshRequest) GetEncryptedResult() string {
	if x != nil {
		return x.EncryptedResult
	}
	return ""
}

func (x *CompleteRefreshRequest) GetResultTtlSeconds() int64 {
	if x != nil {
		return x.ResultTtlSeconds
	}
	return 0
}

type CompleteRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRefreshResponse) Reset() {
	*x = CompleteRefreshResponse{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRefreshResponse) ProtoMessage() {}

func (x *CompleteRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRefreshResponse.ProtoReflect.Descriptor instead.
func (*CompleteRefreshResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP(), []int{3}
}

type AbandonRefreshRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialHash string                 `protobuf:"bytes,1,opt,name=credential_hash,json=credentialHash,proto3" json:"credential_hash,omitempty"`
	LockToken      string                 `protobuf:"bytes,2,opt,name=lock_token,json=lockToken,proto3" json:"lock_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AbandonRefreshRequest) Reset() {
	*x = AbandonRefreshRequest{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonRefreshRequest) ProtoMessage() {}

func (x *AbandonRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonRefreshRequest.ProtoReflect.Descriptor instead.
func (*AbandonRefreshRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP(), []int{4}
}

func (x *AbandonRefreshRequest) GetCredentialHash() string {
	if x != nil {
		return x.CredentialHash
	}
	return ""
}

func (x *AbandonRefreshRequest) GetLockToken() string {
	if x != nil {
		return x.LockToken
	}
	return ""
}

type AbandonRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonRefreshResponse) Reset() {
	*x = AbandonRefreshResponse{}
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonRefreshResponse) ProtoMessage() {}

func (x *AbandonRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonRefreshResponse.ProtoReflect.Descriptor instead.
func (*AbandonRefreshResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP(), []int{5}
}

var File_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto protoreflect.FileDescriptor

const file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDesc = "" +
	"\n" +
	"Lnominal/protos/authorization/internal/v1/internal_refresh_coordination.proto\x12!nominal.authorization.internal.v1\x1a\x1bbuf/validate/validate.proto\"\x7f\n" +
	"\x13BeginRefreshRequest\x123\n" +
	"\x0fcredential_hash\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x0ecredentialHash\x123\n" +
	"\x10lock_ttl_seconds\x18\x02 \x01(\x03B\t\xbaH\x06\"\x04\x18x(\x05R\x0elockTtlSeconds\"\xea\x01\n" +
	"\x14BeginRefreshResponse\x12Z\n" +
	"\bdecision\x18\x01 \x01(\x0e2>.nominal.authorization.internal.v1.RefreshCoordinationDecisionR\bdecision\x12.\n" +
	"\x10encrypted_result\x18\x02 \x01(\tH\x00R\x0fencryptedResult\x88\x01\x01\x12\"\n" +
	"\n" +
	"lock_token\x18\x03 \x01(\tH\x01R\tlockToken\x88\x01\x01B\x13\n" +
	"\x11_encrypted_resultB\r\n" +
	"\v_lock_token\"\xc0\x01\n" +
	"\x16CompleteRefreshRequest\x123\n" +
	"\x0fcredential_hash\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x0ecredentialHash\x126\n" +
	"\x10encrypted_result\x18\x02 \x01(\tB\v\xbaH\br\x06\x10\x01\x18\x80\x80\x04R\x0fencryptedResult\x129\n" +
	"\x12result_ttl_seconds\x18\x03 \x01(\x03B\v\xbaH\b\"\x06\x18\x80\xf5$(\x1eR\x10resultTtlSeconds\"\x19\n" +
	"\x17CompleteRefreshResponse\"v\n" +
	"\x15AbandonRefreshRequest\x123\n" +
	"\x0fcredential_hash\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x0ecredentialHash\x12(\n" +
	"\n" +
	"lock_token\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\tlockToken\"\x18\n" +
	"\x16AbandonRefreshResponse*\xd4\x01\n" +
	"\x1bRefreshCoordinationDecision\x12-\n" +
	")REFRESH_COORDINATION_DECISION_UNSPECIFIED\x10\x00\x12*\n" +
	"&REFRESH_COORDINATION_DECISION_ACQUIRED\x10\x01\x12&\n" +
	"\"REFRESH_COORDINATION_DECISION_WAIT\x10\x02\x122\n" +
	".REFRESH_COORDINATION_DECISION_RESULT_AVAILABLE\x10\x032\xbf\x03\n" +
	"\"InternalRefreshCoordinationService\x12\x81\x01\n" +
	"\fBeginRefresh\x126.nominal.authorization.internal.v1.BeginRefreshRequest\x1a7.nominal.authorization.internal.v1.BeginRefreshResponse\"\x00\x12\x8a\x01\n" +
	"\x0fCompleteRefresh\x129.nominal.authorization.internal.v1.CompleteRefreshRequest\x1a:.nominal.authorization.internal.v1.CompleteRefreshResponse\"\x00\x12\x87\x01\n" +
	"\x0eAbandonRefresh\x128.nominal.authorization.internal.v1.AbandonRefreshRequest\x1a9.nominal.authorization.internal.v1.AbandonRefreshResponse\"\x00B\xd1\x02\n" +
	"%com.nominal.authorization.internal.v1B InternalRefreshCoordinationProtoP\x01Z_github.com/nominal-io/nominal-api-protos-go/nominal/protos/authorization/internal/v1;internalv1\xa2\x02\x03NAI\xaa\x02!Nominal.Authorization.Internal.V1\xca\x02!Nominal\\Authorization\\Internal\\V1\xe2\x02-Nominal\\Authorization\\Internal\\V1\\GPBMetadata\xea\x02$Nominal::Authorization::Internal::V1b\x06proto3"

var (
	file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescOnce sync.Once
	file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescData []byte
)

func file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescGZIP() []byte {
	file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescOnce.Do(func() {
		file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDesc), len(file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDesc)))
	})
	return file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDescData
}

var file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_goTypes = []any{
	(RefreshCoordinationDecision)(0), // 0: nominal.authorization.internal.v1.RefreshCoordinationDecision
	(*BeginRefreshRequest)(nil),      // 1: nominal.authorization.internal.v1.BeginRefreshRequest
	(*BeginRefreshResponse)(nil),     // 2: nominal.authorization.internal.v1.BeginRefreshResponse
	(*CompleteRefreshRequest)(nil),   // 3: nominal.authorization.internal.v1.CompleteRefreshRequest
	(*CompleteRefreshResponse)(nil),  // 4: nominal.authorization.internal.v1.CompleteRefreshResponse
	(*AbandonRefreshRequest)(nil),    // 5: nominal.authorization.internal.v1.AbandonRefreshRequest
	(*AbandonRefreshResponse)(nil),   // 6: nominal.authorization.internal.v1.AbandonRefreshResponse
}
var file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_depIdxs = []int32{
	0, // 0: nominal.authorization.internal.v1.BeginRefreshResponse.decision:type_name -> nominal.authorization.internal.v1.RefreshCoordinationDecision
	1, // 1: nominal.authorization.internal.v1.InternalRefreshCoordinationService.BeginRefresh:input_type -> nominal.authorization.internal.v1.BeginRefreshRequest
	3, // 2: nominal.authorization.internal.v1.InternalRefreshCoordinationService.CompleteRefresh:input_type -> nominal.authorization.internal.v1.CompleteRefreshRequest
	5, // 3: nominal.authorization.internal.v1.InternalRefreshCoordinationService.AbandonRefresh:input_type -> nominal.authorization.internal.v1.AbandonRefreshRequest
	2, // 4: nominal.authorization.internal.v1.InternalRefreshCoordinationService.BeginRefresh:output_type -> nominal.authorization.internal.v1.BeginRefreshResponse
	4, // 5: nominal.authorization.internal.v1.InternalRefreshCoordinationService.CompleteRefresh:output_type -> nominal.authorization.internal.v1.CompleteRefreshResponse
	6, // 6: nominal.authorization.internal.v1.InternalRefreshCoordinationService.AbandonRefresh:output_type -> nominal.authorization.internal.v1.AbandonRefreshResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_init() }
func file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_init() {
	if File_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto != nil {
		return
	}
	file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDesc), len(file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_goTypes,
		DependencyIndexes: file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_depIdxs,
		EnumInfos:         file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_enumTypes,
		MessageInfos:      file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_msgTypes,
	}.Build()
	File_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto = out.File
	file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_goTypes = nil
	file_nominal_protos_authorization_internal_v1_internal_refresh_coordination_proto_depIdxs = nil
}
