// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/storage/v1/data_deletion.proto

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataDeletionService_DeleteData_FullMethodName              = "/nominal.storage.v1.DataDeletionService/DeleteData"
	DataDeletionService_DeleteChannelWithTags_FullMethodName   = "/nominal.storage.v1.DataDeletionService/DeleteChannelWithTags"
	DataDeletionService_UndeleteChannelWithTags_FullMethodName = "/nominal.storage.v1.DataDeletionService/UndeleteChannelWithTags"
)

// DataDeletionServiceClient is the client API for DataDeletionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Data Deletion Service manages deletion of stored data.
type DataDeletionServiceClient interface {
	// Deprecated: Do not use.
	// Deprecated: This legacy endpoint is unsupported for Iceberg-backed or DUAL datasets, so it may not delete all
	// requested data. Do not use it for new integrations.
	//
	// Deletes stored data. This is an irreversible operation so be careful about specified
	// time range, channel names, and tag scope. requires the user to be an admin for the organization.
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
	// Deletes channels with tags within a data source.
	// Requires DATASOURCE__DELETE_DATA permission on the data source.
	// Deletions are soft — deleted channels with tags are marked for deletion and will eventually be hard deleted.
	// The request will be rejected if there are too many pending deletions for the data source.
	// Throws if the request matches too many channels with tags.
	DeleteChannelWithTags(ctx context.Context, in *DeleteChannelWithTagsRequest, opts ...grpc.CallOption) (*DeleteChannelWithTagsResponse, error)
	// Best effort to undelete channels with tags within a data source.
	// Requires DATASOURCE__DELETE_DATA permission on the data source.
	// The batch size of channels with tags in the request must be <= 1000.
	UndeleteChannelWithTags(ctx context.Context, in *UndeleteChannelWithTagsRequest, opts ...grpc.CallOption) (*UndeleteChannelWithTagsResponse, error)
}

type dataDeletionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataDeletionServiceClient(cc grpc.ClientConnInterface) DataDeletionServiceClient {
	return &dataDeletionServiceClient{cc}
}

// Deprecated: Do not use.
func (c *dataDeletionServiceClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataResponse)
	err := c.cc.Invoke(ctx, DataDeletionService_DeleteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataDeletionServiceClient) DeleteChannelWithTags(ctx context.Context, in *DeleteChannelWithTagsRequest, opts ...grpc.CallOption) (*DeleteChannelWithTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChannelWithTagsResponse)
	err := c.cc.Invoke(ctx, DataDeletionService_DeleteChannelWithTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataDeletionServiceClient) UndeleteChannelWithTags(ctx context.Context, in *UndeleteChannelWithTagsRequest, opts ...grpc.CallOption) (*UndeleteChannelWithTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteChannelWithTagsResponse)
	err := c.cc.Invoke(ctx, DataDeletionService_UndeleteChannelWithTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataDeletionServiceServer is the server API for DataDeletionService service.
// All implementations must embed UnimplementedDataDeletionServiceServer
// for forward compatibility.
//
// Data Deletion Service manages deletion of stored data.
type DataDeletionServiceServer interface {
	// Deprecated: Do not use.
	// Deprecated: This legacy endpoint is unsupported for Iceberg-backed or DUAL datasets, so it may not delete all
	// requested data. Do not use it for new integrations.
	//
	// Deletes stored data. This is an irreversible operation so be careful about specified
	// time range, channel names, and tag scope. requires the user to be an admin for the organization.
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
	// Deletes channels with tags within a data source.
	// Requires DATASOURCE__DELETE_DATA permission on the data source.
	// Deletions are soft — deleted channels with tags are marked for deletion and will eventually be hard deleted.
	// The request will be rejected if there are too many pending deletions for the data source.
	// Throws if the request matches too many channels with tags.
	DeleteChannelWithTags(context.Context, *DeleteChannelWithTagsRequest) (*DeleteChannelWithTagsResponse, error)
	// Best effort to undelete channels with tags within a data source.
	// Requires DATASOURCE__DELETE_DATA permission on the data source.
	// The batch size of channels with tags in the request must be <= 1000.
	UndeleteChannelWithTags(context.Context, *UndeleteChannelWithTagsRequest) (*UndeleteChannelWithTagsResponse, error)
	mustEmbedUnimplementedDataDeletionServiceServer()
}

// UnimplementedDataDeletionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataDeletionServiceServer struct{}

func (UnimplementedDataDeletionServiceServer) DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedDataDeletionServiceServer) DeleteChannelWithTags(context.Context, *DeleteChannelWithTagsRequest) (*DeleteChannelWithTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChannelWithTags not implemented")
}
func (UnimplementedDataDeletionServiceServer) UndeleteChannelWithTags(context.Context, *UndeleteChannelWithTagsRequest) (*UndeleteChannelWithTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndeleteChannelWithTags not implemented")
}
func (UnimplementedDataDeletionServiceServer) mustEmbedUnimplementedDataDeletionServiceServer() {}
func (UnimplementedDataDeletionServiceServer) testEmbeddedByValue()                             {}

// UnsafeDataDeletionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataDeletionServiceServer will
// result in compilation errors.
type UnsafeDataDeletionServiceServer interface {
	mustEmbedUnimplementedDataDeletionServiceServer()
}

func RegisterDataDeletionServiceServer(s grpc.ServiceRegistrar, srv DataDeletionServiceServer) {
	// If the following call panics, it indicates UnimplementedDataDeletionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataDeletionService_ServiceDesc, srv)
}

func _DataDeletionService_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataDeletionServiceServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataDeletionService_DeleteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataDeletionServiceServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataDeletionService_DeleteChannelWithTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChannelWithTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataDeletionServiceServer).DeleteChannelWithTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataDeletionService_DeleteChannelWithTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataDeletionServiceServer).DeleteChannelWithTags(ctx, req.(*DeleteChannelWithTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataDeletionService_UndeleteChannelWithTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteChannelWithTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataDeletionServiceServer).UndeleteChannelWithTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataDeletionService_UndeleteChannelWithTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataDeletionServiceServer).UndeleteChannelWithTags(ctx, req.(*UndeleteChannelWithTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataDeletionService_ServiceDesc is the grpc.ServiceDesc for DataDeletionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataDeletionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.storage.v1.DataDeletionService",
	HandlerType: (*DataDeletionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteData",
			Handler:    _DataDeletionService_DeleteData_Handler,
		},
		{
			MethodName: "DeleteChannelWithTags",
			Handler:    _DataDeletionService_DeleteChannelWithTags_Handler,
		},
		{
			MethodName: "UndeleteChannelWithTags",
			Handler:    _DataDeletionService_UndeleteChannelWithTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/storage/v1/data_deletion.proto",
}
