// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/ai/v1/model_provider_health.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelProviderHealthService_GetProviderStatus_FullMethodName = "/nominal.ai.v1.ModelProviderHealthService/GetProviderStatus"
)

// ModelProviderHealthServiceClient is the client API for ModelProviderHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelProviderHealthService monitors the health and performance of the backing LLM model provider.
// It runs lightweight health checks every 5 minutes to measure provider responsiveness and reliability,
// independent of the complexity of user prompts.
type ModelProviderHealthServiceClient interface {
	// GetProviderStatus returns the current health status of the model provider based on recent health checks.
	// The status is HEALTHY if all checks in the last 30 minutes passed latency thresholds,
	// or DEGRADED if any checks exceeded latency thresholds or failed entirely.
	GetProviderStatus(ctx context.Context, in *GetProviderStatusRequest, opts ...grpc.CallOption) (*GetProviderStatusResponse, error)
}

type modelProviderHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelProviderHealthServiceClient(cc grpc.ClientConnInterface) ModelProviderHealthServiceClient {
	return &modelProviderHealthServiceClient{cc}
}

func (c *modelProviderHealthServiceClient) GetProviderStatus(ctx context.Context, in *GetProviderStatusRequest, opts ...grpc.CallOption) (*GetProviderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderStatusResponse)
	err := c.cc.Invoke(ctx, ModelProviderHealthService_GetProviderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelProviderHealthServiceServer is the server API for ModelProviderHealthService service.
// All implementations must embed UnimplementedModelProviderHealthServiceServer
// for forward compatibility.
//
// ModelProviderHealthService monitors the health and performance of the backing LLM model provider.
// It runs lightweight health checks every 5 minutes to measure provider responsiveness and reliability,
// independent of the complexity of user prompts.
type ModelProviderHealthServiceServer interface {
	// GetProviderStatus returns the current health status of the model provider based on recent health checks.
	// The status is HEALTHY if all checks in the last 30 minutes passed latency thresholds,
	// or DEGRADED if any checks exceeded latency thresholds or failed entirely.
	GetProviderStatus(context.Context, *GetProviderStatusRequest) (*GetProviderStatusResponse, error)
	mustEmbedUnimplementedModelProviderHealthServiceServer()
}

// UnimplementedModelProviderHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelProviderHealthServiceServer struct{}

func (UnimplementedModelProviderHealthServiceServer) GetProviderStatus(context.Context, *GetProviderStatusRequest) (*GetProviderStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderStatus not implemented")
}
func (UnimplementedModelProviderHealthServiceServer) mustEmbedUnimplementedModelProviderHealthServiceServer() {
}
func (UnimplementedModelProviderHealthServiceServer) testEmbeddedByValue() {}

// UnsafeModelProviderHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelProviderHealthServiceServer will
// result in compilation errors.
type UnsafeModelProviderHealthServiceServer interface {
	mustEmbedUnimplementedModelProviderHealthServiceServer()
}

func RegisterModelProviderHealthServiceServer(s grpc.ServiceRegistrar, srv ModelProviderHealthServiceServer) {
	// If the following call panics, it indicates UnimplementedModelProviderHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProviderHealthService_ServiceDesc, srv)
}

func _ModelProviderHealthService_GetProviderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderHealthServiceServer).GetProviderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderHealthService_GetProviderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderHealthServiceServer).GetProviderStatus(ctx, req.(*GetProviderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelProviderHealthService_ServiceDesc is the grpc.ServiceDesc for ModelProviderHealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelProviderHealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.ai.v1.ModelProviderHealthService",
	HandlerType: (*ModelProviderHealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProviderStatus",
			Handler:    _ModelProviderHealthService_GetProviderStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/ai/v1/model_provider_health.proto",
}
