// This proto file was generated from internal-user-creation-api.yml.
// Care should be taken while both files exist to maintain backwards compatibility with the Conjure generated code.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/user_creation/v1/user_creation.proto

package user_creationv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureDatabaseUserExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDatabaseUserExistsRequest) Reset() {
	*x = EnsureDatabaseUserExistsRequest{}
	mi := &file_nominal_protos_user_creation_v1_user_creation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDatabaseUserExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDatabaseUserExistsRequest) ProtoMessage() {}

func (x *EnsureDatabaseUserExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_user_creation_v1_user_creation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDatabaseUserExistsRequest.ProtoReflect.Descriptor instead.
func (*EnsureDatabaseUserExistsRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_user_creation_v1_user_creation_proto_rawDescGZIP(), []int{0}
}

type EnsureDatabaseUserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDatabaseUserExistsResponse) Reset() {
	*x = EnsureDatabaseUserExistsResponse{}
	mi := &file_nominal_protos_user_creation_v1_user_creation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDatabaseUserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDatabaseUserExistsResponse) ProtoMessage() {}

func (x *EnsureDatabaseUserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_user_creation_v1_user_creation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDatabaseUserExistsResponse.ProtoReflect.Descriptor instead.
func (*EnsureDatabaseUserExistsResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_user_creation_v1_user_creation_proto_rawDescGZIP(), []int{1}
}

var File_nominal_protos_user_creation_v1_user_creation_proto protoreflect.FileDescriptor

const file_nominal_protos_user_creation_v1_user_creation_proto_rawDesc = "" +
	"\n" +
	"3nominal/protos/user_creation/v1/user_creation.proto\x12\x18nominal.user_creation.v1\x1a\x1cgoogle/api/annotations.proto\"!\n" +
	"\x1fEnsureDatabaseUserExistsRequest\"\"\n" +
	" EnsureDatabaseUserExistsResponse2\xd8\x01\n" +
	"\x1bInternalUserCreationService\x12\xb8\x01\n" +
	"\x18EnsureDatabaseUserExists\x129.nominal.user_creation.v1.EnsureDatabaseUserExistsRequest\x1a:.nominal.user_creation.v1.EnsureDatabaseUserExistsResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/user-creation/v1/databaseB\x8c\x02\n" +
	"\x1ccom.nominal.user_creation.v1B\x11UserCreationProtoP\x01Z[github.com/nominal-io/nominal-api-protos-go/nominal/protos/user_creation/v1;user_creationv1\xa2\x02\x03NUX\xaa\x02\x17Nominal.UserCreation.V1\xca\x02\x17Nominal\\UserCreation\\V1\xe2\x02#Nominal\\UserCreation\\V1\\GPBMetadata\xea\x02\x19Nominal::UserCreation::V1b\x06proto3"

var (
	file_nominal_protos_user_creation_v1_user_creation_proto_rawDescOnce sync.Once
	file_nominal_protos_user_creation_v1_user_creation_proto_rawDescData []byte
)

func file_nominal_protos_user_creation_v1_user_creation_proto_rawDescGZIP() []byte {
	file_nominal_protos_user_creation_v1_user_creation_proto_rawDescOnce.Do(func() {
		file_nominal_protos_user_creation_v1_user_creation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_user_creation_v1_user_creation_proto_rawDesc), len(file_nominal_protos_user_creation_v1_user_creation_proto_rawDesc)))
	})
	return file_nominal_protos_user_creation_v1_user_creation_proto_rawDescData
}

var file_nominal_protos_user_creation_v1_user_creation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nominal_protos_user_creation_v1_user_creation_proto_goTypes = []any{
	(*EnsureDatabaseUserExistsRequest)(nil),  // 0: nominal.user_creation.v1.EnsureDatabaseUserExistsRequest
	(*EnsureDatabaseUserExistsResponse)(nil), // 1: nominal.user_creation.v1.EnsureDatabaseUserExistsResponse
}
var file_nominal_protos_user_creation_v1_user_creation_proto_depIdxs = []int32{
	0, // 0: nominal.user_creation.v1.InternalUserCreationService.EnsureDatabaseUserExists:input_type -> nominal.user_creation.v1.EnsureDatabaseUserExistsRequest
	1, // 1: nominal.user_creation.v1.InternalUserCreationService.EnsureDatabaseUserExists:output_type -> nominal.user_creation.v1.EnsureDatabaseUserExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nominal_protos_user_creation_v1_user_creation_proto_init() }
func file_nominal_protos_user_creation_v1_user_creation_proto_init() {
	if File_nominal_protos_user_creation_v1_user_creation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_user_creation_v1_user_creation_proto_rawDesc), len(file_nominal_protos_user_creation_v1_user_creation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_user_creation_v1_user_creation_proto_goTypes,
		DependencyIndexes: file_nominal_protos_user_creation_v1_user_creation_proto_depIdxs,
		MessageInfos:      file_nominal_protos_user_creation_v1_user_creation_proto_msgTypes,
	}.Build()
	File_nominal_protos_user_creation_v1_user_creation_proto = out.File
	file_nominal_protos_user_creation_v1_user_creation_proto_goTypes = nil
	file_nominal_protos_user_creation_v1_user_creation_proto_depIdxs = nil
}
