// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/authorization/resources/v1/resource_shares.proto

package resourcesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Roles that can be granted for a resource share.
type ResourceShareRole int32

const (
	ResourceShareRole_RESOURCE_SHARE_ROLE_UNSPECIFIED ResourceShareRole = 0
	ResourceShareRole_RESOURCE_SHARE_ROLE_VIEWER      ResourceShareRole = 1
)

// Enum value maps for ResourceShareRole.
var (
	ResourceShareRole_name = map[int32]string{
		0: "RESOURCE_SHARE_ROLE_UNSPECIFIED",
		1: "RESOURCE_SHARE_ROLE_VIEWER",
	}
	ResourceShareRole_value = map[string]int32{
		"RESOURCE_SHARE_ROLE_UNSPECIFIED": 0,
		"RESOURCE_SHARE_ROLE_VIEWER":      1,
	}
)

func (x ResourceShareRole) Enum() *ResourceShareRole {
	p := new(ResourceShareRole)
	*p = x
	return p
}

func (x ResourceShareRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceShareRole) Descriptor() protoreflect.EnumDescriptor {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_enumTypes[0].Descriptor()
}

func (ResourceShareRole) Type() protoreflect.EnumType {
	return &file_nominal_protos_authorization_resources_v1_resource_shares_proto_enumTypes[0]
}

func (x ResourceShareRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceShareRole.Descriptor instead.
func (ResourceShareRole) EnumDescriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{0}
}

// Client-known identity of a resource share.
type ResourceShareKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RID of the workbook being shared. Only workbook RIDs are currently supported.
	ResourceRid string `protobuf:"bytes,1,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	// Required. Must be a declared role other than RESOURCE_SHARE_ROLE_UNSPECIFIED.
	Role          ResourceShareRole `protobuf:"varint,2,opt,name=role,proto3,enum=nominal.authorization.resources.v1.ResourceShareRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceShareKey) Reset() {
	*x = ResourceShareKey{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceShareKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceShareKey) ProtoMessage() {}

func (x *ResourceShareKey) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceShareKey.ProtoReflect.Descriptor instead.
func (*ResourceShareKey) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceShareKey) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

func (x *ResourceShareKey) GetRole() ResourceShareRole {
	if x != nil {
		return x.Role
	}
	return ResourceShareRole_RESOURCE_SHARE_ROLE_UNSPECIFIED
}

// A share definition for a resource and role.
type ResourceShare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *ResourceShareKey      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Subjects that receive the share, up to 1000. An empty list removes all subjects from an existing share.
	Subjects []*ResourceShare_ShareSubject `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Related resources that receive grants inferred from this resource share. At most 1000 resources of each type
	// receive grants; when more are resolved, the resources with the lowest lexicographic RIDs are selected.
	RelatedGrants *ResourceShare_RelatedResourceGrants `protobuf:"bytes,3,opt,name=related_grants,json=relatedGrants,proto3" json:"related_grants,omitempty"`
	// User that most recently created or updated the share.
	LastUpdatedBy string                 `protobuf:"bytes,4,opt,name=last_updated_by,json=lastUpdatedBy,proto3" json:"last_updated_by,omitempty"`
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceShare) Reset() {
	*x = ResourceShare{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceShare) ProtoMessage() {}

func (x *ResourceShare) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceShare.ProtoReflect.Descriptor instead.
func (*ResourceShare) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceShare) GetKey() *ResourceShareKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ResourceShare) GetSubjects() []*ResourceShare_ShareSubject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *ResourceShare) GetRelatedGrants() *ResourceShare_RelatedResourceGrants {
	if x != nil {
		return x.RelatedGrants
	}
	return nil
}

func (x *ResourceShare) GetLastUpdatedBy() string {
	if x != nil {
		return x.LastUpdatedBy
	}
	return ""
}

func (x *ResourceShare) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

type RunGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunGrant) Reset() {
	*x = RunGrant{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunGrant) ProtoMessage() {}

func (x *RunGrant) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunGrant.ProtoReflect.Descriptor instead.
func (*RunGrant) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{2}
}

func (x *RunGrant) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type AssetGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetGrant) Reset() {
	*x = AssetGrant{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetGrant) ProtoMessage() {}

func (x *AssetGrant) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetGrant.ProtoReflect.Descriptor instead.
func (*AssetGrant) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{3}
}

func (x *AssetGrant) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type DatasourceGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceGrant) Reset() {
	*x = DatasourceGrant{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceGrant) ProtoMessage() {}

func (x *DatasourceGrant) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceGrant.ProtoReflect.Descriptor instead.
func (*DatasourceGrant) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{4}
}

func (x *DatasourceGrant) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type CreateResourceShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceShare *ResourceShare         `protobuf:"bytes,1,opt,name=resource_share,json=resourceShare,proto3" json:"resource_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceShareRequest) Reset() {
	*x = CreateResourceShareRequest{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceShareRequest) ProtoMessage() {}

func (x *CreateResourceShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceShareRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceShareRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResourceShareRequest) GetResourceShare() *ResourceShare {
	if x != nil {
		return x.ResourceShare
	}
	return nil
}

type CreateResourceShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceShare *ResourceShare         `protobuf:"bytes,1,opt,name=resource_share,json=resourceShare,proto3" json:"resource_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceShareResponse) Reset() {
	*x = CreateResourceShareResponse{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceShareResponse) ProtoMessage() {}

func (x *CreateResourceShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceShareResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceShareResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResourceShareResponse) GetResourceShare() *ResourceShare {
	if x != nil {
		return x.ResourceShare
	}
	return nil
}

type BatchGetResourceSharesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource-share keys to get, up to 1000.
	Keys          []*ResourceShareKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResourceSharesRequest) Reset() {
	*x = BatchGetResourceSharesRequest{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResourceSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResourceSharesRequest) ProtoMessage() {}

func (x *BatchGetResourceSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResourceSharesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetResourceSharesRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetResourceSharesRequest) GetKeys() []*ResourceShareKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetResourceSharesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource shares in request order. Duplicate request keys produce duplicate entries.
	ResourceShares []*ResourceShare `protobuf:"bytes,1,rep,name=resource_shares,json=resourceShares,proto3" json:"resource_shares,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchGetResourceSharesResponse) Reset() {
	*x = BatchGetResourceSharesResponse{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResourceSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResourceSharesResponse) ProtoMessage() {}

func (x *BatchGetResourceSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResourceSharesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResourceSharesResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetResourceSharesResponse) GetResourceShares() []*ResourceShare {
	if x != nil {
		return x.ResourceShares
	}
	return nil
}

type ListResourceSharesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RID of the workbook whose shares are listed. Only workbook RIDs are currently supported.
	ResourceRid string `protobuf:"bytes,1,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	// Maximum number of shares to return. Zero selects the default of 100; values above 1000 are rejected.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Token returned by a previous ListResourceShares call.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceSharesRequest) Reset() {
	*x = ListResourceSharesRequest{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceSharesRequest) ProtoMessage() {}

func (x *ListResourceSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceSharesRequest.ProtoReflect.Descriptor instead.
func (*ListResourceSharesRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{9}
}

func (x *ListResourceSharesRequest) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

func (x *ListResourceSharesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResourceSharesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResourceSharesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceShares []*ResourceShare       `protobuf:"bytes,1,rep,name=resource_shares,json=resourceShares,proto3" json:"resource_shares,omitempty"`
	NextPageToken  string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListResourceSharesResponse) Reset() {
	*x = ListResourceSharesResponse{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceSharesResponse) ProtoMessage() {}

func (x *ListResourceSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceSharesResponse.ProtoReflect.Descriptor instead.
func (*ListResourceSharesResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{10}
}

func (x *ListResourceSharesResponse) GetResourceShares() []*ResourceShare {
	if x != nil {
		return x.ResourceShares
	}
	return nil
}

func (x *ListResourceSharesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteResourceShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *ResourceShareKey      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceShareRequest) Reset() {
	*x = DeleteResourceShareRequest{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceShareRequest) ProtoMessage() {}

func (x *DeleteResourceShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceShareRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceShareRequest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResourceShareRequest) GetKey() *ResourceShareKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResourceShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceShareResponse) Reset() {
	*x = DeleteResourceShareResponse{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceShareResponse) ProtoMessage() {}

func (x *DeleteResourceShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceShareResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceShareResponse) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{12}
}

type ResourceShare_ShareSubject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Subject:
	//
	//	*ResourceShare_ShareSubject_UserRid
	Subject       isResourceShare_ShareSubject_Subject `protobuf_oneof:"subject"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceShare_ShareSubject) Reset() {
	*x = ResourceShare_ShareSubject{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceShare_ShareSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceShare_ShareSubject) ProtoMessage() {}

func (x *ResourceShare_ShareSubject) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceShare_ShareSubject.ProtoReflect.Descriptor instead.
func (*ResourceShare_ShareSubject) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResourceShare_ShareSubject) GetSubject() isResourceShare_ShareSubject_Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ResourceShare_ShareSubject) GetUserRid() string {
	if x != nil {
		if x, ok := x.Subject.(*ResourceShare_ShareSubject_UserRid); ok {
			return x.UserRid
		}
	}
	return ""
}

type isResourceShare_ShareSubject_Subject interface {
	isResourceShare_ShareSubject_Subject()
}

type ResourceShare_ShareSubject_UserRid struct {
	UserRid string `protobuf:"bytes,1,opt,name=user_rid,json=userRid,proto3,oneof"`
}

func (*ResourceShare_ShareSubject_UserRid) isResourceShare_ShareSubject_Subject() {}

type ResourceShare_RelatedResourceGrants struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Run grants, up to 1000.
	RunGrants []*RunGrant `protobuf:"bytes,1,rep,name=run_grants,json=runGrants,proto3" json:"run_grants,omitempty"`
	// Asset grants, up to 1000.
	AssetGrants []*AssetGrant `protobuf:"bytes,2,rep,name=asset_grants,json=assetGrants,proto3" json:"asset_grants,omitempty"`
	// Datasource grants, up to 1000.
	DatasourceGrants []*DatasourceGrant `protobuf:"bytes,3,rep,name=datasource_grants,json=datasourceGrants,proto3" json:"datasource_grants,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceShare_RelatedResourceGrants) Reset() {
	*x = ResourceShare_RelatedResourceGrants{}
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceShare_RelatedResourceGrants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceShare_RelatedResourceGrants) ProtoMessage() {}

func (x *ResourceShare_RelatedResourceGrants) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceShare_RelatedResourceGrants.ProtoReflect.Descriptor instead.
func (*ResourceShare_RelatedResourceGrants) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ResourceShare_RelatedResourceGrants) GetRunGrants() []*RunGrant {
	if x != nil {
		return x.RunGrants
	}
	return nil
}

func (x *ResourceShare_RelatedResourceGrants) GetAssetGrants() []*AssetGrant {
	if x != nil {
		return x.AssetGrants
	}
	return nil
}

func (x *ResourceShare_RelatedResourceGrants) GetDatasourceGrants() []*DatasourceGrant {
	if x != nil {
		return x.DatasourceGrants
	}
	return nil
}

var File_nominal_protos_authorization_resources_v1_resource_shares_proto protoreflect.FileDescriptor

const file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDesc = "" +
	"\n" +
	"?nominal/protos/authorization/resources/v1/resource_shares.proto\x12\"nominal.authorization.resources.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!nominal/protos/gen/v1/alias.proto\"\xc7\x01\n" +
	"\x10ResourceShareKey\x12Y\n" +
	"\fresource_rid\x18\x01 \x01(\tB6\xe0A\x05\xbaH\b\xc8\x01\x01r\x03\x18\x80\x02\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\vresourceRid\x12X\n" +
	"\x04role\x18\x02 \x01(\x0e25.nominal.authorization.resources.v1.ResourceShareRoleB\r\xe0A\x05\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04role\"\x9a\a\n" +
	"\rResourceShare\x12Q\n" +
	"\x03key\x18\x01 \x01(\v24.nominal.authorization.resources.v1.ResourceShareKeyB\t\xe0A\x05\xbaH\x03\xc8\x01\x01R\x03key\x12e\n" +
	"\bsubjects\x18\x02 \x03(\v2>.nominal.authorization.resources.v1.ResourceShare.ShareSubjectB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\bsubjects\x12s\n" +
	"\x0erelated_grants\x18\x03 \x01(\v2G.nominal.authorization.resources.v1.ResourceShare.RelatedResourceGrantsB\x03\xe0A\x03R\rrelatedGrants\x12^\n" +
	"\x0flast_updated_by\x18\x04 \x01(\tB6\xe0A\x03\xbaH\x05r\x03\x18\x80\x02\x9a\xb2\x1a'\n" +
	"%io.nominal.authentication.api.UserRidR\rlastUpdatedBy\x12G\n" +
	"\x0flast_updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\rlastUpdatedAt\x1at\n" +
	"\fShareSubject\x12R\n" +
	"\buser_rid\x18\x01 \x01(\tB5\xbaH\ar\x05\x10\x01\x18\x80\x02\x9a\xb2\x1a'\n" +
	"%io.nominal.authentication.api.UserRidH\x00R\auserRidB\x10\n" +
	"\asubject\x12\x05\xbaH\x02\b\x01\x1a\xba\x02\n" +
	"\x15RelatedResourceGrants\x12V\n" +
	"\n" +
	"run_grants\x18\x01 \x03(\v2,.nominal.authorization.resources.v1.RunGrantB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\trunGrants\x12\\\n" +
	"\fasset_grants\x18\x02 \x03(\v2..nominal.authorization.resources.v1.AssetGrantB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\vassetGrants\x12k\n" +
	"\x11datasource_grants\x18\x03 \x03(\v23.nominal.authorization.resources.v1.DatasourceGrantB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\x10datasourceGrants\"N\n" +
	"\bRunGrant\x12B\n" +
	"\x03rid\x18\x01 \x01(\tB0\xbaH\b\xc8\x01\x01r\x03\x18\x80\x02\x9a\xb2\x1a!\n" +
	"\x1fio.nominal.scout.run.api.RunRidR\x03rid\"S\n" +
	"\n" +
	"AssetGrant\x12E\n" +
	"\x03rid\x18\x01 \x01(\tB3\xbaH\b\xc8\x01\x01r\x03\x18\x80\x02\x9a\xb2\x1a$\n" +
	"\"io.nominal.scout.rids.api.AssetRidR\x03rid\"g\n" +
	"\x0fDatasourceGrant\x12T\n" +
	"\x03rid\x18\x01 \x01(\tBB\xbaH\b\xc8\x01\x01r\x03\x18\x80\x02\x9a\xb2\x1a3\n" +
	"1io.nominal.api.rids.NominalDataSourceOrDatasetRidR\x03rid\"~\n" +
	"\x1aCreateResourceShareRequest\x12`\n" +
	"\x0eresource_share\x18\x01 \x01(\v21.nominal.authorization.resources.v1.ResourceShareB\x06\xbaH\x03\xc8\x01\x01R\rresourceShare\"\x7f\n" +
	"\x1bCreateResourceShareResponse\x12`\n" +
	"\x0eresource_share\x18\x01 \x01(\v21.nominal.authorization.resources.v1.ResourceShareB\x06\xbaH\x03\xc8\x01\x01R\rresourceShare\"v\n" +
	"\x1dBatchGetResourceSharesRequest\x12U\n" +
	"\x04keys\x18\x01 \x03(\v24.nominal.authorization.resources.v1.ResourceShareKeyB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x04keys\"\x87\x01\n" +
	"\x1eBatchGetResourceSharesResponse\x12e\n" +
	"\x0fresource_shares\x18\x01 \x03(\v21.nominal.authorization.resources.v1.ResourceShareB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\x0eresourceShares\"\xdf\x01\n" +
	"\x19ListResourceSharesRequest\x12V\n" +
	"\fresource_rid\x18\x01 \x01(\tB3\xbaH\b\xc8\x01\x01r\x03\x18\x80\x02\x9a\xb2\x1a$\n" +
	"\"com.palantir.ri.ResourceIdentifierR\vresourceRid\x12'\n" +
	"\tpage_size\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12A\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\"\xbaH\x05r\x03\x18\x80\x10\x9a\xb2\x1a\x16\n" +
	"\x14io.nominal.api.TokenR\tpageToken\"\xcf\x01\n" +
	"\x1aListResourceSharesResponse\x12e\n" +
	"\x0fresource_shares\x18\x01 \x03(\v21.nominal.authorization.resources.v1.ResourceShareB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\x0eresourceShares\x12J\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\"\xbaH\x05r\x03\x18\x80\x10\x9a\xb2\x1a\x16\n" +
	"\x14io.nominal.api.TokenR\rnextPageToken\"l\n" +
	"\x1aDeleteResourceShareRequest\x12N\n" +
	"\x03key\x18\x01 \x01(\v24.nominal.authorization.resources.v1.ResourceShareKeyB\x06\xbaH\x03\xc8\x01\x01R\x03key\"\x1d\n" +
	"\x1bDeleteResourceShareResponse*X\n" +
	"\x11ResourceShareRole\x12#\n" +
	"\x1fRESOURCE_SHARE_ROLE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRESOURCE_SHARE_ROLE_VIEWER\x10\x012\x9c\a\n" +
	"\x14ResourceShareService\x12\xf4\x01\n" +
	"\x13CreateResourceShare\x12>.nominal.authorization.resources.v1.CreateResourceShareRequest\x1a?.nominal.authorization.resources.v1.CreateResourceShareResponse\"\\\x82\xd3\xe4\x93\x02V:\x0eresource_share\"D/authorization/resources/v1/{resource_share.key.resource_rid}/shares\x12\xd8\x01\n" +
	"\x16BatchGetResourceShares\x12A.nominal.authorization.resources.v1.BatchGetResourceSharesRequest\x1aB.nominal.authorization.resources.v1.BatchGetResourceSharesResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/authorization/resources/v1/shares/batch-get\x12\xce\x01\n" +
	"\x12ListResourceShares\x12=.nominal.authorization.resources.v1.ListResourceSharesRequest\x1a>.nominal.authorization.resources.v1.ListResourceSharesResponse\"9\x82\xd3\xe4\x93\x023\x121/authorization/resources/v1/{resource_rid}/shares\x12\xe0\x01\n" +
	"\x13DeleteResourceShare\x12>.nominal.authorization.resources.v1.DeleteResourceShareRequest\x1a?.nominal.authorization.resources.v1.DeleteResourceShareResponse\"H\x82\xd3\xe4\x93\x02B*@/authorization/resources/v1/{key.resource_rid}/shares/{key.role}B\xcb\x02\n" +
	"&com.nominal.authorization.resources.v1B\x13ResourceSharesProtoP\x01Zagithub.com/nominal-io/nominal-api-protos-go/nominal/protos/authorization/resources/v1;resourcesv1\xa2\x02\x03NAR\xaa\x02\"Nominal.Authorization.Resources.V1\xca\x02\"Nominal\\Authorization\\Resources\\V1\xe2\x02.Nominal\\Authorization\\Resources\\V1\\GPBMetadata\xea\x02%Nominal::Authorization::Resources::V1b\x06proto3"

var (
	file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescOnce sync.Once
	file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescData []byte
)

func file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescGZIP() []byte {
	file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescOnce.Do(func() {
		file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDesc), len(file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDesc)))
	})
	return file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDescData
}

var file_nominal_protos_authorization_resources_v1_resource_shares_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nominal_protos_authorization_resources_v1_resource_shares_proto_goTypes = []any{
	(ResourceShareRole)(0),                      // 0: nominal.authorization.resources.v1.ResourceShareRole
	(*ResourceShareKey)(nil),                    // 1: nominal.authorization.resources.v1.ResourceShareKey
	(*ResourceShare)(nil),                       // 2: nominal.authorization.resources.v1.ResourceShare
	(*RunGrant)(nil),                            // 3: nominal.authorization.resources.v1.RunGrant
	(*AssetGrant)(nil),                          // 4: nominal.authorization.resources.v1.AssetGrant
	(*DatasourceGrant)(nil),                     // 5: nominal.authorization.resources.v1.DatasourceGrant
	(*CreateResourceShareRequest)(nil),          // 6: nominal.authorization.resources.v1.CreateResourceShareRequest
	(*CreateResourceShareResponse)(nil),         // 7: nominal.authorization.resources.v1.CreateResourceShareResponse
	(*BatchGetResourceSharesRequest)(nil),       // 8: nominal.authorization.resources.v1.BatchGetResourceSharesRequest
	(*BatchGetResourceSharesResponse)(nil),      // 9: nominal.authorization.resources.v1.BatchGetResourceSharesResponse
	(*ListResourceSharesRequest)(nil),           // 10: nominal.authorization.resources.v1.ListResourceSharesRequest
	(*ListResourceSharesResponse)(nil),          // 11: nominal.authorization.resources.v1.ListResourceSharesResponse
	(*DeleteResourceShareRequest)(nil),          // 12: nominal.authorization.resources.v1.DeleteResourceShareRequest
	(*DeleteResourceShareResponse)(nil),         // 13: nominal.authorization.resources.v1.DeleteResourceShareResponse
	(*ResourceShare_ShareSubject)(nil),          // 14: nominal.authorization.resources.v1.ResourceShare.ShareSubject
	(*ResourceShare_RelatedResourceGrants)(nil), // 15: nominal.authorization.resources.v1.ResourceShare.RelatedResourceGrants
	(*timestamppb.Timestamp)(nil),               // 16: google.protobuf.Timestamp
}
var file_nominal_protos_authorization_resources_v1_resource_shares_proto_depIdxs = []int32{
	0,  // 0: nominal.authorization.resources.v1.ResourceShareKey.role:type_name -> nominal.authorization.resources.v1.ResourceShareRole
	1,  // 1: nominal.authorization.resources.v1.ResourceShare.key:type_name -> nominal.authorization.resources.v1.ResourceShareKey
	14, // 2: nominal.authorization.resources.v1.ResourceShare.subjects:type_name -> nominal.authorization.resources.v1.ResourceShare.ShareSubject
	15, // 3: nominal.authorization.resources.v1.ResourceShare.related_grants:type_name -> nominal.authorization.resources.v1.ResourceShare.RelatedResourceGrants
	16, // 4: nominal.authorization.resources.v1.ResourceShare.last_updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: nominal.authorization.resources.v1.CreateResourceShareRequest.resource_share:type_name -> nominal.authorization.resources.v1.ResourceShare
	2,  // 6: nominal.authorization.resources.v1.CreateResourceShareResponse.resource_share:type_name -> nominal.authorization.resources.v1.ResourceShare
	1,  // 7: nominal.authorization.resources.v1.BatchGetResourceSharesRequest.keys:type_name -> nominal.authorization.resources.v1.ResourceShareKey
	2,  // 8: nominal.authorization.resources.v1.BatchGetResourceSharesResponse.resource_shares:type_name -> nominal.authorization.resources.v1.ResourceShare
	2,  // 9: nominal.authorization.resources.v1.ListResourceSharesResponse.resource_shares:type_name -> nominal.authorization.resources.v1.ResourceShare
	1,  // 10: nominal.authorization.resources.v1.DeleteResourceShareRequest.key:type_name -> nominal.authorization.resources.v1.ResourceShareKey
	3,  // 11: nominal.authorization.resources.v1.ResourceShare.RelatedResourceGrants.run_grants:type_name -> nominal.authorization.resources.v1.RunGrant
	4,  // 12: nominal.authorization.resources.v1.ResourceShare.RelatedResourceGrants.asset_grants:type_name -> nominal.authorization.resources.v1.AssetGrant
	5,  // 13: nominal.authorization.resources.v1.ResourceShare.RelatedResourceGrants.datasource_grants:type_name -> nominal.authorization.resources.v1.DatasourceGrant
	6,  // 14: nominal.authorization.resources.v1.ResourceShareService.CreateResourceShare:input_type -> nominal.authorization.resources.v1.CreateResourceShareRequest
	8,  // 15: nominal.authorization.resources.v1.ResourceShareService.BatchGetResourceShares:input_type -> nominal.authorization.resources.v1.BatchGetResourceSharesRequest
	10, // 16: nominal.authorization.resources.v1.ResourceShareService.ListResourceShares:input_type -> nominal.authorization.resources.v1.ListResourceSharesRequest
	12, // 17: nominal.authorization.resources.v1.ResourceShareService.DeleteResourceShare:input_type -> nominal.authorization.resources.v1.DeleteResourceShareRequest
	7,  // 18: nominal.authorization.resources.v1.ResourceShareService.CreateResourceShare:output_type -> nominal.authorization.resources.v1.CreateResourceShareResponse
	9,  // 19: nominal.authorization.resources.v1.ResourceShareService.BatchGetResourceShares:output_type -> nominal.authorization.resources.v1.BatchGetResourceSharesResponse
	11, // 20: nominal.authorization.resources.v1.ResourceShareService.ListResourceShares:output_type -> nominal.authorization.resources.v1.ListResourceSharesResponse
	13, // 21: nominal.authorization.resources.v1.ResourceShareService.DeleteResourceShare:output_type -> nominal.authorization.resources.v1.DeleteResourceShareResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_nominal_protos_authorization_resources_v1_resource_shares_proto_init() }
func file_nominal_protos_authorization_resources_v1_resource_shares_proto_init() {
	if File_nominal_protos_authorization_resources_v1_resource_shares_proto != nil {
		return
	}
	file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes[13].OneofWrappers = []any{
		(*ResourceShare_ShareSubject_UserRid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDesc), len(file_nominal_protos_authorization_resources_v1_resource_shares_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nominal_protos_authorization_resources_v1_resource_shares_proto_goTypes,
		DependencyIndexes: file_nominal_protos_authorization_resources_v1_resource_shares_proto_depIdxs,
		EnumInfos:         file_nominal_protos_authorization_resources_v1_resource_shares_proto_enumTypes,
		MessageInfos:      file_nominal_protos_authorization_resources_v1_resource_shares_proto_msgTypes,
	}.Build()
	File_nominal_protos_authorization_resources_v1_resource_shares_proto = out.File
	file_nominal_protos_authorization_resources_v1_resource_shares_proto_goTypes = nil
	file_nominal_protos_authorization_resources_v1_resource_shares_proto_depIdxs = nil
}
