// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/mesh/v1/mesh.proto

package meshv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshService_Mesh_FullMethodName                   = "/nominal.mesh.v1.MeshService/Mesh"
	MeshService_HealthCheck_FullMethodName            = "/nominal.mesh.v1.MeshService/HealthCheck"
	MeshService_CreateLink_FullMethodName             = "/nominal.mesh.v1.MeshService/CreateLink"
	MeshService_GetLink_FullMethodName                = "/nominal.mesh.v1.MeshService/GetLink"
	MeshService_UpdateLink_FullMethodName             = "/nominal.mesh.v1.MeshService/UpdateLink"
	MeshService_DeleteLink_FullMethodName             = "/nominal.mesh.v1.MeshService/DeleteLink"
	MeshService_SearchLinks_FullMethodName            = "/nominal.mesh.v1.MeshService/SearchLinks"
	MeshService_CreateRemoteConnection_FullMethodName = "/nominal.mesh.v1.MeshService/CreateRemoteConnection"
	MeshService_GetRemoteConnection_FullMethodName    = "/nominal.mesh.v1.MeshService/GetRemoteConnection"
	MeshService_UpdateRemoteConnection_FullMethodName = "/nominal.mesh.v1.MeshService/UpdateRemoteConnection"
	MeshService_DeleteRemoteConnection_FullMethodName = "/nominal.mesh.v1.MeshService/DeleteRemoteConnection"
	MeshService_ListRemoteConnections_FullMethodName  = "/nominal.mesh.v1.MeshService/ListRemoteConnections"
)

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Manages mesh links between local and remote environments.
type MeshServiceClient interface {
	// Core Mesh operations.
	// ------------------------------------------------------------------------------------------------------------
	// Used to mesh resources between stacks.
	Mesh(ctx context.Context, in *MeshRequest, opts ...grpc.CallOption) (*MeshResponse, error)
	// Used to determine the health of a stack and its availability for meshing.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Link operations.
	// ------------------------------------------------------------------------------------------------------------
	// Creates a link which allows the specified resource to be synced between mesh environments.
	// Throws MESH_SERVICE_ERROR_LINK_ALREADY_EXISTS if a link already exists.
	CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error)
	// Retrieves a link for the requested resource, throwing MESH_SERVICE_ERROR_LINK_NOT_FOUND if there is no link.
	GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*GetLinkResponse, error)
	// Updates a link for the requested resource, throwing MESH_SERVICE_ERROR_LINK_NOT_FOUND if there is no link.
	UpdateLink(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error)
	// Deletes a link for the specified resource.
	DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error)
	// Searches for links with optional filters and pagination.
	SearchLinks(ctx context.Context, in *SearchLinksRequest, opts ...grpc.CallOption) (*SearchLinksResponse, error)
	// Remote Connection operations.
	// ------------------------------------------------------------------------------------------------------------
	// Creates a remote connection for mesh links.
	// Throws MESH_SERVICE_ERROR_REMOTE_CONNECTION_ALREADY_EXISTS if a remote connection with the same name already exists.
	CreateRemoteConnection(ctx context.Context, in *CreateRemoteConnectionRequest, opts ...grpc.CallOption) (*CreateRemoteConnectionResponse, error)
	// Retrieves a remote connection by RID.
	// Throws MESH_SERVICE_ERROR_REMOTE_CONNECTION_NOT_FOUND if there is no remote connection.
	GetRemoteConnection(ctx context.Context, in *GetRemoteConnectionRequest, opts ...grpc.CallOption) (*GetRemoteConnectionResponse, error)
	// Updates a remote connection by RID.
	// Throws MESH_SERVICE_ERROR_REMOTE_CONNECTION_NOT_FOUND if there is no remote connection.
	UpdateRemoteConnection(ctx context.Context, in *UpdateRemoteConnectionRequest, opts ...grpc.CallOption) (*UpdateRemoteConnectionResponse, error)
	// Deletes a remote connection by RID.
	DeleteRemoteConnection(ctx context.Context, in *DeleteRemoteConnectionRequest, opts ...grpc.CallOption) (*DeleteRemoteConnectionResponse, error)
	// Lists all remote connections.
	ListRemoteConnections(ctx context.Context, in *ListRemoteConnectionsRequest, opts ...grpc.CallOption) (*ListRemoteConnectionsResponse, error)
}

type meshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshServiceClient(cc grpc.ClientConnInterface) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) Mesh(ctx context.Context, in *MeshRequest, opts ...grpc.CallOption) (*MeshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeshResponse)
	err := c.cc.Invoke(ctx, MeshService_Mesh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MeshService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLinkResponse)
	err := c.cc.Invoke(ctx, MeshService_CreateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*GetLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLinkResponse)
	err := c.cc.Invoke(ctx, MeshService_GetLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) UpdateLink(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLinkResponse)
	err := c.cc.Invoke(ctx, MeshService_UpdateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLinkResponse)
	err := c.cc.Invoke(ctx, MeshService_DeleteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) SearchLinks(ctx context.Context, in *SearchLinksRequest, opts ...grpc.CallOption) (*SearchLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLinksResponse)
	err := c.cc.Invoke(ctx, MeshService_SearchLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) CreateRemoteConnection(ctx context.Context, in *CreateRemoteConnectionRequest, opts ...grpc.CallOption) (*CreateRemoteConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRemoteConnectionResponse)
	err := c.cc.Invoke(ctx, MeshService_CreateRemoteConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) GetRemoteConnection(ctx context.Context, in *GetRemoteConnectionRequest, opts ...grpc.CallOption) (*GetRemoteConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRemoteConnectionResponse)
	err := c.cc.Invoke(ctx, MeshService_GetRemoteConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) UpdateRemoteConnection(ctx context.Context, in *UpdateRemoteConnectionRequest, opts ...grpc.CallOption) (*UpdateRemoteConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRemoteConnectionResponse)
	err := c.cc.Invoke(ctx, MeshService_UpdateRemoteConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) DeleteRemoteConnection(ctx context.Context, in *DeleteRemoteConnectionRequest, opts ...grpc.CallOption) (*DeleteRemoteConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRemoteConnectionResponse)
	err := c.cc.Invoke(ctx, MeshService_DeleteRemoteConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) ListRemoteConnections(ctx context.Context, in *ListRemoteConnectionsRequest, opts ...grpc.CallOption) (*ListRemoteConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRemoteConnectionsResponse)
	err := c.cc.Invoke(ctx, MeshService_ListRemoteConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServiceServer is the server API for MeshService service.
// All implementations must embed UnimplementedMeshServiceServer
// for forward compatibility.
//
// Manages mesh links between local and remote environments.
type MeshServiceServer interface {
	// Core Mesh operations.
	// ------------------------------------------------------------------------------------------------------------
	// Used to mesh resources between stacks.
	Mesh(context.Context, *MeshRequest) (*MeshResponse, error)
	// Used to determine the health of a stack and its availability for meshing.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Link operations.
	// ------------------------------------------------------------------------------------------------------------
	// Creates a link which allows the specified resource to be synced between mesh environments.
	// Throws MESH_SERVICE_ERROR_LINK_ALREADY_EXISTS if a link already exists.
	CreateLink(context.Context, *CreateLinkRequest) (*CreateLinkResponse, error)
	// Retrieves a link for the requested resource, throwing MESH_SERVICE_ERROR_LINK_NOT_FOUND if there is no link.
	GetLink(context.Context, *GetLinkRequest) (*GetLinkResponse, error)
	// Updates a link for the requested resource, throwing MESH_SERVICE_ERROR_LINK_NOT_FOUND if there is no link.
	UpdateLink(context.Context, *UpdateLinkRequest) (*UpdateLinkResponse, error)
	// Deletes a link for the specified resource.
	DeleteLink(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error)
	// Searches for links with optional filters and pagination.
	SearchLinks(context.Context, *SearchLinksRequest) (*SearchLinksResponse, error)
	// Remote Connection operations.
	// ------------------------------------------------------------------------------------------------------------
	// Creates a remote connection for mesh links.
	// Throws MESH_SERVICE_ERROR_REMOTE_CONNECTION_ALREADY_EXISTS if a remote connection with the same name already exists.
	CreateRemoteConnection(context.Context, *CreateRemoteConnectionRequest) (*CreateRemoteConnectionResponse, error)
	// Retrieves a remote connection by RID.
	// Throws MESH_SERVICE_ERROR_REMOTE_CONNECTION_NOT_FOUND if there is no remote connection.
	GetRemoteConnection(context.Context, *GetRemoteConnectionRequest) (*GetRemoteConnectionResponse, error)
	// Updates a remote connection by RID.
	// Throws MESH_SERVICE_ERROR_REMOTE_CONNECTION_NOT_FOUND if there is no remote connection.
	UpdateRemoteConnection(context.Context, *UpdateRemoteConnectionRequest) (*UpdateRemoteConnectionResponse, error)
	// Deletes a remote connection by RID.
	DeleteRemoteConnection(context.Context, *DeleteRemoteConnectionRequest) (*DeleteRemoteConnectionResponse, error)
	// Lists all remote connections.
	ListRemoteConnections(context.Context, *ListRemoteConnectionsRequest) (*ListRemoteConnectionsResponse, error)
	mustEmbedUnimplementedMeshServiceServer()
}

// UnimplementedMeshServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServiceServer struct{}

func (UnimplementedMeshServiceServer) Mesh(context.Context, *MeshRequest) (*MeshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mesh not implemented")
}
func (UnimplementedMeshServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMeshServiceServer) CreateLink(context.Context, *CreateLinkRequest) (*CreateLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLink not implemented")
}
func (UnimplementedMeshServiceServer) GetLink(context.Context, *GetLinkRequest) (*GetLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedMeshServiceServer) UpdateLink(context.Context, *UpdateLinkRequest) (*UpdateLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLink not implemented")
}
func (UnimplementedMeshServiceServer) DeleteLink(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLink not implemented")
}
func (UnimplementedMeshServiceServer) SearchLinks(context.Context, *SearchLinksRequest) (*SearchLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchLinks not implemented")
}
func (UnimplementedMeshServiceServer) CreateRemoteConnection(context.Context, *CreateRemoteConnectionRequest) (*CreateRemoteConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRemoteConnection not implemented")
}
func (UnimplementedMeshServiceServer) GetRemoteConnection(context.Context, *GetRemoteConnectionRequest) (*GetRemoteConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRemoteConnection not implemented")
}
func (UnimplementedMeshServiceServer) UpdateRemoteConnection(context.Context, *UpdateRemoteConnectionRequest) (*UpdateRemoteConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRemoteConnection not implemented")
}
func (UnimplementedMeshServiceServer) DeleteRemoteConnection(context.Context, *DeleteRemoteConnectionRequest) (*DeleteRemoteConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRemoteConnection not implemented")
}
func (UnimplementedMeshServiceServer) ListRemoteConnections(context.Context, *ListRemoteConnectionsRequest) (*ListRemoteConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRemoteConnections not implemented")
}
func (UnimplementedMeshServiceServer) mustEmbedUnimplementedMeshServiceServer() {}
func (UnimplementedMeshServiceServer) testEmbeddedByValue()                     {}

// UnsafeMeshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServiceServer will
// result in compilation errors.
type UnsafeMeshServiceServer interface {
	mustEmbedUnimplementedMeshServiceServer()
}

func RegisterMeshServiceServer(s grpc.ServiceRegistrar, srv MeshServiceServer) {
	// If the following call panics, it indicates UnimplementedMeshServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshService_ServiceDesc, srv)
}

func _MeshService_Mesh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).Mesh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_Mesh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).Mesh(ctx, req.(*MeshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_CreateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CreateLink(ctx, req.(*CreateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_GetLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).GetLink(ctx, req.(*GetLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_UpdateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).UpdateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_UpdateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).UpdateLink(ctx, req.(*UpdateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_DeleteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).DeleteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_DeleteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).DeleteLink(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_SearchLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).SearchLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_SearchLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).SearchLinks(ctx, req.(*SearchLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_CreateRemoteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRemoteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CreateRemoteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_CreateRemoteConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CreateRemoteConnection(ctx, req.(*CreateRemoteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_GetRemoteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemoteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).GetRemoteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_GetRemoteConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).GetRemoteConnection(ctx, req.(*GetRemoteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_UpdateRemoteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemoteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).UpdateRemoteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_UpdateRemoteConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).UpdateRemoteConnection(ctx, req.(*UpdateRemoteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_DeleteRemoteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRemoteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).DeleteRemoteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_DeleteRemoteConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).DeleteRemoteConnection(ctx, req.(*DeleteRemoteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_ListRemoteConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemoteConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).ListRemoteConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_ListRemoteConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).ListRemoteConnections(ctx, req.(*ListRemoteConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshService_ServiceDesc is the grpc.ServiceDesc for MeshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.mesh.v1.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mesh",
			Handler:    _MeshService_Mesh_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MeshService_HealthCheck_Handler,
		},
		{
			MethodName: "CreateLink",
			Handler:    _MeshService_CreateLink_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _MeshService_GetLink_Handler,
		},
		{
			MethodName: "UpdateLink",
			Handler:    _MeshService_UpdateLink_Handler,
		},
		{
			MethodName: "DeleteLink",
			Handler:    _MeshService_DeleteLink_Handler,
		},
		{
			MethodName: "SearchLinks",
			Handler:    _MeshService_SearchLinks_Handler,
		},
		{
			MethodName: "CreateRemoteConnection",
			Handler:    _MeshService_CreateRemoteConnection_Handler,
		},
		{
			MethodName: "GetRemoteConnection",
			Handler:    _MeshService_GetRemoteConnection_Handler,
		},
		{
			MethodName: "UpdateRemoteConnection",
			Handler:    _MeshService_UpdateRemoteConnection_Handler,
		},
		{
			MethodName: "DeleteRemoteConnection",
			Handler:    _MeshService_DeleteRemoteConnection_Handler,
		},
		{
			MethodName: "ListRemoteConnections",
			Handler:    _MeshService_ListRemoteConnections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/mesh/v1/mesh.proto",
}
