// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/authz/v1/annotations.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The failing-check policy for one RPC. All requirements must hold
type AuthzPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unordered. Empty means no grant can fail this call, unless dynamic is set
	Requirements []*Requirement `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	// The handler has a failing check the caller cannot pre-evaluate, because it
	// depends on server state or on a resource the handler resolves. Consumers
	// must not read `requirements` as exhaustive.
	Dynamic bool `protobuf:"varint,2,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	// What cannot be pre-checked, and why. Required when dynamic is true
	DynamicReason string `protobuf:"bytes,3,opt,name=dynamic_reason,json=dynamicReason,proto3" json:"dynamic_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzPolicy) Reset() {
	*x = AuthzPolicy{}
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzPolicy) ProtoMessage() {}

func (x *AuthzPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzPolicy.ProtoReflect.Descriptor instead.
func (*AuthzPolicy) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authz_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *AuthzPolicy) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *AuthzPolicy) GetDynamic() bool {
	if x != nil {
		return x.Dynamic
	}
	return false
}

func (x *AuthzPolicy) GetDynamicReason() string {
	if x != nil {
		return x.DynamicReason
	}
	return ""
}

// One check whose denial fails the call
type Requirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gatekeeper action, e.g. "marking:update". Must be a value of
	// io.nominal.gatekeeper.security.PermissionAction.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// What the action is checked against
	//
	// Types that are valid to be assigned to Scope:
	//
	//	*Requirement_Resource
	//	*Requirement_Organization
	//	*Requirement_Workspace
	Scope         isRequirement_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authz_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Requirement) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Requirement) GetScope() isRequirement_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Requirement) GetResource() *ResourceScope {
	if x != nil {
		if x, ok := x.Scope.(*Requirement_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *Requirement) GetOrganization() *OrganizationScope {
	if x != nil {
		if x, ok := x.Scope.(*Requirement_Organization); ok {
			return x.Organization
		}
	}
	return nil
}

func (x *Requirement) GetWorkspace() *WorkspaceScope {
	if x != nil {
		if x, ok := x.Scope.(*Requirement_Workspace); ok {
			return x.Workspace
		}
	}
	return nil
}

type isRequirement_Scope interface {
	isRequirement_Scope()
}

type Requirement_Resource struct {
	Resource *ResourceScope `protobuf:"bytes,2,opt,name=resource,proto3,oneof"`
}

type Requirement_Organization struct {
	Organization *OrganizationScope `protobuf:"bytes,3,opt,name=organization,proto3,oneof"`
}

type Requirement_Workspace struct {
	Workspace *WorkspaceScope `protobuf:"bytes,4,opt,name=workspace,proto3,oneof"`
}

func (*Requirement_Resource) isRequirement_Scope() {}

func (*Requirement_Organization) isRequirement_Scope() {}

func (*Requirement_Workspace) isRequirement_Scope() {}

// Checked against a resource the request names.
type ResourceScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request field carrying the resource, in lower_snake_case. If the resource
	// is resolved by the handler instead, set AuthzPolicy.dynamic.
	Field         string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceScope) Reset() {
	*x = ResourceScope{}
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceScope) ProtoMessage() {}

func (x *ResourceScope) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceScope.ProtoReflect.Descriptor instead.
func (*ResourceScope) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authz_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceScope) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// Checked against the caller's organization, taken from the session.
type OrganizationScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationScope) Reset() {
	*x = OrganizationScope{}
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationScope) ProtoMessage() {}

func (x *OrganizationScope) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationScope.ProtoReflect.Descriptor instead.
func (*OrganizationScope) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authz_v1_annotations_proto_rawDescGZIP(), []int{3}
}

// Checked against the caller's workspace, taken from the session.
type WorkspaceScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceScope) Reset() {
	*x = WorkspaceScope{}
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceScope) ProtoMessage() {}

func (x *WorkspaceScope) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_authz_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceScope.ProtoReflect.Descriptor instead.
func (*WorkspaceScope) Descriptor() ([]byte, []int) {
	return file_nominal_protos_authz_v1_annotations_proto_rawDescGZIP(), []int{4}
}

var file_nominal_protos_authz_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthzPolicy)(nil),
		Field:         54055,
		Name:          "nominal.authz.v1.authz",
		Tag:           "bytes,54055,opt,name=authz",
		Filename:      "nominal/protos/authz/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional nominal.authz.v1.AuthzPolicy authz = 54055;
	E_Authz = &file_nominal_protos_authz_v1_annotations_proto_extTypes[0]
)

var File_nominal_protos_authz_v1_annotations_proto protoreflect.FileDescriptor

const file_nominal_protos_authz_v1_annotations_proto_rawDesc = "" +
	"\n" +
	")nominal/protos/authz/v1/annotations.proto\x12\x10nominal.authz.v1\x1a google/protobuf/descriptor.proto\"\x91\x01\n" +
	"\vAuthzPolicy\x12A\n" +
	"\frequirements\x18\x01 \x03(\v2\x1d.nominal.authz.v1.RequirementR\frequirements\x12\x18\n" +
	"\adynamic\x18\x02 \x01(\bR\adynamic\x12%\n" +
	"\x0edynamic_reason\x18\x03 \x01(\tR\rdynamicReason\"\xfa\x01\n" +
	"\vRequirement\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12=\n" +
	"\bresource\x18\x02 \x01(\v2\x1f.nominal.authz.v1.ResourceScopeH\x00R\bresource\x12I\n" +
	"\forganization\x18\x03 \x01(\v2#.nominal.authz.v1.OrganizationScopeH\x00R\forganization\x12@\n" +
	"\tworkspace\x18\x04 \x01(\v2 .nominal.authz.v1.WorkspaceScopeH\x00R\tworkspaceB\a\n" +
	"\x05scope\"%\n" +
	"\rResourceScope\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\"\x13\n" +
	"\x11OrganizationScope\"\x10\n" +
	"\x0eWorkspaceScope:U\n" +
	"\x05authz\x12\x1e.google.protobuf.MethodOptions\x18\xa7\xa6\x03 \x01(\v2\x1d.nominal.authz.v1.AuthzPolicyR\x05authzB\xd7\x01\n" +
	"\x14com.nominal.authz.v1B\x10AnnotationsProtoP\x01ZKgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/authz/v1;authzv1\xa2\x02\x03NAX\xaa\x02\x10Nominal.Authz.V1\xca\x02\x10Nominal\\Authz\\V1\xe2\x02\x1cNominal\\Authz\\V1\\GPBMetadata\xea\x02\x12Nominal::Authz::V1b\x06proto3"

var (
	file_nominal_protos_authz_v1_annotations_proto_rawDescOnce sync.Once
	file_nominal_protos_authz_v1_annotations_proto_rawDescData []byte
)

func file_nominal_protos_authz_v1_annotations_proto_rawDescGZIP() []byte {
	file_nominal_protos_authz_v1_annotations_proto_rawDescOnce.Do(func() {
		file_nominal_protos_authz_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_authz_v1_annotations_proto_rawDesc), len(file_nominal_protos_authz_v1_annotations_proto_rawDesc)))
	})
	return file_nominal_protos_authz_v1_annotations_proto_rawDescData
}

var file_nominal_protos_authz_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nominal_protos_authz_v1_annotations_proto_goTypes = []any{
	(*AuthzPolicy)(nil),                // 0: nominal.authz.v1.AuthzPolicy
	(*Requirement)(nil),                // 1: nominal.authz.v1.Requirement
	(*ResourceScope)(nil),              // 2: nominal.authz.v1.ResourceScope
	(*OrganizationScope)(nil),          // 3: nominal.authz.v1.OrganizationScope
	(*WorkspaceScope)(nil),             // 4: nominal.authz.v1.WorkspaceScope
	(*descriptorpb.MethodOptions)(nil), // 5: google.protobuf.MethodOptions
}
var file_nominal_protos_authz_v1_annotations_proto_depIdxs = []int32{
	1, // 0: nominal.authz.v1.AuthzPolicy.requirements:type_name -> nominal.authz.v1.Requirement
	2, // 1: nominal.authz.v1.Requirement.resource:type_name -> nominal.authz.v1.ResourceScope
	3, // 2: nominal.authz.v1.Requirement.organization:type_name -> nominal.authz.v1.OrganizationScope
	4, // 3: nominal.authz.v1.Requirement.workspace:type_name -> nominal.authz.v1.WorkspaceScope
	5, // 4: nominal.authz.v1.authz:extendee -> google.protobuf.MethodOptions
	0, // 5: nominal.authz.v1.authz:type_name -> nominal.authz.v1.AuthzPolicy
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	4, // [4:5] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nominal_protos_authz_v1_annotations_proto_init() }
func file_nominal_protos_authz_v1_annotations_proto_init() {
	if File_nominal_protos_authz_v1_annotations_proto != nil {
		return
	}
	file_nominal_protos_authz_v1_annotations_proto_msgTypes[1].OneofWrappers = []any{
		(*Requirement_Resource)(nil),
		(*Requirement_Organization)(nil),
		(*Requirement_Workspace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_authz_v1_annotations_proto_rawDesc), len(file_nominal_protos_authz_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_nominal_protos_authz_v1_annotations_proto_goTypes,
		DependencyIndexes: file_nominal_protos_authz_v1_annotations_proto_depIdxs,
		MessageInfos:      file_nominal_protos_authz_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_nominal_protos_authz_v1_annotations_proto_extTypes,
	}.Build()
	File_nominal_protos_authz_v1_annotations_proto = out.File
	file_nominal_protos_authz_v1_annotations_proto_goTypes = nil
	file_nominal_protos_authz_v1_annotations_proto_depIdxs = nil
}
