// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/sql/v1/sql.proto

package sqlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SqlService_Query_FullMethodName         = "/nominal.sql.v1.SqlService/Query"
	SqlService_Export_FullMethodName        = "/nominal.sql.v1.SqlService/Export"
	SqlService_GetSqlCatalog_FullMethodName = "/nominal.sql.v1.SqlService/GetSqlCatalog"
)

// SqlServiceClient is the client API for SqlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Executes read-only SQL queries against Scout telemetry tables.
type SqlServiceClient interface {
	// Validate, authorize, lower, and execute a bounded SQL query.
	Query(ctx context.Context, in *SqlServiceQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SqlServiceQueryResponse], error)
	// Validate, authorize, lower, and execute an unbounded SQL query, writing the full result to
	// object storage as CSV and returning a presigned URL.
	Export(ctx context.Context, in *SqlServiceExportRequest, opts ...grpc.CallOption) (*SqlServiceExportResponse, error)
	// Get the queryable SQL surface: tables, columns, and allowed functions.
	GetSqlCatalog(ctx context.Context, in *GetSqlCatalogRequest, opts ...grpc.CallOption) (*GetSqlCatalogResponse, error)
}

type sqlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlServiceClient(cc grpc.ClientConnInterface) SqlServiceClient {
	return &sqlServiceClient{cc}
}

func (c *sqlServiceClient) Query(ctx context.Context, in *SqlServiceQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SqlServiceQueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SqlService_ServiceDesc.Streams[0], SqlService_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SqlServiceQueryRequest, SqlServiceQueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlService_QueryClient = grpc.ServerStreamingClient[SqlServiceQueryResponse]

func (c *sqlServiceClient) Export(ctx context.Context, in *SqlServiceExportRequest, opts ...grpc.CallOption) (*SqlServiceExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqlServiceExportResponse)
	err := c.cc.Invoke(ctx, SqlService_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlServiceClient) GetSqlCatalog(ctx context.Context, in *GetSqlCatalogRequest, opts ...grpc.CallOption) (*GetSqlCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSqlCatalogResponse)
	err := c.cc.Invoke(ctx, SqlService_GetSqlCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqlServiceServer is the server API for SqlService service.
// All implementations must embed UnimplementedSqlServiceServer
// for forward compatibility.
//
// Executes read-only SQL queries against Scout telemetry tables.
type SqlServiceServer interface {
	// Validate, authorize, lower, and execute a bounded SQL query.
	Query(*SqlServiceQueryRequest, grpc.ServerStreamingServer[SqlServiceQueryResponse]) error
	// Validate, authorize, lower, and execute an unbounded SQL query, writing the full result to
	// object storage as CSV and returning a presigned URL.
	Export(context.Context, *SqlServiceExportRequest) (*SqlServiceExportResponse, error)
	// Get the queryable SQL surface: tables, columns, and allowed functions.
	GetSqlCatalog(context.Context, *GetSqlCatalogRequest) (*GetSqlCatalogResponse, error)
	mustEmbedUnimplementedSqlServiceServer()
}

// UnimplementedSqlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlServiceServer struct{}

func (UnimplementedSqlServiceServer) Query(*SqlServiceQueryRequest, grpc.ServerStreamingServer[SqlServiceQueryResponse]) error {
	return status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSqlServiceServer) Export(context.Context, *SqlServiceExportRequest) (*SqlServiceExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedSqlServiceServer) GetSqlCatalog(context.Context, *GetSqlCatalogRequest) (*GetSqlCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSqlCatalog not implemented")
}
func (UnimplementedSqlServiceServer) mustEmbedUnimplementedSqlServiceServer() {}
func (UnimplementedSqlServiceServer) testEmbeddedByValue()                    {}

// UnsafeSqlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlServiceServer will
// result in compilation errors.
type UnsafeSqlServiceServer interface {
	mustEmbedUnimplementedSqlServiceServer()
}

func RegisterSqlServiceServer(s grpc.ServiceRegistrar, srv SqlServiceServer) {
	// If the following call panics, it indicates UnimplementedSqlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqlService_ServiceDesc, srv)
}

func _SqlService_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SqlServiceQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SqlServiceServer).Query(m, &grpc.GenericServerStream[SqlServiceQueryRequest, SqlServiceQueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqlService_QueryServer = grpc.ServerStreamingServer[SqlServiceQueryResponse]

func _SqlService_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlServiceExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServiceServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlService_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServiceServer).Export(ctx, req.(*SqlServiceExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqlService_GetSqlCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSqlCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServiceServer).GetSqlCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlService_GetSqlCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServiceServer).GetSqlCatalog(ctx, req.(*GetSqlCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SqlService_ServiceDesc is the grpc.ServiceDesc for SqlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.sql.v1.SqlService",
	HandlerType: (*SqlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Export",
			Handler:    _SqlService_Export_Handler,
		},
		{
			MethodName: "GetSqlCatalog",
			Handler:    _SqlService_GetSqlCatalog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _SqlService_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nominal/protos/sql/v1/sql.proto",
}
