// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/ingest/v2/containerized_ingest.proto

package ingestv2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One containerized extractor invocation. Input sources are bound to environment variables.
type ContainerizedIngestItem struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	ExtractorRid      string                   `protobuf:"bytes,1,opt,name=extractor_rid,json=extractorRid,proto3" json:"extractor_rid,omitempty"`
	Sources           map[string]*IngestSource `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Arguments         map[string]string        `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampMetadata *TimestampMetadata       `protobuf:"bytes,4,opt,name=timestamp_metadata,json=timestampMetadata,proto3,oneof" json:"timestamp_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContainerizedIngestItem) Reset() {
	*x = ContainerizedIngestItem{}
	mi := &file_nominal_protos_ingest_v2_containerized_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerizedIngestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerizedIngestItem) ProtoMessage() {}

func (x *ContainerizedIngestItem) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_containerized_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerizedIngestItem.ProtoReflect.Descriptor instead.
func (*ContainerizedIngestItem) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerizedIngestItem) GetExtractorRid() string {
	if x != nil {
		return x.ExtractorRid
	}
	return ""
}

func (x *ContainerizedIngestItem) GetSources() map[string]*IngestSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ContainerizedIngestItem) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ContainerizedIngestItem) GetTimestampMetadata() *TimestampMetadata {
	if x != nil {
		return x.TimestampMetadata
	}
	return nil
}

var File_nominal_protos_ingest_v2_containerized_ingest_proto protoreflect.FileDescriptor

const file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDesc = "" +
	"\n" +
	"3nominal/protos/ingest/v2/containerized_ingest.proto\x12\x11nominal.ingest.v2\x1a\x1bbuf/validate/validate.proto\x1a!nominal/protos/gen/v1/alias.proto\x1a%nominal/protos/ingest/v2/common.proto\"\x97\x05\n" +
	"\x17ContainerizedIngestItem\x12`\n" +
	"\rextractor_rid\x18\x01 \x01(\tB;\xbaH\x03\xc8\x01\x01\x9a\xb2\x1a1\n" +
	"/io.nominal.ingest.api.ContainerizedExtractorRidR\fextractorRid\x12\x82\x01\n" +
	"\asources\x18\x02 \x03(\v27.nominal.ingest.v2.ContainerizedIngestItem.SourcesEntryB/\x9a\xb2\x1a+\x12)io.nominal.ingest.api.EnvironmentVariableR\asources\x12\x88\x01\n" +
	"\targuments\x18\x03 \x03(\v29.nominal.ingest.v2.ContainerizedIngestItem.ArgumentsEntryB/\x9a\xb2\x1a+\x12)io.nominal.ingest.api.EnvironmentVariableR\targuments\x12X\n" +
	"\x12timestamp_metadata\x18\x04 \x01(\v2$.nominal.ingest.v2.TimestampMetadataH\x00R\x11timestampMetadata\x88\x01\x01\x1a[\n" +
	"\fSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.nominal.ingest.v2.IngestSourceR\x05value:\x028\x01\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x15\n" +
	"\x13_timestamp_metadataB\xe6\x01\n" +
	"\x15com.nominal.ingest.v2B\x18ContainerizedIngestProtoP\x01ZMgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/ingest/v2;ingestv2\xa2\x02\x03NIX\xaa\x02\x11Nominal.Ingest.V2\xca\x02\x11Nominal\\Ingest\\V2\xe2\x02\x1dNominal\\Ingest\\V2\\GPBMetadata\xea\x02\x13Nominal::Ingest::V2b\x06proto3"

var (
	file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDescOnce sync.Once
	file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDescData []byte
)

func file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDescGZIP() []byte {
	file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDescOnce.Do(func() {
		file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDesc), len(file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDesc)))
	})
	return file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDescData
}

var file_nominal_protos_ingest_v2_containerized_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nominal_protos_ingest_v2_containerized_ingest_proto_goTypes = []any{
	(*ContainerizedIngestItem)(nil), // 0: nominal.ingest.v2.ContainerizedIngestItem
	nil,                             // 1: nominal.ingest.v2.ContainerizedIngestItem.SourcesEntry
	nil,                             // 2: nominal.ingest.v2.ContainerizedIngestItem.ArgumentsEntry
	(*TimestampMetadata)(nil),       // 3: nominal.ingest.v2.TimestampMetadata
	(*IngestSource)(nil),            // 4: nominal.ingest.v2.IngestSource
}
var file_nominal_protos_ingest_v2_containerized_ingest_proto_depIdxs = []int32{
	1, // 0: nominal.ingest.v2.ContainerizedIngestItem.sources:type_name -> nominal.ingest.v2.ContainerizedIngestItem.SourcesEntry
	2, // 1: nominal.ingest.v2.ContainerizedIngestItem.arguments:type_name -> nominal.ingest.v2.ContainerizedIngestItem.ArgumentsEntry
	3, // 2: nominal.ingest.v2.ContainerizedIngestItem.timestamp_metadata:type_name -> nominal.ingest.v2.TimestampMetadata
	4, // 3: nominal.ingest.v2.ContainerizedIngestItem.SourcesEntry.value:type_name -> nominal.ingest.v2.IngestSource
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nominal_protos_ingest_v2_containerized_ingest_proto_init() }
func file_nominal_protos_ingest_v2_containerized_ingest_proto_init() {
	if File_nominal_protos_ingest_v2_containerized_ingest_proto != nil {
		return
	}
	file_nominal_protos_ingest_v2_common_proto_init()
	file_nominal_protos_ingest_v2_containerized_ingest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDesc), len(file_nominal_protos_ingest_v2_containerized_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nominal_protos_ingest_v2_containerized_ingest_proto_goTypes,
		DependencyIndexes: file_nominal_protos_ingest_v2_containerized_ingest_proto_depIdxs,
		MessageInfos:      file_nominal_protos_ingest_v2_containerized_ingest_proto_msgTypes,
	}.Build()
	File_nominal_protos_ingest_v2_containerized_ingest_proto = out.File
	file_nominal_protos_ingest_v2_containerized_ingest_proto_goTypes = nil
	file_nominal_protos_ingest_v2_containerized_ingest_proto_depIdxs = nil
}
