// V2 of the containerized extractor service. Speaks gRPC/proto so it can be exposed alongside
// the existing v1 Conjure-based ContainerizedExtractorService without breaking existing clients.
//
// V2 differs from v1 in that:
//   - The transport is gRPC + proto rather than Conjure HTTP, matching the rest of the modern
//     scout surface (e.g. nominal.registry.v2.RegistryService).
//   - The extractor record itself only carries identity, ownership and lifecycle state. Schema
//     fields (inputs, parameters, output_file_format, default_timestamp_metadata) live on the
//     ContainerImage rows registered through nominal.registry.v2.RegistryService.CreateImage,
//     and the extractor exposes them indirectly through `active_container_image`. This avoids the
//     v1 mismatch where extractor- and image-level schemas could drift.
//   - Self-hosted images are the only supported source — the deprecated `image: DockerImageSource`
//     field from v1 is gone.
//   - Archive has a dedicated RPC; unarchive happens through Update by setting `is_archived` to
//     false.
//
// V1 remains the canonical API while clients migrate.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/ingest/v2/containerized_extractor.proto

package ingestv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerizedExtractorService_CreateContainerizedExtractor_FullMethodName  = "/nominal.ingest.v2.ContainerizedExtractorService/CreateContainerizedExtractor"
	ContainerizedExtractorService_GetContainerizedExtractor_FullMethodName     = "/nominal.ingest.v2.ContainerizedExtractorService/GetContainerizedExtractor"
	ContainerizedExtractorService_UpdateContainerizedExtractor_FullMethodName  = "/nominal.ingest.v2.ContainerizedExtractorService/UpdateContainerizedExtractor"
	ContainerizedExtractorService_ArchiveContainerizedExtractor_FullMethodName = "/nominal.ingest.v2.ContainerizedExtractorService/ArchiveContainerizedExtractor"
	ContainerizedExtractorService_SearchContainerizedExtractors_FullMethodName = "/nominal.ingest.v2.ContainerizedExtractorService/SearchContainerizedExtractors"
)

// ContainerizedExtractorServiceClient is the client API for ContainerizedExtractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Manages containerized extractors backed by self-hosted images in the internal registry.
type ContainerizedExtractorServiceClient interface {
	// Create a new extractor in a workspace. Container images are attached separately via
	// RegistryService.CreateImage.
	CreateContainerizedExtractor(ctx context.Context, in *CreateContainerizedExtractorRequest, opts ...grpc.CallOption) (*CreateContainerizedExtractorResponse, error)
	// Fetch a single extractor by RID.
	GetContainerizedExtractor(ctx context.Context, in *GetContainerizedExtractorRequest, opts ...grpc.CallOption) (*GetContainerizedExtractorResponse, error)
	// Partial update of an existing extractor. Use the `is_archived` field to archive / unarchive.
	UpdateContainerizedExtractor(ctx context.Context, in *UpdateContainerizedExtractorRequest, opts ...grpc.CallOption) (*UpdateContainerizedExtractorResponse, error)
	// Archive an extractor so it is hidden from default search results and rejects new ingests.
	ArchiveContainerizedExtractor(ctx context.Context, in *ArchiveContainerizedExtractorRequest, opts ...grpc.CallOption) (*ArchiveContainerizedExtractorResponse, error)
	// Search extractors within a workspace, with cursor-based pagination.
	SearchContainerizedExtractors(ctx context.Context, in *SearchContainerizedExtractorsRequest, opts ...grpc.CallOption) (*SearchContainerizedExtractorsResponse, error)
}

type containerizedExtractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerizedExtractorServiceClient(cc grpc.ClientConnInterface) ContainerizedExtractorServiceClient {
	return &containerizedExtractorServiceClient{cc}
}

func (c *containerizedExtractorServiceClient) CreateContainerizedExtractor(ctx context.Context, in *CreateContainerizedExtractorRequest, opts ...grpc.CallOption) (*CreateContainerizedExtractorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContainerizedExtractorResponse)
	err := c.cc.Invoke(ctx, ContainerizedExtractorService_CreateContainerizedExtractor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerizedExtractorServiceClient) GetContainerizedExtractor(ctx context.Context, in *GetContainerizedExtractorRequest, opts ...grpc.CallOption) (*GetContainerizedExtractorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerizedExtractorResponse)
	err := c.cc.Invoke(ctx, ContainerizedExtractorService_GetContainerizedExtractor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerizedExtractorServiceClient) UpdateContainerizedExtractor(ctx context.Context, in *UpdateContainerizedExtractorRequest, opts ...grpc.CallOption) (*UpdateContainerizedExtractorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContainerizedExtractorResponse)
	err := c.cc.Invoke(ctx, ContainerizedExtractorService_UpdateContainerizedExtractor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerizedExtractorServiceClient) ArchiveContainerizedExtractor(ctx context.Context, in *ArchiveContainerizedExtractorRequest, opts ...grpc.CallOption) (*ArchiveContainerizedExtractorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveContainerizedExtractorResponse)
	err := c.cc.Invoke(ctx, ContainerizedExtractorService_ArchiveContainerizedExtractor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerizedExtractorServiceClient) SearchContainerizedExtractors(ctx context.Context, in *SearchContainerizedExtractorsRequest, opts ...grpc.CallOption) (*SearchContainerizedExtractorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchContainerizedExtractorsResponse)
	err := c.cc.Invoke(ctx, ContainerizedExtractorService_SearchContainerizedExtractors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerizedExtractorServiceServer is the server API for ContainerizedExtractorService service.
// All implementations must embed UnimplementedContainerizedExtractorServiceServer
// for forward compatibility.
//
// Manages containerized extractors backed by self-hosted images in the internal registry.
type ContainerizedExtractorServiceServer interface {
	// Create a new extractor in a workspace. Container images are attached separately via
	// RegistryService.CreateImage.
	CreateContainerizedExtractor(context.Context, *CreateContainerizedExtractorRequest) (*CreateContainerizedExtractorResponse, error)
	// Fetch a single extractor by RID.
	GetContainerizedExtractor(context.Context, *GetContainerizedExtractorRequest) (*GetContainerizedExtractorResponse, error)
	// Partial update of an existing extractor. Use the `is_archived` field to archive / unarchive.
	UpdateContainerizedExtractor(context.Context, *UpdateContainerizedExtractorRequest) (*UpdateContainerizedExtractorResponse, error)
	// Archive an extractor so it is hidden from default search results and rejects new ingests.
	ArchiveContainerizedExtractor(context.Context, *ArchiveContainerizedExtractorRequest) (*ArchiveContainerizedExtractorResponse, error)
	// Search extractors within a workspace, with cursor-based pagination.
	SearchContainerizedExtractors(context.Context, *SearchContainerizedExtractorsRequest) (*SearchContainerizedExtractorsResponse, error)
	mustEmbedUnimplementedContainerizedExtractorServiceServer()
}

// UnimplementedContainerizedExtractorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerizedExtractorServiceServer struct{}

func (UnimplementedContainerizedExtractorServiceServer) CreateContainerizedExtractor(context.Context, *CreateContainerizedExtractorRequest) (*CreateContainerizedExtractorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContainerizedExtractor not implemented")
}
func (UnimplementedContainerizedExtractorServiceServer) GetContainerizedExtractor(context.Context, *GetContainerizedExtractorRequest) (*GetContainerizedExtractorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainerizedExtractor not implemented")
}
func (UnimplementedContainerizedExtractorServiceServer) UpdateContainerizedExtractor(context.Context, *UpdateContainerizedExtractorRequest) (*UpdateContainerizedExtractorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContainerizedExtractor not implemented")
}
func (UnimplementedContainerizedExtractorServiceServer) ArchiveContainerizedExtractor(context.Context, *ArchiveContainerizedExtractorRequest) (*ArchiveContainerizedExtractorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveContainerizedExtractor not implemented")
}
func (UnimplementedContainerizedExtractorServiceServer) SearchContainerizedExtractors(context.Context, *SearchContainerizedExtractorsRequest) (*SearchContainerizedExtractorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchContainerizedExtractors not implemented")
}
func (UnimplementedContainerizedExtractorServiceServer) mustEmbedUnimplementedContainerizedExtractorServiceServer() {
}
func (UnimplementedContainerizedExtractorServiceServer) testEmbeddedByValue() {}

// UnsafeContainerizedExtractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerizedExtractorServiceServer will
// result in compilation errors.
type UnsafeContainerizedExtractorServiceServer interface {
	mustEmbedUnimplementedContainerizedExtractorServiceServer()
}

func RegisterContainerizedExtractorServiceServer(s grpc.ServiceRegistrar, srv ContainerizedExtractorServiceServer) {
	// If the following call panics, it indicates UnimplementedContainerizedExtractorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerizedExtractorService_ServiceDesc, srv)
}

func _ContainerizedExtractorService_CreateContainerizedExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerizedExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerizedExtractorServiceServer).CreateContainerizedExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerizedExtractorService_CreateContainerizedExtractor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerizedExtractorServiceServer).CreateContainerizedExtractor(ctx, req.(*CreateContainerizedExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerizedExtractorService_GetContainerizedExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerizedExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerizedExtractorServiceServer).GetContainerizedExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerizedExtractorService_GetContainerizedExtractor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerizedExtractorServiceServer).GetContainerizedExtractor(ctx, req.(*GetContainerizedExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerizedExtractorService_UpdateContainerizedExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContainerizedExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerizedExtractorServiceServer).UpdateContainerizedExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerizedExtractorService_UpdateContainerizedExtractor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerizedExtractorServiceServer).UpdateContainerizedExtractor(ctx, req.(*UpdateContainerizedExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerizedExtractorService_ArchiveContainerizedExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveContainerizedExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerizedExtractorServiceServer).ArchiveContainerizedExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerizedExtractorService_ArchiveContainerizedExtractor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerizedExtractorServiceServer).ArchiveContainerizedExtractor(ctx, req.(*ArchiveContainerizedExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerizedExtractorService_SearchContainerizedExtractors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchContainerizedExtractorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerizedExtractorServiceServer).SearchContainerizedExtractors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerizedExtractorService_SearchContainerizedExtractors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerizedExtractorServiceServer).SearchContainerizedExtractors(ctx, req.(*SearchContainerizedExtractorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerizedExtractorService_ServiceDesc is the grpc.ServiceDesc for ContainerizedExtractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerizedExtractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.ingest.v2.ContainerizedExtractorService",
	HandlerType: (*ContainerizedExtractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainerizedExtractor",
			Handler:    _ContainerizedExtractorService_CreateContainerizedExtractor_Handler,
		},
		{
			MethodName: "GetContainerizedExtractor",
			Handler:    _ContainerizedExtractorService_GetContainerizedExtractor_Handler,
		},
		{
			MethodName: "UpdateContainerizedExtractor",
			Handler:    _ContainerizedExtractorService_UpdateContainerizedExtractor_Handler,
		},
		{
			MethodName: "ArchiveContainerizedExtractor",
			Handler:    _ContainerizedExtractorService_ArchiveContainerizedExtractor_Handler,
		},
		{
			MethodName: "SearchContainerizedExtractors",
			Handler:    _ContainerizedExtractorService_SearchContainerizedExtractors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/ingest/v2/containerized_extractor.proto",
}
