// Workspace enablement for native (Nominal-published) containerized extractors.
//
// The deployment's installable catalog is populated exclusively by internal catalog sync (the
// bootstrap Job seeds object storage, combined-service mirrors the verified index) — there is no
// public API for registering catalog content. This service is the workspace-facing surface on top
// of that catalog: browse what the deployment carries, enable an entry into a workspace (which
// materializes a FIRST_PARTY ContainerizedExtractor backed by a registry image imported from the
// staged catalog artifacts), converge an installation to a desired version, and disable it again.
//
// Enable reconciles synchronously within the request: the caller's credentials are needed
// to register new resources with the authorization service and to import the container image, so
// convergence happens while they are present. Both are idempotent — re-running a converged
// installation is a no-op.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/ingest/v2/native_extractor.proto

package ingestv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NativeExtractorService_ListNativeExtractors_FullMethodName   = "/nominal.ingest.v2.NativeExtractorService/ListNativeExtractors"
	NativeExtractorService_EnableNativeExtractor_FullMethodName  = "/nominal.ingest.v2.NativeExtractorService/EnableNativeExtractor"
	NativeExtractorService_DisableNativeExtractor_FullMethodName = "/nominal.ingest.v2.NativeExtractorService/DisableNativeExtractor"
)

// NativeExtractorServiceClient is the client API for NativeExtractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Workspace-facing surface for enabling and converging native catalog extractors.
type NativeExtractorServiceClient interface {
	// Lists every catalog entry the deployment carries with this workspace's installation state.
	ListNativeExtractors(ctx context.Context, in *ListNativeExtractorsRequest, opts ...grpc.CallOption) (*ListNativeExtractorsResponse, error)
	// Enables a catalog entry in a workspace and converges it to the deployment's current desired
	// version, materializing the workspace-local extractor and importing its container image.
	// Idempotent: calling it on an already-enabled entry re-converges to the current desired
	// version (this is also how a stale installation picks up a newly published version).
	EnableNativeExtractor(ctx context.Context, in *EnableNativeExtractorRequest, opts ...grpc.CallOption) (*EnableNativeExtractorResponse, error)
	// Archives the workspace's extractor, which is the installation; re-enabling unarchives it.
	DisableNativeExtractor(ctx context.Context, in *DisableNativeExtractorRequest, opts ...grpc.CallOption) (*DisableNativeExtractorResponse, error)
}

type nativeExtractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNativeExtractorServiceClient(cc grpc.ClientConnInterface) NativeExtractorServiceClient {
	return &nativeExtractorServiceClient{cc}
}

func (c *nativeExtractorServiceClient) ListNativeExtractors(ctx context.Context, in *ListNativeExtractorsRequest, opts ...grpc.CallOption) (*ListNativeExtractorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNativeExtractorsResponse)
	err := c.cc.Invoke(ctx, NativeExtractorService_ListNativeExtractors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nativeExtractorServiceClient) EnableNativeExtractor(ctx context.Context, in *EnableNativeExtractorRequest, opts ...grpc.CallOption) (*EnableNativeExtractorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableNativeExtractorResponse)
	err := c.cc.Invoke(ctx, NativeExtractorService_EnableNativeExtractor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nativeExtractorServiceClient) DisableNativeExtractor(ctx context.Context, in *DisableNativeExtractorRequest, opts ...grpc.CallOption) (*DisableNativeExtractorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableNativeExtractorResponse)
	err := c.cc.Invoke(ctx, NativeExtractorService_DisableNativeExtractor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NativeExtractorServiceServer is the server API for NativeExtractorService service.
// All implementations must embed UnimplementedNativeExtractorServiceServer
// for forward compatibility.
//
// Workspace-facing surface for enabling and converging native catalog extractors.
type NativeExtractorServiceServer interface {
	// Lists every catalog entry the deployment carries with this workspace's installation state.
	ListNativeExtractors(context.Context, *ListNativeExtractorsRequest) (*ListNativeExtractorsResponse, error)
	// Enables a catalog entry in a workspace and converges it to the deployment's current desired
	// version, materializing the workspace-local extractor and importing its container image.
	// Idempotent: calling it on an already-enabled entry re-converges to the current desired
	// version (this is also how a stale installation picks up a newly published version).
	EnableNativeExtractor(context.Context, *EnableNativeExtractorRequest) (*EnableNativeExtractorResponse, error)
	// Archives the workspace's extractor, which is the installation; re-enabling unarchives it.
	DisableNativeExtractor(context.Context, *DisableNativeExtractorRequest) (*DisableNativeExtractorResponse, error)
	mustEmbedUnimplementedNativeExtractorServiceServer()
}

// UnimplementedNativeExtractorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNativeExtractorServiceServer struct{}

func (UnimplementedNativeExtractorServiceServer) ListNativeExtractors(context.Context, *ListNativeExtractorsRequest) (*ListNativeExtractorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNativeExtractors not implemented")
}
func (UnimplementedNativeExtractorServiceServer) EnableNativeExtractor(context.Context, *EnableNativeExtractorRequest) (*EnableNativeExtractorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableNativeExtractor not implemented")
}
func (UnimplementedNativeExtractorServiceServer) DisableNativeExtractor(context.Context, *DisableNativeExtractorRequest) (*DisableNativeExtractorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableNativeExtractor not implemented")
}
func (UnimplementedNativeExtractorServiceServer) mustEmbedUnimplementedNativeExtractorServiceServer() {
}
func (UnimplementedNativeExtractorServiceServer) testEmbeddedByValue() {}

// UnsafeNativeExtractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NativeExtractorServiceServer will
// result in compilation errors.
type UnsafeNativeExtractorServiceServer interface {
	mustEmbedUnimplementedNativeExtractorServiceServer()
}

func RegisterNativeExtractorServiceServer(s grpc.ServiceRegistrar, srv NativeExtractorServiceServer) {
	// If the following call panics, it indicates UnimplementedNativeExtractorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NativeExtractorService_ServiceDesc, srv)
}

func _NativeExtractorService_ListNativeExtractors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNativeExtractorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeExtractorServiceServer).ListNativeExtractors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NativeExtractorService_ListNativeExtractors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeExtractorServiceServer).ListNativeExtractors(ctx, req.(*ListNativeExtractorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NativeExtractorService_EnableNativeExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableNativeExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeExtractorServiceServer).EnableNativeExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NativeExtractorService_EnableNativeExtractor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeExtractorServiceServer).EnableNativeExtractor(ctx, req.(*EnableNativeExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NativeExtractorService_DisableNativeExtractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableNativeExtractorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeExtractorServiceServer).DisableNativeExtractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NativeExtractorService_DisableNativeExtractor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeExtractorServiceServer).DisableNativeExtractor(ctx, req.(*DisableNativeExtractorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NativeExtractorService_ServiceDesc is the grpc.ServiceDesc for NativeExtractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NativeExtractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.ingest.v2.NativeExtractorService",
	HandlerType: (*NativeExtractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNativeExtractors",
			Handler:    _NativeExtractorService_ListNativeExtractors_Handler,
		},
		{
			MethodName: "EnableNativeExtractor",
			Handler:    _NativeExtractorService_EnableNativeExtractor_Handler,
		},
		{
			MethodName: "DisableNativeExtractor",
			Handler:    _NativeExtractorService_DisableNativeExtractor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/ingest/v2/native_extractor.proto",
}
