// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nominal/protos/ingest/v2/video_ingest.proto

package ingestv2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/nominal-io/nominal-api-protos-go/nominal/protos/gen/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dataset-file-backed video ingest work.
type VideoIngestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *IngestSource          `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Ingest        *VideoIngestOptions    `protobuf:"bytes,2,opt,name=ingest,proto3" json:"ingest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoIngestItem) Reset() {
	*x = VideoIngestItem{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoIngestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoIngestItem) ProtoMessage() {}

func (x *VideoIngestItem) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoIngestItem.ProtoReflect.Descriptor instead.
func (*VideoIngestItem) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *VideoIngestItem) GetSource() *IngestSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *VideoIngestItem) GetIngest() *VideoIngestOptions {
	if x != nil {
		return x.Ingest
	}
	return nil
}

type VideoIngestOptions struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	TimestampManifest *VideoTimestampManifest `protobuf:"bytes,1,opt,name=timestamp_manifest,json=timestampManifest,proto3" json:"timestamp_manifest,omitempty"`
	Channel           string                  `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	OverwriteSegments *bool                   `protobuf:"varint,3,opt,name=overwrite_segments,json=overwriteSegments,proto3,oneof" json:"overwrite_segments,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VideoIngestOptions) Reset() {
	*x = VideoIngestOptions{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoIngestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoIngestOptions) ProtoMessage() {}

func (x *VideoIngestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoIngestOptions.ProtoReflect.Descriptor instead.
func (*VideoIngestOptions) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *VideoIngestOptions) GetTimestampManifest() *VideoTimestampManifest {
	if x != nil {
		return x.TimestampManifest
	}
	return nil
}

func (x *VideoIngestOptions) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *VideoIngestOptions) GetOverwriteSegments() bool {
	if x != nil && x.OverwriteSegments != nil {
		return *x.OverwriteSegments
	}
	return false
}

type VideoTimestampManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Manifest:
	//
	//	*VideoTimestampManifest_NoManifest
	//	*VideoTimestampManifest_TimestampManifestFiles
	//	*VideoTimestampManifest_Mcap
	Manifest      isVideoTimestampManifest_Manifest `protobuf_oneof:"manifest"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoTimestampManifest) Reset() {
	*x = VideoTimestampManifest{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTimestampManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTimestampManifest) ProtoMessage() {}

func (x *VideoTimestampManifest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTimestampManifest.ProtoReflect.Descriptor instead.
func (*VideoTimestampManifest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *VideoTimestampManifest) GetManifest() isVideoTimestampManifest_Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *VideoTimestampManifest) GetNoManifest() *NoTimestampManifest {
	if x != nil {
		if x, ok := x.Manifest.(*VideoTimestampManifest_NoManifest); ok {
			return x.NoManifest
		}
	}
	return nil
}

func (x *VideoTimestampManifest) GetTimestampManifestFiles() *TimestampManifestFiles {
	if x != nil {
		if x, ok := x.Manifest.(*VideoTimestampManifest_TimestampManifestFiles); ok {
			return x.TimestampManifestFiles
		}
	}
	return nil
}

func (x *VideoTimestampManifest) GetMcap() *McapTimestampManifest {
	if x != nil {
		if x, ok := x.Manifest.(*VideoTimestampManifest_Mcap); ok {
			return x.Mcap
		}
	}
	return nil
}

type isVideoTimestampManifest_Manifest interface {
	isVideoTimestampManifest_Manifest()
}

type VideoTimestampManifest_NoManifest struct {
	NoManifest *NoTimestampManifest `protobuf:"bytes,1,opt,name=no_manifest,json=noManifest,proto3,oneof"`
}

type VideoTimestampManifest_TimestampManifestFiles struct {
	TimestampManifestFiles *TimestampManifestFiles `protobuf:"bytes,2,opt,name=timestamp_manifest_files,json=timestampManifestFiles,proto3,oneof"`
}

type VideoTimestampManifest_Mcap struct {
	Mcap *McapTimestampManifest `protobuf:"bytes,3,opt,name=mcap,proto3,oneof"`
}

func (*VideoTimestampManifest_NoManifest) isVideoTimestampManifest_Manifest() {}

func (*VideoTimestampManifest_TimestampManifestFiles) isVideoTimestampManifest_Manifest() {}

func (*VideoTimestampManifest_Mcap) isVideoTimestampManifest_Manifest() {}

type NoTimestampManifest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartingTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=starting_timestamp,json=startingTimestamp,proto3" json:"starting_timestamp,omitempty"`
	ScaleParameter    *ScaleParameter        `protobuf:"bytes,2,opt,name=scale_parameter,json=scaleParameter,proto3,oneof" json:"scale_parameter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NoTimestampManifest) Reset() {
	*x = NoTimestampManifest{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoTimestampManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoTimestampManifest) ProtoMessage() {}

func (x *NoTimestampManifest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoTimestampManifest.ProtoReflect.Descriptor instead.
func (*NoTimestampManifest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *NoTimestampManifest) GetStartingTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartingTimestamp
	}
	return nil
}

func (x *NoTimestampManifest) GetScaleParameter() *ScaleParameter {
	if x != nil {
		return x.ScaleParameter
	}
	return nil
}

// Sidecar manifest files whose per-frame timestamps are concatenated in list order. Used when a
// video's frame timestamps are recorded across several files.
type TimestampManifestFiles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*IngestSource        `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampManifestFiles) Reset() {
	*x = TimestampManifestFiles{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampManifestFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampManifestFiles) ProtoMessage() {}

func (x *TimestampManifestFiles) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampManifestFiles.ProtoReflect.Descriptor instead.
func (*TimestampManifestFiles) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *TimestampManifestFiles) GetSources() []*IngestSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

// Frame timestamps are embedded in the mcap file that carries the video frames, rather than supplied
// as a sidecar manifest.
type McapTimestampManifest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChannelLocator *McapChannelLocator    `protobuf:"bytes,1,opt,name=channel_locator,json=channelLocator,proto3" json:"channel_locator,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *McapTimestampManifest) Reset() {
	*x = McapTimestampManifest{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McapTimestampManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McapTimestampManifest) ProtoMessage() {}

func (x *McapTimestampManifest) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McapTimestampManifest.ProtoReflect.Descriptor instead.
func (*McapTimestampManifest) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *McapTimestampManifest) GetChannelLocator() *McapChannelLocator {
	if x != nil {
		return x.ChannelLocator
	}
	return nil
}

// Locates the video's channel within an mcap file. Topics are not guaranteed unique, so an mcap file
// with duplicate topics must be located by id.
type McapChannelLocator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Locator:
	//
	//	*McapChannelLocator_Topic
	//	*McapChannelLocator_Id
	Locator       isMcapChannelLocator_Locator `protobuf_oneof:"locator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McapChannelLocator) Reset() {
	*x = McapChannelLocator{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McapChannelLocator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McapChannelLocator) ProtoMessage() {}

func (x *McapChannelLocator) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McapChannelLocator.ProtoReflect.Descriptor instead.
func (*McapChannelLocator) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *McapChannelLocator) GetLocator() isMcapChannelLocator_Locator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *McapChannelLocator) GetTopic() string {
	if x != nil {
		if x, ok := x.Locator.(*McapChannelLocator_Topic); ok {
			return x.Topic
		}
	}
	return ""
}

func (x *McapChannelLocator) GetId() int32 {
	if x != nil {
		if x, ok := x.Locator.(*McapChannelLocator_Id); ok {
			return x.Id
		}
	}
	return 0
}

type isMcapChannelLocator_Locator interface {
	isMcapChannelLocator_Locator()
}

type McapChannelLocator_Topic struct {
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3,oneof"`
}

type McapChannelLocator_Id struct {
	Id int32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

func (*McapChannelLocator_Topic) isMcapChannelLocator_Locator() {}

func (*McapChannelLocator_Id) isMcapChannelLocator_Locator() {}

type ScaleParameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ScaleParameter:
	//
	//	*ScaleParameter_TrueFrameRate
	//	*ScaleParameter_EndingTimestamp
	//	*ScaleParameter_ScaleFactor
	ScaleParameter isScaleParameter_ScaleParameter `protobuf_oneof:"scale_parameter"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScaleParameter) Reset() {
	*x = ScaleParameter{}
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleParameter) ProtoMessage() {}

func (x *ScaleParameter) ProtoReflect() protoreflect.Message {
	mi := &file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleParameter.ProtoReflect.Descriptor instead.
func (*ScaleParameter) Descriptor() ([]byte, []int) {
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *ScaleParameter) GetScaleParameter() isScaleParameter_ScaleParameter {
	if x != nil {
		return x.ScaleParameter
	}
	return nil
}

func (x *ScaleParameter) GetTrueFrameRate() float64 {
	if x != nil {
		if x, ok := x.ScaleParameter.(*ScaleParameter_TrueFrameRate); ok {
			return x.TrueFrameRate
		}
	}
	return 0
}

func (x *ScaleParameter) GetEndingTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.ScaleParameter.(*ScaleParameter_EndingTimestamp); ok {
			return x.EndingTimestamp
		}
	}
	return nil
}

func (x *ScaleParameter) GetScaleFactor() float64 {
	if x != nil {
		if x, ok := x.ScaleParameter.(*ScaleParameter_ScaleFactor); ok {
			return x.ScaleFactor
		}
	}
	return 0
}

type isScaleParameter_ScaleParameter interface {
	isScaleParameter_ScaleParameter()
}

type ScaleParameter_TrueFrameRate struct {
	TrueFrameRate float64 `protobuf:"fixed64,1,opt,name=true_frame_rate,json=trueFrameRate,proto3,oneof"`
}

type ScaleParameter_EndingTimestamp struct {
	EndingTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ending_timestamp,json=endingTimestamp,proto3,oneof"`
}

type ScaleParameter_ScaleFactor struct {
	ScaleFactor float64 `protobuf:"fixed64,3,opt,name=scale_factor,json=scaleFactor,proto3,oneof"`
}

func (*ScaleParameter_TrueFrameRate) isScaleParameter_ScaleParameter() {}

func (*ScaleParameter_EndingTimestamp) isScaleParameter_ScaleParameter() {}

func (*ScaleParameter_ScaleFactor) isScaleParameter_ScaleParameter() {}

var File_nominal_protos_ingest_v2_video_ingest_proto protoreflect.FileDescriptor

const file_nominal_protos_ingest_v2_video_ingest_proto_rawDesc = "" +
	"\n" +
	"+nominal/protos/ingest/v2/video_ingest.proto\x12\x11nominal.ingest.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!nominal/protos/gen/v1/alias.proto\x1a%nominal/protos/ingest/v2/common.proto\"\x99\x01\n" +
	"\x0fVideoIngestItem\x12?\n" +
	"\x06source\x18\x01 \x01(\v2\x1f.nominal.ingest.v2.IngestSourceB\x06\xbaH\x03\xc8\x01\x01R\x06source\x12E\n" +
	"\x06ingest\x18\x02 \x01(\v2%.nominal.ingest.v2.VideoIngestOptionsB\x06\xbaH\x03\xc8\x01\x01R\x06ingest\"\xff\x01\n" +
	"\x12VideoIngestOptions\x12`\n" +
	"\x12timestamp_manifest\x18\x01 \x01(\v2).nominal.ingest.v2.VideoTimestampManifestB\x06\xbaH\x03\xc8\x01\x01R\x11timestampManifest\x12<\n" +
	"\achannel\x18\x02 \x01(\tB\"\xbaH\x03\xc8\x01\x01\x9a\xb2\x1a\x18\n" +
	"\x16io.nominal.api.ChannelR\achannel\x122\n" +
	"\x12overwrite_segments\x18\x03 \x01(\bH\x00R\x11overwriteSegments\x88\x01\x01B\x15\n" +
	"\x13_overwrite_segments\"\x9d\x02\n" +
	"\x16VideoTimestampManifest\x12I\n" +
	"\vno_manifest\x18\x01 \x01(\v2&.nominal.ingest.v2.NoTimestampManifestH\x00R\n" +
	"noManifest\x12e\n" +
	"\x18timestamp_manifest_files\x18\x02 \x01(\v2).nominal.ingest.v2.TimestampManifestFilesH\x00R\x16timestampManifestFiles\x12>\n" +
	"\x04mcap\x18\x03 \x01(\v2(.nominal.ingest.v2.McapTimestampManifestH\x00R\x04mcapB\x11\n" +
	"\bmanifest\x12\x05\xbaH\x02\b\x01\"\xcd\x01\n" +
	"\x13NoTimestampManifest\x12Q\n" +
	"\x12starting_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x11startingTimestamp\x12O\n" +
	"\x0fscale_parameter\x18\x02 \x01(\v2!.nominal.ingest.v2.ScaleParameterH\x00R\x0escaleParameter\x88\x01\x01B\x12\n" +
	"\x10_scale_parameter\"]\n" +
	"\x16TimestampManifestFiles\x12C\n" +
	"\asources\x18\x01 \x03(\v2\x1f.nominal.ingest.v2.IngestSourceB\b\xbaH\x05\x92\x01\x02\b\x01R\asources\"o\n" +
	"\x15McapTimestampManifest\x12V\n" +
	"\x0fchannel_locator\x18\x01 \x01(\v2%.nominal.ingest.v2.McapChannelLocatorB\x06\xbaH\x03\xc8\x01\x01R\x0echannelLocator\"\x9b\x01\n" +
	"\x12McapChannelLocator\x12=\n" +
	"\x05topic\x18\x01 \x01(\tB%\x9a\xb2\x1a!\n" +
	"\x1fio.nominal.api.McapChannelTopicH\x00R\x05topic\x124\n" +
	"\x02id\x18\x02 \x01(\x05B\"\x9a\xb2\x1a\x1e\n" +
	"\x1cio.nominal.api.McapChannelIdH\x00R\x02idB\x10\n" +
	"\alocator\x12\x05\xbaH\x02\b\x01\"\xc2\x01\n" +
	"\x0eScaleParameter\x12(\n" +
	"\x0ftrue_frame_rate\x18\x01 \x01(\x01H\x00R\rtrueFrameRate\x12G\n" +
	"\x10ending_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0fendingTimestamp\x12#\n" +
	"\fscale_factor\x18\x03 \x01(\x01H\x00R\vscaleFactorB\x18\n" +
	"\x0fscale_parameter\x12\x05\xbaH\x02\b\x01B\xde\x01\n" +
	"\x15com.nominal.ingest.v2B\x10VideoIngestProtoP\x01ZMgithub.com/nominal-io/nominal-api-protos-go/nominal/protos/ingest/v2;ingestv2\xa2\x02\x03NIX\xaa\x02\x11Nominal.Ingest.V2\xca\x02\x11Nominal\\Ingest\\V2\xe2\x02\x1dNominal\\Ingest\\V2\\GPBMetadata\xea\x02\x13Nominal::Ingest::V2b\x06proto3"

var (
	file_nominal_protos_ingest_v2_video_ingest_proto_rawDescOnce sync.Once
	file_nominal_protos_ingest_v2_video_ingest_proto_rawDescData []byte
)

func file_nominal_protos_ingest_v2_video_ingest_proto_rawDescGZIP() []byte {
	file_nominal_protos_ingest_v2_video_ingest_proto_rawDescOnce.Do(func() {
		file_nominal_protos_ingest_v2_video_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nominal_protos_ingest_v2_video_ingest_proto_rawDesc), len(file_nominal_protos_ingest_v2_video_ingest_proto_rawDesc)))
	})
	return file_nominal_protos_ingest_v2_video_ingest_proto_rawDescData
}

var file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nominal_protos_ingest_v2_video_ingest_proto_goTypes = []any{
	(*VideoIngestItem)(nil),        // 0: nominal.ingest.v2.VideoIngestItem
	(*VideoIngestOptions)(nil),     // 1: nominal.ingest.v2.VideoIngestOptions
	(*VideoTimestampManifest)(nil), // 2: nominal.ingest.v2.VideoTimestampManifest
	(*NoTimestampManifest)(nil),    // 3: nominal.ingest.v2.NoTimestampManifest
	(*TimestampManifestFiles)(nil), // 4: nominal.ingest.v2.TimestampManifestFiles
	(*McapTimestampManifest)(nil),  // 5: nominal.ingest.v2.McapTimestampManifest
	(*McapChannelLocator)(nil),     // 6: nominal.ingest.v2.McapChannelLocator
	(*ScaleParameter)(nil),         // 7: nominal.ingest.v2.ScaleParameter
	(*IngestSource)(nil),           // 8: nominal.ingest.v2.IngestSource
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_nominal_protos_ingest_v2_video_ingest_proto_depIdxs = []int32{
	8,  // 0: nominal.ingest.v2.VideoIngestItem.source:type_name -> nominal.ingest.v2.IngestSource
	1,  // 1: nominal.ingest.v2.VideoIngestItem.ingest:type_name -> nominal.ingest.v2.VideoIngestOptions
	2,  // 2: nominal.ingest.v2.VideoIngestOptions.timestamp_manifest:type_name -> nominal.ingest.v2.VideoTimestampManifest
	3,  // 3: nominal.ingest.v2.VideoTimestampManifest.no_manifest:type_name -> nominal.ingest.v2.NoTimestampManifest
	4,  // 4: nominal.ingest.v2.VideoTimestampManifest.timestamp_manifest_files:type_name -> nominal.ingest.v2.TimestampManifestFiles
	5,  // 5: nominal.ingest.v2.VideoTimestampManifest.mcap:type_name -> nominal.ingest.v2.McapTimestampManifest
	9,  // 6: nominal.ingest.v2.NoTimestampManifest.starting_timestamp:type_name -> google.protobuf.Timestamp
	7,  // 7: nominal.ingest.v2.NoTimestampManifest.scale_parameter:type_name -> nominal.ingest.v2.ScaleParameter
	8,  // 8: nominal.ingest.v2.TimestampManifestFiles.sources:type_name -> nominal.ingest.v2.IngestSource
	6,  // 9: nominal.ingest.v2.McapTimestampManifest.channel_locator:type_name -> nominal.ingest.v2.McapChannelLocator
	9,  // 10: nominal.ingest.v2.ScaleParameter.ending_timestamp:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_nominal_protos_ingest_v2_video_ingest_proto_init() }
func file_nominal_protos_ingest_v2_video_ingest_proto_init() {
	if File_nominal_protos_ingest_v2_video_ingest_proto != nil {
		return
	}
	file_nominal_protos_ingest_v2_common_proto_init()
	file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[1].OneofWrappers = []any{}
	file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[2].OneofWrappers = []any{
		(*VideoTimestampManifest_NoManifest)(nil),
		(*VideoTimestampManifest_TimestampManifestFiles)(nil),
		(*VideoTimestampManifest_Mcap)(nil),
	}
	file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[3].OneofWrappers = []any{}
	file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[6].OneofWrappers = []any{
		(*McapChannelLocator_Topic)(nil),
		(*McapChannelLocator_Id)(nil),
	}
	file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes[7].OneofWrappers = []any{
		(*ScaleParameter_TrueFrameRate)(nil),
		(*ScaleParameter_EndingTimestamp)(nil),
		(*ScaleParameter_ScaleFactor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nominal_protos_ingest_v2_video_ingest_proto_rawDesc), len(file_nominal_protos_ingest_v2_video_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nominal_protos_ingest_v2_video_ingest_proto_goTypes,
		DependencyIndexes: file_nominal_protos_ingest_v2_video_ingest_proto_depIdxs,
		MessageInfos:      file_nominal_protos_ingest_v2_video_ingest_proto_msgTypes,
	}.Build()
	File_nominal_protos_ingest_v2_video_ingest_proto = out.File
	file_nominal_protos_ingest_v2_video_ingest_proto_goTypes = nil
	file_nominal_protos_ingest_v2_video_ingest_proto_depIdxs = nil
}
