// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/connect/v1/connect_apps.proto

package connectv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectAppsService_CreateConnectApp_FullMethodName               = "/nominal.connect.v1.ConnectAppsService/CreateConnectApp"
	ConnectAppsService_GetConnectApp_FullMethodName                  = "/nominal.connect.v1.ConnectAppsService/GetConnectApp"
	ConnectAppsService_UpdateConnectAppMetadata_FullMethodName       = "/nominal.connect.v1.ConnectAppsService/UpdateConnectAppMetadata"
	ConnectAppsService_Commit_FullMethodName                         = "/nominal.connect.v1.ConnectAppsService/Commit"
	ConnectAppsService_SearchConnectApps_FullMethodName              = "/nominal.connect.v1.ConnectAppsService/SearchConnectApps"
	ConnectAppsService_ArchiveConnectApps_FullMethodName             = "/nominal.connect.v1.ConnectAppsService/ArchiveConnectApps"
	ConnectAppsService_UnarchiveConnectApps_FullMethodName           = "/nominal.connect.v1.ConnectAppsService/UnarchiveConnectApps"
	ConnectAppsService_GetConnectAppBundleDownloadUrl_FullMethodName = "/nominal.connect.v1.ConnectAppsService/GetConnectAppBundleDownloadUrl"
)

// ConnectAppsServiceClient is the client API for ConnectAppsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for creating and managing Connect Apps
type ConnectAppsServiceClient interface {
	// Create a new Connect App, either with a bundle file or as an empty app
	CreateConnectApp(ctx context.Context, in *CreateConnectAppRequest, opts ...grpc.CallOption) (*CreateConnectAppResponse, error)
	// Get a Connect App by its RID
	GetConnectApp(ctx context.Context, in *GetConnectAppRequest, opts ...grpc.CallOption) (*GetConnectAppResponse, error)
	// Update metadata fields of a Connect App
	UpdateConnectAppMetadata(ctx context.Context, in *UpdateConnectAppMetadataRequest, opts ...grpc.CallOption) (*UpdateConnectAppMetadataResponse, error)
	// Commit a bundle to the main branch
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// Searches for Connect Apps, returning paged results
	SearchConnectApps(ctx context.Context, in *SearchConnectAppsRequest, opts ...grpc.CallOption) (*SearchConnectAppsResponse, error)
	// Archive Connect Apps
	ArchiveConnectApps(ctx context.Context, in *ArchiveConnectAppsRequest, opts ...grpc.CallOption) (*ArchiveConnectAppsResponse, error)
	// Unarchive Connect Apps
	UnarchiveConnectApps(ctx context.Context, in *UnarchiveConnectAppsRequest, opts ...grpc.CallOption) (*UnarchiveConnectAppsResponse, error)
	// Get a pre-signed URL for downloading the bundle of a Connect App at a specific commit or the latest commit on the main branch
	GetConnectAppBundleDownloadUrl(ctx context.Context, in *GetConnectAppBundleDownloadUrlRequest, opts ...grpc.CallOption) (*GetConnectAppBundleDownloadUrlResponse, error)
}

type connectAppsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectAppsServiceClient(cc grpc.ClientConnInterface) ConnectAppsServiceClient {
	return &connectAppsServiceClient{cc}
}

func (c *connectAppsServiceClient) CreateConnectApp(ctx context.Context, in *CreateConnectAppRequest, opts ...grpc.CallOption) (*CreateConnectAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConnectAppResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_CreateConnectApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectAppsServiceClient) GetConnectApp(ctx context.Context, in *GetConnectAppRequest, opts ...grpc.CallOption) (*GetConnectAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectAppResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_GetConnectApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectAppsServiceClient) UpdateConnectAppMetadata(ctx context.Context, in *UpdateConnectAppMetadataRequest, opts ...grpc.CallOption) (*UpdateConnectAppMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConnectAppMetadataResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_UpdateConnectAppMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectAppsServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectAppsServiceClient) SearchConnectApps(ctx context.Context, in *SearchConnectAppsRequest, opts ...grpc.CallOption) (*SearchConnectAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchConnectAppsResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_SearchConnectApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectAppsServiceClient) ArchiveConnectApps(ctx context.Context, in *ArchiveConnectAppsRequest, opts ...grpc.CallOption) (*ArchiveConnectAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveConnectAppsResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_ArchiveConnectApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectAppsServiceClient) UnarchiveConnectApps(ctx context.Context, in *UnarchiveConnectAppsRequest, opts ...grpc.CallOption) (*UnarchiveConnectAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnarchiveConnectAppsResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_UnarchiveConnectApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectAppsServiceClient) GetConnectAppBundleDownloadUrl(ctx context.Context, in *GetConnectAppBundleDownloadUrlRequest, opts ...grpc.CallOption) (*GetConnectAppBundleDownloadUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectAppBundleDownloadUrlResponse)
	err := c.cc.Invoke(ctx, ConnectAppsService_GetConnectAppBundleDownloadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectAppsServiceServer is the server API for ConnectAppsService service.
// All implementations must embed UnimplementedConnectAppsServiceServer
// for forward compatibility.
//
// Service for creating and managing Connect Apps
type ConnectAppsServiceServer interface {
	// Create a new Connect App, either with a bundle file or as an empty app
	CreateConnectApp(context.Context, *CreateConnectAppRequest) (*CreateConnectAppResponse, error)
	// Get a Connect App by its RID
	GetConnectApp(context.Context, *GetConnectAppRequest) (*GetConnectAppResponse, error)
	// Update metadata fields of a Connect App
	UpdateConnectAppMetadata(context.Context, *UpdateConnectAppMetadataRequest) (*UpdateConnectAppMetadataResponse, error)
	// Commit a bundle to the main branch
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// Searches for Connect Apps, returning paged results
	SearchConnectApps(context.Context, *SearchConnectAppsRequest) (*SearchConnectAppsResponse, error)
	// Archive Connect Apps
	ArchiveConnectApps(context.Context, *ArchiveConnectAppsRequest) (*ArchiveConnectAppsResponse, error)
	// Unarchive Connect Apps
	UnarchiveConnectApps(context.Context, *UnarchiveConnectAppsRequest) (*UnarchiveConnectAppsResponse, error)
	// Get a pre-signed URL for downloading the bundle of a Connect App at a specific commit or the latest commit on the main branch
	GetConnectAppBundleDownloadUrl(context.Context, *GetConnectAppBundleDownloadUrlRequest) (*GetConnectAppBundleDownloadUrlResponse, error)
	mustEmbedUnimplementedConnectAppsServiceServer()
}

// UnimplementedConnectAppsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectAppsServiceServer struct{}

func (UnimplementedConnectAppsServiceServer) CreateConnectApp(context.Context, *CreateConnectAppRequest) (*CreateConnectAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConnectApp not implemented")
}
func (UnimplementedConnectAppsServiceServer) GetConnectApp(context.Context, *GetConnectAppRequest) (*GetConnectAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectApp not implemented")
}
func (UnimplementedConnectAppsServiceServer) UpdateConnectAppMetadata(context.Context, *UpdateConnectAppMetadataRequest) (*UpdateConnectAppMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConnectAppMetadata not implemented")
}
func (UnimplementedConnectAppsServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedConnectAppsServiceServer) SearchConnectApps(context.Context, *SearchConnectAppsRequest) (*SearchConnectAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchConnectApps not implemented")
}
func (UnimplementedConnectAppsServiceServer) ArchiveConnectApps(context.Context, *ArchiveConnectAppsRequest) (*ArchiveConnectAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveConnectApps not implemented")
}
func (UnimplementedConnectAppsServiceServer) UnarchiveConnectApps(context.Context, *UnarchiveConnectAppsRequest) (*UnarchiveConnectAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnarchiveConnectApps not implemented")
}
func (UnimplementedConnectAppsServiceServer) GetConnectAppBundleDownloadUrl(context.Context, *GetConnectAppBundleDownloadUrlRequest) (*GetConnectAppBundleDownloadUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectAppBundleDownloadUrl not implemented")
}
func (UnimplementedConnectAppsServiceServer) mustEmbedUnimplementedConnectAppsServiceServer() {}
func (UnimplementedConnectAppsServiceServer) testEmbeddedByValue()                            {}

// UnsafeConnectAppsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectAppsServiceServer will
// result in compilation errors.
type UnsafeConnectAppsServiceServer interface {
	mustEmbedUnimplementedConnectAppsServiceServer()
}

func RegisterConnectAppsServiceServer(s grpc.ServiceRegistrar, srv ConnectAppsServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectAppsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectAppsService_ServiceDesc, srv)
}

func _ConnectAppsService_CreateConnectApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).CreateConnectApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_CreateConnectApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).CreateConnectApp(ctx, req.(*CreateConnectAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectAppsService_GetConnectApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).GetConnectApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_GetConnectApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).GetConnectApp(ctx, req.(*GetConnectAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectAppsService_UpdateConnectAppMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConnectAppMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).UpdateConnectAppMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_UpdateConnectAppMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).UpdateConnectAppMetadata(ctx, req.(*UpdateConnectAppMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectAppsService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectAppsService_SearchConnectApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchConnectAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).SearchConnectApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_SearchConnectApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).SearchConnectApps(ctx, req.(*SearchConnectAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectAppsService_ArchiveConnectApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveConnectAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).ArchiveConnectApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_ArchiveConnectApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).ArchiveConnectApps(ctx, req.(*ArchiveConnectAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectAppsService_UnarchiveConnectApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnarchiveConnectAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).UnarchiveConnectApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_UnarchiveConnectApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).UnarchiveConnectApps(ctx, req.(*UnarchiveConnectAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectAppsService_GetConnectAppBundleDownloadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectAppBundleDownloadUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectAppsServiceServer).GetConnectAppBundleDownloadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectAppsService_GetConnectAppBundleDownloadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectAppsServiceServer).GetConnectAppBundleDownloadUrl(ctx, req.(*GetConnectAppBundleDownloadUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectAppsService_ServiceDesc is the grpc.ServiceDesc for ConnectAppsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectAppsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.connect.v1.ConnectAppsService",
	HandlerType: (*ConnectAppsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConnectApp",
			Handler:    _ConnectAppsService_CreateConnectApp_Handler,
		},
		{
			MethodName: "GetConnectApp",
			Handler:    _ConnectAppsService_GetConnectApp_Handler,
		},
		{
			MethodName: "UpdateConnectAppMetadata",
			Handler:    _ConnectAppsService_UpdateConnectAppMetadata_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _ConnectAppsService_Commit_Handler,
		},
		{
			MethodName: "SearchConnectApps",
			Handler:    _ConnectAppsService_SearchConnectApps_Handler,
		},
		{
			MethodName: "ArchiveConnectApps",
			Handler:    _ConnectAppsService_ArchiveConnectApps_Handler,
		},
		{
			MethodName: "UnarchiveConnectApps",
			Handler:    _ConnectAppsService_UnarchiveConnectApps_Handler,
		},
		{
			MethodName: "GetConnectAppBundleDownloadUrl",
			Handler:    _ConnectAppsService_GetConnectAppBundleDownloadUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nominal/protos/connect/v1/connect_apps.proto",
}
