// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nominal/protos/connections/v1/external_api_connections.proto

package connectionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionsService_ListChannels_FullMethodName = "/nominal.connections.v1.ConnectionsService/ListChannels"
	ConnectionsService_QueryChannel_FullMethodName = "/nominal.connections.v1.ConnectionsService/QueryChannel"
)

// ConnectionsServiceClient is the client API for ConnectionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Defines the interface for how Nominal expects to interact with custom connection implementations. All sources of
// time series data is abstracted by a channel identifier, allowing for flexibility of the underlying data source
// implementations.
//
// The authorization credentials are passed as http headers as:
//
//	"Authorization: Bearer <token>"
type ConnectionsServiceClient interface {
	// *
	// Paging endpoint to list all the channels and their allowed tag values. Callers should expect that more results are
	// available as long as ListChannelsResponse continues to return a pageToken and will pass in this pageToken in the
	// next ListChannelsRequest.
	ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error)
	// *
	// Endpoint to query a given channel for time series data for a given set of tags and time range. The response is a
	// stream of points.
	QueryChannel(ctx context.Context, in *QueryChannelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryChannelResponse], error)
}

type connectionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionsServiceClient(cc grpc.ClientConnInterface) ConnectionsServiceClient {
	return &connectionsServiceClient{cc}
}

func (c *connectionsServiceClient) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsResponse)
	err := c.cc.Invoke(ctx, ConnectionsService_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionsServiceClient) QueryChannel(ctx context.Context, in *QueryChannelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryChannelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectionsService_ServiceDesc.Streams[0], ConnectionsService_QueryChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryChannelRequest, QueryChannelResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionsService_QueryChannelClient = grpc.ServerStreamingClient[QueryChannelResponse]

// ConnectionsServiceServer is the server API for ConnectionsService service.
// All implementations must embed UnimplementedConnectionsServiceServer
// for forward compatibility.
//
// *
// Defines the interface for how Nominal expects to interact with custom connection implementations. All sources of
// time series data is abstracted by a channel identifier, allowing for flexibility of the underlying data source
// implementations.
//
// The authorization credentials are passed as http headers as:
//
//	"Authorization: Bearer <token>"
type ConnectionsServiceServer interface {
	// *
	// Paging endpoint to list all the channels and their allowed tag values. Callers should expect that more results are
	// available as long as ListChannelsResponse continues to return a pageToken and will pass in this pageToken in the
	// next ListChannelsRequest.
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error)
	// *
	// Endpoint to query a given channel for time series data for a given set of tags and time range. The response is a
	// stream of points.
	QueryChannel(*QueryChannelRequest, grpc.ServerStreamingServer[QueryChannelResponse]) error
	mustEmbedUnimplementedConnectionsServiceServer()
}

// UnimplementedConnectionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionsServiceServer struct{}

func (UnimplementedConnectionsServiceServer) ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedConnectionsServiceServer) QueryChannel(*QueryChannelRequest, grpc.ServerStreamingServer[QueryChannelResponse]) error {
	return status.Error(codes.Unimplemented, "method QueryChannel not implemented")
}
func (UnimplementedConnectionsServiceServer) mustEmbedUnimplementedConnectionsServiceServer() {}
func (UnimplementedConnectionsServiceServer) testEmbeddedByValue()                            {}

// UnsafeConnectionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionsServiceServer will
// result in compilation errors.
type UnsafeConnectionsServiceServer interface {
	mustEmbedUnimplementedConnectionsServiceServer()
}

func RegisterConnectionsServiceServer(s grpc.ServiceRegistrar, srv ConnectionsServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionsService_ServiceDesc, srv)
}

func _ConnectionsService_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionsServiceServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionsService_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionsServiceServer).ListChannels(ctx, req.(*ListChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionsService_QueryChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryChannelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectionsServiceServer).QueryChannel(m, &grpc.GenericServerStream[QueryChannelRequest, QueryChannelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionsService_QueryChannelServer = grpc.ServerStreamingServer[QueryChannelResponse]

// ConnectionsService_ServiceDesc is the grpc.ServiceDesc for ConnectionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nominal.connections.v1.ConnectionsService",
	HandlerType: (*ConnectionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChannels",
			Handler:    _ConnectionsService_ListChannels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryChannel",
			Handler:       _ConnectionsService_QueryChannel_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nominal/protos/connections/v1/external_api_connections.proto",
}
